# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: croupier/api/v1/management.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'croupier/api/v1/management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n croupier/api/v1/management.proto\x12\x0f\x63roupier.api.v1\"\xc4\x01\n\x11ManagementRequest\x12\x1c\n\toperation\x18\x01 \x01(\tR\toperation\x12R\n\nparameters\x18\x02 \x03(\x0b\x32\x32.croupier.api.v1.ManagementRequest.ParametersEntryR\nparameters\x1a=\n\x0fParametersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"B\n\x12ManagementResponse\x12\x16\n\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n\x05\x65rror\x18\x02 \x01(\tR\x05\x65rror2f\n\x11ManagementService\x12Q\n\x06Manage\x12\".croupier.api.v1.ManagementRequest\x1a#.croupier.api.v1.ManagementResponseBa\n\"io.github.cuihairu.croupier.api.v1P\x01Z9github.com/cuihairu/croupier/pkg/pb/croupier/api/v1;apiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'croupier.api.v1.management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"io.github.cuihairu.croupier.api.v1P\001Z9github.com/cuihairu/croupier/pkg/pb/croupier/api/v1;apiv1'
  _globals['_MANAGEMENTREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_MANAGEMENTREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_MANAGEMENTREQUEST']._serialized_start=54
  _globals['_MANAGEMENTREQUEST']._serialized_end=250
  _globals['_MANAGEMENTREQUEST_PARAMETERSENTRY']._serialized_start=189
  _globals['_MANAGEMENTREQUEST_PARAMETERSENTRY']._serialized_end=250
  _globals['_MANAGEMENTRESPONSE']._serialized_start=252
  _globals['_MANAGEMENTRESPONSE']._serialized_end=318
  _globals['_MANAGEMENTSERVICE']._serialized_start=320
  _globals['_MANAGEMENTSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
