// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: croupier/sdk/v1/invocation.proto

package sdkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SDK Function Invocation Request.
// payload is always UTF-8 JSON in protocol v1.
type InvokeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FunctionId     string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`                                                     // e.g. "player.ban"
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`                                         // client-supplied idempotency key
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // serialized request JSON bytes
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // optional k/v metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *InvokeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SDK Function Invocation Response.
// payload is always UTF-8 JSON in protocol v1.
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // serialized response JSON bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_invocation_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SDK Task Start Response
type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_invocation_proto_rawDescGZIP(), []int{2}
}

func (x *StartTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// SDK Task Stream Request
type TaskStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamRequest) Reset() {
	*x = TaskStreamRequest{}
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamRequest) ProtoMessage() {}

func (x *TaskStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamRequest.ProtoReflect.Descriptor instead.
func (*TaskStreamRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_invocation_proto_rawDescGZIP(), []int{3}
}

func (x *TaskStreamRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// SDK Task Event.
// payload is always UTF-8 JSON in protocol v1.
type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`          // "queued" | "started" | "progress" | "log" | "completed" | "failed" | "cancel_requested" | "cancelled"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`    // free text for log/error
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"` // 0..100 when type == progress
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`    // optional JSON bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_invocation_proto_rawDescGZIP(), []int{4}
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskEvent) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SDK Task Cancellation Request
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_invocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_invocation_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_croupier_sdk_v1_invocation_proto protoreflect.FileDescriptor

const file_croupier_sdk_v1_invocation_proto_rawDesc = "" +
	"\n" +
	" croupier/sdk/v1/invocation.proto\x12\x0fcroupier.sdk.v1\"\xfa\x01\n" +
	"\rInvokeRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.croupier.sdk.v1.InvokeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x0eInvokeResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\",\n" +
	"\x11StartTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\",\n" +
	"\x11TaskStreamRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x88\x01\n" +
	"\tTaskEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskIdBa\n" +
	"\"io.github.cuihairu.croupier.sdk.v1P\x01Z9github.com/cuihairu/croupier/sdks/go/pkg/pb/croupier/sdk/v1;sdkv1b\x06proto3"

var (
	file_croupier_sdk_v1_invocation_proto_rawDescOnce sync.Once
	file_croupier_sdk_v1_invocation_proto_rawDescData []byte
)

func file_croupier_sdk_v1_invocation_proto_rawDescGZIP() []byte {
	file_croupier_sdk_v1_invocation_proto_rawDescOnce.Do(func() {
		file_croupier_sdk_v1_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_sdk_v1_invocation_proto_rawDesc), len(file_croupier_sdk_v1_invocation_proto_rawDesc)))
	})
	return file_croupier_sdk_v1_invocation_proto_rawDescData
}

var file_croupier_sdk_v1_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_croupier_sdk_v1_invocation_proto_goTypes = []any{
	(*InvokeRequest)(nil),     // 0: croupier.sdk.v1.InvokeRequest
	(*InvokeResponse)(nil),    // 1: croupier.sdk.v1.InvokeResponse
	(*StartTaskResponse)(nil), // 2: croupier.sdk.v1.StartTaskResponse
	(*TaskStreamRequest)(nil), // 3: croupier.sdk.v1.TaskStreamRequest
	(*TaskEvent)(nil),         // 4: croupier.sdk.v1.TaskEvent
	(*CancelTaskRequest)(nil), // 5: croupier.sdk.v1.CancelTaskRequest
	nil,                       // 6: croupier.sdk.v1.InvokeRequest.MetadataEntry
}
var file_croupier_sdk_v1_invocation_proto_depIdxs = []int32{
	6, // 0: croupier.sdk.v1.InvokeRequest.metadata:type_name -> croupier.sdk.v1.InvokeRequest.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_croupier_sdk_v1_invocation_proto_init() }
func file_croupier_sdk_v1_invocation_proto_init() {
	if File_croupier_sdk_v1_invocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_sdk_v1_invocation_proto_rawDesc), len(file_croupier_sdk_v1_invocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_croupier_sdk_v1_invocation_proto_goTypes,
		DependencyIndexes: file_croupier_sdk_v1_invocation_proto_depIdxs,
		MessageInfos:      file_croupier_sdk_v1_invocation_proto_msgTypes,
	}.Build()
	File_croupier_sdk_v1_invocation_proto = out.File
	file_croupier_sdk_v1_invocation_proto_goTypes = nil
	file_croupier_sdk_v1_invocation_proto_depIdxs = nil
}
