# syntax=docker/dockerfile:1
ARG GO_IMAGE=golang:1.21
ARG RUNTIME_IMAGE=gcr.io/distroless/static:nonroot
FROM ${GO_IMAGE} as build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOFLAGS=-mod=mod go build -o /out/croupier-server ./cmd/server

FROM ${RUNTIME_IMAGE}
WORKDIR /app
COPY --from=build /out/croupier-server /app/
COPY configs /app/configs
EXPOSE 8443 8080
USER nonroot
ENTRYPOINT ["/app/croupier-server"]
