package registrationguard

import "strings"

var forbiddenPresentationFields = map[string]struct{}{
	"categorydisplay":     {},
	"category-display":    {},
	"category_display":    {},
	"displayname":         {},
	"display-name":        {},
	"display_name":        {},
	"entitydisplay":       {},
	"entity-display":      {},
	"entity_display":      {},
	"formily":             {},
	"inputmapping":        {},
	"input-mapping":       {},
	"input_mapping":       {},
	"layout":              {},
	"menu":                {},
	"operationdisplay":    {},
	"operation-display":   {},
	"operation_display":   {},
	"operationkind":       {},
	"operation-kind":      {},
	"operation_kind":      {},
	"outputmapping":       {},
	"output-mapping":      {},
	"output_mapping":      {},
	"pagecontract":        {},
	"page-contract":       {},
	"page_contract":       {},
	"pagehint":            {},
	"page-hint":           {},
	"page_hint":           {},
	"pageschema":          {},
	"page-schema":         {},
	"page_schema":         {},
	"placement":           {},
	"pagination":          {},
	"route":               {},
	"routes":              {},
	"table":               {},
	"tablecolumns":        {},
	"table-columns":       {},
	"table_columns":       {},
	"ui":                  {},
	"x-category-display":  {},
	"x_category_display":  {},
	"x-components":        {},
	"x_components":        {},
	"x-display-name":      {},
	"x_display_name":      {},
	"x-entity-display":    {},
	"x_entity_display":    {},
	"x-formily":           {},
	"x_formily":           {},
	"x-layout":            {},
	"x_layout":            {},
	"x-menu":              {},
	"x-operation-display": {},
	"x_operation_display": {},
	"x-operation-kind":    {},
	"x_operation_kind":    {},
	"x-output-mapping":    {},
	"x_output_mapping":    {},
	"x-page":              {},
	"x-page-contract":     {},
	"x_page_contract":     {},
	"x-page-hint":         {},
	"x_page_hint":         {},
	"x-page-schema":       {},
	"x_page_schema":       {},
	"x-pagination":        {},
	"x_pagination":        {},
	"x-placement":         {},
	"x_placement":         {},
	"x-route":             {},
	"x-routes":            {},
	"x-table":             {},
	"x-table-columns":     {},
	"x_table":             {},
	"x_table_columns":     {},
	"x-ui":                {},
	"x_ui":                {},
	"x-input-mapping":     {},
	"x_input_mapping":     {},
}

// ForbiddenPresentationField reports whether key tries to attach presentation,
// navigation, or page-composition concerns to a function capability contract.
func ForbiddenPresentationField(key string) (string, bool) {
	normalized := strings.TrimSpace(strings.ToLower(key))
	if normalized == "" {
		return "", false
	}
	normalized = strings.ReplaceAll(normalized, " ", "")
	if _, ok := forbiddenPresentationFields[normalized]; ok {
		return normalized, true
	}
	return normalized, false
}
