// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: croupier/component/v1/ui_options.proto

package componentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 已废弃：字段级 UI 元信息。
//
// UI 生成完全由 Server 端负责（见 docs/architecture/ui-generation.md）。
// Proto 层只定义 API 契约（类型、约束、语义），不定义展示细节。
// 字段的 widget、label、placeholder、条件显示等应由以下方式提供：
//  1. Server 端从 JSON Schema 自动推导
//  2. configs/ui/ 文件级配置覆盖
//  3. Dashboard UI 编辑器持久化
//
// 保留此消息定义以维持 wire 兼容性，新代码不应使用。
//
// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
type UIFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组件：input/textarea/number/select/checkbox/radio/switch/date/time/json-editor/file
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	Widget string `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	// 标签文本/i18n key
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// 占位符
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	Placeholder string `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	// 敏感字段（审计脱敏）
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	Sensitive bool `protobuf:"varint,4,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	// 静态枚举：value→label
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	EnumMap map[string]string `protobuf:"bytes,5,rep,name=enum_map,json=enumMap,proto3" json:"enum_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 显隐/必填（表达式，CEL 语义，基于请求体字段）
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	ShowIf string `protobuf:"bytes,6,opt,name=show_if,json=showIf,proto3" json:"show_if,omitempty"`
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	RequiredIf    string `protobuf:"bytes,7,opt,name=required_if,json=requiredIf,proto3" json:"required_if,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIFieldOptions) Reset() {
	*x = UIFieldOptions{}
	mi := &file_croupier_component_v1_ui_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIFieldOptions) ProtoMessage() {}

func (x *UIFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_component_v1_ui_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIFieldOptions.ProtoReflect.Descriptor instead.
func (*UIFieldOptions) Descriptor() ([]byte, []int) {
	return file_croupier_component_v1_ui_options_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetWidget() string {
	if x != nil {
		return x.Widget
	}
	return ""
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetEnumMap() map[string]string {
	if x != nil {
		return x.EnumMap
	}
	return nil
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetShowIf() string {
	if x != nil {
		return x.ShowIf
	}
	return ""
}

// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
func (x *UIFieldOptions) GetRequiredIf() string {
	if x != nil {
		return x.RequiredIf
	}
	return ""
}

var file_croupier_component_v1_ui_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*UIFieldOptions)(nil),
		Field:         52001,
		Name:          "croupier.component.v1.ui",
		Tag:           "bytes,52001,opt,name=ui",
		Filename:      "croupier/component/v1/ui_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional croupier.component.v1.UIFieldOptions ui = 52001;
	//
	// Deprecated: Marked as deprecated in croupier/component/v1/ui_options.proto.
	E_Ui = &file_croupier_component_v1_ui_options_proto_extTypes[0]
)

var File_croupier_component_v1_ui_options_proto protoreflect.FileDescriptor

const file_croupier_component_v1_ui_options_proto_rawDesc = "" +
	"\n" +
	"&croupier/component/v1/ui_options.proto\x12\x15croupier.component.v1\x1a google/protobuf/descriptor.proto\"\xe3\x02\n" +
	"\x0eUIFieldOptions\x12\x1a\n" +
	"\x06widget\x18\x01 \x01(\tB\x02\x18\x01R\x06widget\x12\x18\n" +
	"\x05label\x18\x02 \x01(\tB\x02\x18\x01R\x05label\x12$\n" +
	"\vplaceholder\x18\x03 \x01(\tB\x02\x18\x01R\vplaceholder\x12 \n" +
	"\tsensitive\x18\x04 \x01(\bB\x02\x18\x01R\tsensitive\x12Q\n" +
	"\benum_map\x18\x05 \x03(\v22.croupier.component.v1.UIFieldOptions.EnumMapEntryB\x02\x18\x01R\aenumMap\x12\x1b\n" +
	"\ashow_if\x18\x06 \x01(\tB\x02\x18\x01R\x06showIf\x12#\n" +
	"\vrequired_if\x18\a \x01(\tB\x02\x18\x01R\n" +
	"requiredIf\x1a:\n" +
	"\fEnumMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x02\x18\x01:Z\n" +
	"\x02ui\x12\x1d.google.protobuf.FieldOptions\x18\xa1\x96\x03 \x01(\v2%.croupier.component.v1.UIFieldOptionsB\x02\x18\x01R\x02uiB\xf0\x01\n" +
	"\x19com.croupier.component.v1B\x0eUiOptionsProtoP\x01ZMgithub.com/cuihairu/croupier/sdks/go/pkg/pb/croupier/component/v1;componentv1\xa2\x02\x03CCX\xaa\x02\x15Croupier.Component.V1\xca\x02\x15Croupier\\Component\\V1\xe2\x02!Croupier\\Component\\V1\\GPBMetadata\xea\x02\x17Croupier::Component::V1b\x06proto3"

var (
	file_croupier_component_v1_ui_options_proto_rawDescOnce sync.Once
	file_croupier_component_v1_ui_options_proto_rawDescData []byte
)

func file_croupier_component_v1_ui_options_proto_rawDescGZIP() []byte {
	file_croupier_component_v1_ui_options_proto_rawDescOnce.Do(func() {
		file_croupier_component_v1_ui_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_component_v1_ui_options_proto_rawDesc), len(file_croupier_component_v1_ui_options_proto_rawDesc)))
	})
	return file_croupier_component_v1_ui_options_proto_rawDescData
}

var file_croupier_component_v1_ui_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_croupier_component_v1_ui_options_proto_goTypes = []any{
	(*UIFieldOptions)(nil),            // 0: croupier.component.v1.UIFieldOptions
	nil,                               // 1: croupier.component.v1.UIFieldOptions.EnumMapEntry
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_croupier_component_v1_ui_options_proto_depIdxs = []int32{
	1, // 0: croupier.component.v1.UIFieldOptions.enum_map:type_name -> croupier.component.v1.UIFieldOptions.EnumMapEntry
	2, // 1: croupier.component.v1.ui:extendee -> google.protobuf.FieldOptions
	0, // 2: croupier.component.v1.ui:type_name -> croupier.component.v1.UIFieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_croupier_component_v1_ui_options_proto_init() }
func file_croupier_component_v1_ui_options_proto_init() {
	if File_croupier_component_v1_ui_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_component_v1_ui_options_proto_rawDesc), len(file_croupier_component_v1_ui_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_croupier_component_v1_ui_options_proto_goTypes,
		DependencyIndexes: file_croupier_component_v1_ui_options_proto_depIdxs,
		MessageInfos:      file_croupier_component_v1_ui_options_proto_msgTypes,
		ExtensionInfos:    file_croupier_component_v1_ui_options_proto_extTypes,
	}.Build()
	File_croupier_component_v1_ui_options_proto = out.File
	file_croupier_component_v1_ui_options_proto_goTypes = nil
	file_croupier_component_v1_ui_options_proto_depIdxs = nil
}
