// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: croupier/server/v1/server_control.proto

package serverv1

import (
	context "context"
	v1 "github.com/cuihairu/croupier/pkg/pb/croupier/ops/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_ListFunctionsSummary_FullMethodName = "/croupier.server.v1.ControlService/ListFunctionsSummary"
	ControlService_Register_FullMethodName             = "/croupier.server.v1.ControlService/Register"
	ControlService_Heartbeat_FullMethodName            = "/croupier.server.v1.ControlService/Heartbeat"
	ControlService_RegisterCapabilities_FullMethodName = "/croupier.server.v1.ControlService/RegisterCapabilities"
	ControlService_GetAgentSystemInfo_FullMethodName   = "/croupier.server.v1.ControlService/GetAgentSystemInfo"
	ControlService_ListAgentProcesses_FullMethodName   = "/croupier.server.v1.ControlService/ListAgentProcesses"
	ControlService_QueryMetrics_FullMethodName         = "/croupier.server.v1.ControlService/QueryMetrics"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Server Control Service - Internal interface for agent registration and management
type ControlServiceClient interface {
	// Summarized function catalog with UI/RBAC metadata (for dashboard)
	ListFunctionsSummary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListFunctionsSummaryResponse, error)
	// Agent registration with server
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Agent heartbeat
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Provider capabilities registration
	RegisterCapabilities(ctx context.Context, in *RegisterCapabilitiesRequest, opts ...grpc.CallOption) (*RegisterCapabilitiesResponse, error)
	// GetAgentSystemInfo retrieves system info for a specific agent.
	GetAgentSystemInfo(ctx context.Context, in *GetAgentSystemInfoRequest, opts ...grpc.CallOption) (*v1.SystemInfo, error)
	// ListAgentProcesses lists processes on a specific agent.
	ListAgentProcesses(ctx context.Context, in *ListAgentProcessesRequest, opts ...grpc.CallOption) (*v1.ListProcessesResponse, error)
	// QueryMetrics queries stored metrics from agents.
	QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) ListFunctionsSummary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListFunctionsSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFunctionsSummaryResponse)
	err := c.cc.Invoke(ctx, ControlService_ListFunctionsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ControlService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RegisterCapabilities(ctx context.Context, in *RegisterCapabilitiesRequest, opts ...grpc.CallOption) (*RegisterCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ControlService_RegisterCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetAgentSystemInfo(ctx context.Context, in *GetAgentSystemInfoRequest, opts ...grpc.CallOption) (*v1.SystemInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.SystemInfo)
	err := c.cc.Invoke(ctx, ControlService_GetAgentSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListAgentProcesses(ctx context.Context, in *ListAgentProcessesRequest, opts ...grpc.CallOption) (*v1.ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListProcessesResponse)
	err := c.cc.Invoke(ctx, ControlService_ListAgentProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMetricsResponse)
	err := c.cc.Invoke(ctx, ControlService_QueryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
//
// Server Control Service - Internal interface for agent registration and management
type ControlServiceServer interface {
	// Summarized function catalog with UI/RBAC metadata (for dashboard)
	ListFunctionsSummary(context.Context, *emptypb.Empty) (*ListFunctionsSummaryResponse, error)
	// Agent registration with server
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Agent heartbeat
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Provider capabilities registration
	RegisterCapabilities(context.Context, *RegisterCapabilitiesRequest) (*RegisterCapabilitiesResponse, error)
	// GetAgentSystemInfo retrieves system info for a specific agent.
	GetAgentSystemInfo(context.Context, *GetAgentSystemInfoRequest) (*v1.SystemInfo, error)
	// ListAgentProcesses lists processes on a specific agent.
	ListAgentProcesses(context.Context, *ListAgentProcessesRequest) (*v1.ListProcessesResponse, error)
	// QueryMetrics queries stored metrics from agents.
	QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) ListFunctionsSummary(context.Context, *emptypb.Empty) (*ListFunctionsSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunctionsSummary not implemented")
}
func (UnimplementedControlServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControlServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlServiceServer) RegisterCapabilities(context.Context, *RegisterCapabilitiesRequest) (*RegisterCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCapabilities not implemented")
}
func (UnimplementedControlServiceServer) GetAgentSystemInfo(context.Context, *GetAgentSystemInfoRequest) (*v1.SystemInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentSystemInfo not implemented")
}
func (UnimplementedControlServiceServer) ListAgentProcesses(context.Context, *ListAgentProcessesRequest) (*v1.ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentProcesses not implemented")
}
func (UnimplementedControlServiceServer) QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMetrics not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_ListFunctionsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListFunctionsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListFunctionsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListFunctionsSummary(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RegisterCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RegisterCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RegisterCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RegisterCapabilities(ctx, req.(*RegisterCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetAgentSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetAgentSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetAgentSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetAgentSystemInfo(ctx, req.(*GetAgentSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListAgentProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListAgentProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListAgentProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListAgentProcesses(ctx, req.(*ListAgentProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_QueryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).QueryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_QueryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).QueryMetrics(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.server.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFunctionsSummary",
			Handler:    _ControlService_ListFunctionsSummary_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ControlService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlService_Heartbeat_Handler,
		},
		{
			MethodName: "RegisterCapabilities",
			Handler:    _ControlService_RegisterCapabilities_Handler,
		},
		{
			MethodName: "GetAgentSystemInfo",
			Handler:    _ControlService_GetAgentSystemInfo_Handler,
		},
		{
			MethodName: "ListAgentProcesses",
			Handler:    _ControlService_ListAgentProcesses_Handler,
		},
		{
			MethodName: "QueryMetrics",
			Handler:    _ControlService_QueryMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "croupier/server/v1/server_control.proto",
}
