<template><div><h1 id="客户端上报概览" tabindex="-1"><a class="header-anchor" href="#客户端上报概览"><span>客户端上报概览</span></a></h1>
<p>Go（示例）</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code class="language-go"><span class="line">client <span class="token operator">:=</span> analytics<span class="token punctuation">.</span><span class="token function">NewClient</span><span class="token punctuation">(</span>analytics<span class="token punctuation">.</span>Config<span class="token punctuation">{</span></span>
<span class="line">  Endpoint<span class="token punctuation">:</span> <span class="token string">"https://ingest.example.com"</span><span class="token punctuation">,</span></span>
<span class="line">  Secret<span class="token punctuation">:</span>   os<span class="token punctuation">.</span><span class="token function">Getenv</span><span class="token punctuation">(</span><span class="token string">"ANALYTICS_SECRET"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">client<span class="token punctuation">.</span><span class="token function">Track</span><span class="token punctuation">(</span>context<span class="token punctuation">.</span><span class="token function">Background</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> analytics<span class="token punctuation">.</span>Event<span class="token punctuation">{</span></span>
<span class="line">  Name<span class="token punctuation">:</span> <span class="token string">"session.start"</span><span class="token punctuation">,</span></span>
<span class="line">  Ts<span class="token punctuation">:</span>   time<span class="token punctuation">.</span><span class="token function">Now</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  Attrs<span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span>any<span class="token punctuation">{</span><span class="token string">"uid"</span><span class="token punctuation">:</span> <span class="token string">"u1"</span><span class="token punctuation">,</span> <span class="token string">"game_id"</span><span class="token punctuation">:</span> <span class="token string">"demo"</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>C#（Unity 快速接入，示意）</p>
<div class="language-csharp line-numbers-mode" data-highlighter="prismjs" data-ext="cs"><pre v-pre><code class="language-csharp"><span class="line"><span class="token class-name"><span class="token keyword">var</span></span> c <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token constructor-invocation class-name">AnalyticsClient</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token constructor-invocation class-name">Config</span> <span class="token punctuation">{</span></span>
<span class="line">  Endpoint <span class="token operator">=</span> <span class="token string">"https://ingest.example.com"</span><span class="token punctuation">,</span></span>
<span class="line">  Secret <span class="token operator">=</span> Env<span class="token punctuation">.</span><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"ANALYTICS_SECRET"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">c<span class="token punctuation">.</span><span class="token function">Track</span><span class="token punctuation">(</span><span class="token string">"session.start"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token punctuation">{</span> uid <span class="token operator">=</span> <span class="token string">"u1"</span><span class="token punctuation">,</span> game_id <span class="token operator">=</span> <span class="token string">"demo"</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>JavaScript（Node/浏览器）</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code class="language-javascript"><span class="line"><span class="token comment">// 计算签名：Base64(HMAC_SHA256(secret, `${ts}\n${nonce}\n${sha256(body)}`))</span></span>
<span class="line"><span class="token keyword">import</span> crypto <span class="token keyword">from</span> <span class="token string">'node:crypto'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> endpoint <span class="token operator">=</span> <span class="token string">'https://ingest.example.com/api/ingest/events'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> secret <span class="token operator">=</span> process<span class="token punctuation">.</span>env<span class="token punctuation">.</span><span class="token constant">ANALYTICS_SECRET</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> body <span class="token operator">=</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">{</span> <span class="token literal-property property">event</span><span class="token operator">:</span> <span class="token string">'session.start'</span><span class="token punctuation">,</span> <span class="token literal-property property">ts</span><span class="token operator">:</span> Date<span class="token punctuation">.</span><span class="token function">now</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token literal-property property">attrs</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">uid</span><span class="token operator">:</span> <span class="token string">'u1'</span><span class="token punctuation">,</span> <span class="token literal-property property">game_id</span><span class="token operator">:</span> <span class="token string">'demo'</span> <span class="token punctuation">}</span> <span class="token punctuation">}</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> ts <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>Date<span class="token punctuation">.</span><span class="token function">now</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> nonce <span class="token operator">=</span> crypto<span class="token punctuation">.</span><span class="token function">randomBytes</span><span class="token punctuation">(</span><span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token string">'hex'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> bodySha <span class="token operator">=</span> crypto<span class="token punctuation">.</span><span class="token function">createHash</span><span class="token punctuation">(</span><span class="token string">'sha256'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span>body<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">digest</span><span class="token punctuation">(</span><span class="token string">'hex'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> sig <span class="token operator">=</span> crypto<span class="token punctuation">.</span><span class="token function">createHmac</span><span class="token punctuation">(</span><span class="token string">'sha256'</span><span class="token punctuation">,</span> secret<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ts<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>nonce<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>bodySha<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">digest</span><span class="token punctuation">(</span><span class="token string">'base64'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">await</span> <span class="token function">fetch</span><span class="token punctuation">(</span>endpoint<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">'POST'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token string-property property">'Content-Type'</span><span class="token operator">:</span> <span class="token string">'application/json'</span><span class="token punctuation">,</span> <span class="token string-property property">'X-Timestamp'</span><span class="token operator">:</span> ts<span class="token punctuation">,</span> <span class="token string-property property">'X-Nonce'</span><span class="token operator">:</span> nonce<span class="token punctuation">,</span> <span class="token string-property property">'X-Signature'</span><span class="token operator">:</span> sig <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  body</span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>说明</p>
<ul>
<li>SDK 做签名、重试、批量；服务端做去重、防重放、鉴权与限流</li>
<li>服务端 Traces/Metrics 建议使用 OTel SDK，业务事件用 Analytics SDK</li>
</ul>
</div></template>


