// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: platform/v1/platform.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformService_CallPlatform_FullMethodName         = "/croupier.platform.v1.PlatformService/CallPlatform"
	PlatformService_ListPlatforms_FullMethodName        = "/croupier.platform.v1.PlatformService/ListPlatforms"
	PlatformService_ListPlatformMethods_FullMethodName  = "/croupier.platform.v1.PlatformService/ListPlatformMethods"
	PlatformService_ReloadPlatformConfig_FullMethodName = "/croupier.platform.v1.PlatformService/ReloadPlatformConfig"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlatformService provides a unified interface for calling third-party platform APIs.
type PlatformServiceClient interface {
	// CallPlatform invokes a method on a third-party platform.
	// The request and response are JSON encoded bytes.
	CallPlatform(ctx context.Context, in *CallPlatformRequest, opts ...grpc.CallOption) (*CallPlatformResponse, error)
	// ListPlatforms returns all available platforms.
	ListPlatforms(ctx context.Context, in *ListPlatformsRequest, opts ...grpc.CallOption) (*ListPlatformsResponse, error)
	// ListPlatformMethods returns the methods supported by a platform.
	ListPlatformMethods(ctx context.Context, in *ListPlatformMethodsRequest, opts ...grpc.CallOption) (*ListPlatformMethodsResponse, error)
	// ReloadPlatformConfig reloads the platform configuration.
	ReloadPlatformConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadPlatformConfigResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) CallPlatform(ctx context.Context, in *CallPlatformRequest, opts ...grpc.CallOption) (*CallPlatformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallPlatformResponse)
	err := c.cc.Invoke(ctx, PlatformService_CallPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListPlatforms(ctx context.Context, in *ListPlatformsRequest, opts ...grpc.CallOption) (*ListPlatformsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListPlatformMethods(ctx context.Context, in *ListPlatformMethodsRequest, opts ...grpc.CallOption) (*ListPlatformMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformMethodsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListPlatformMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ReloadPlatformConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadPlatformConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadPlatformConfigResponse)
	err := c.cc.Invoke(ctx, PlatformService_ReloadPlatformConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations should embed UnimplementedPlatformServiceServer
// for forward compatibility.
//
// PlatformService provides a unified interface for calling third-party platform APIs.
type PlatformServiceServer interface {
	// CallPlatform invokes a method on a third-party platform.
	// The request and response are JSON encoded bytes.
	CallPlatform(context.Context, *CallPlatformRequest) (*CallPlatformResponse, error)
	// ListPlatforms returns all available platforms.
	ListPlatforms(context.Context, *ListPlatformsRequest) (*ListPlatformsResponse, error)
	// ListPlatformMethods returns the methods supported by a platform.
	ListPlatformMethods(context.Context, *ListPlatformMethodsRequest) (*ListPlatformMethodsResponse, error)
	// ReloadPlatformConfig reloads the platform configuration.
	ReloadPlatformConfig(context.Context, *emptypb.Empty) (*ReloadPlatformConfigResponse, error)
}

// UnimplementedPlatformServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) CallPlatform(context.Context, *CallPlatformRequest) (*CallPlatformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPlatform not implemented")
}
func (UnimplementedPlatformServiceServer) ListPlatforms(context.Context, *ListPlatformsRequest) (*ListPlatformsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlatforms not implemented")
}
func (UnimplementedPlatformServiceServer) ListPlatformMethods(context.Context, *ListPlatformMethodsRequest) (*ListPlatformMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlatformMethods not implemented")
}
func (UnimplementedPlatformServiceServer) ReloadPlatformConfig(context.Context, *emptypb.Empty) (*ReloadPlatformConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPlatformConfig not implemented")
}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue() {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_CallPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CallPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CallPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CallPlatform(ctx, req.(*CallPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListPlatforms(ctx, req.(*ListPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListPlatformMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListPlatformMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListPlatformMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListPlatformMethods(ctx, req.(*ListPlatformMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ReloadPlatformConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ReloadPlatformConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ReloadPlatformConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ReloadPlatformConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.platform.v1.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallPlatform",
			Handler:    _PlatformService_CallPlatform_Handler,
		},
		{
			MethodName: "ListPlatforms",
			Handler:    _PlatformService_ListPlatforms_Handler,
		},
		{
			MethodName: "ListPlatformMethods",
			Handler:    _PlatformService_ListPlatformMethods_Handler,
		},
		{
			MethodName: "ReloadPlatformConfig",
			Handler:    _PlatformService_ReloadPlatformConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/v1/platform.proto",
}
