// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: platform/v1/platform.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallPlatformRequest represents a request to call a platform method.
type CallPlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // Platform name (e.g., "quicksdk")
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`     // Method name (e.g., "day_report")
	Request       []byte                 `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`   // Request parameters (JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPlatformRequest) Reset() {
	*x = CallPlatformRequest{}
	mi := &file_platform_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPlatformRequest) ProtoMessage() {}

func (x *CallPlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPlatformRequest.ProtoReflect.Descriptor instead.
func (*CallPlatformRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

func (x *CallPlatformRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CallPlatformRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallPlatformRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

// CallPlatformResponse represents the response from a platform method call.
type CallPlatformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // Response data (JSON)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`       // Error message if the call failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPlatformResponse) Reset() {
	*x = CallPlatformResponse{}
	mi := &file_platform_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPlatformResponse) ProtoMessage() {}

func (x *CallPlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPlatformResponse.ProtoReflect.Descriptor instead.
func (*CallPlatformResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{1}
}

func (x *CallPlatformResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CallPlatformResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListPlatformsRequest represents a request to list platforms.
type ListPlatformsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformsRequest) Reset() {
	*x = ListPlatformsRequest{}
	mi := &file_platform_v1_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformsRequest) ProtoMessage() {}

func (x *ListPlatformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformsRequest.ProtoReflect.Descriptor instead.
func (*ListPlatformsRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{2}
}

// PlatformInfo represents information about a platform.
type PlatformInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`        // Platform name
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"` // Whether the platform is enabled
	Methods       []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`  // Supported methods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformInfo) Reset() {
	*x = PlatformInfo{}
	mi := &file_platform_v1_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInfo) ProtoMessage() {}

func (x *PlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformInfo.ProtoReflect.Descriptor instead.
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{3}
}

func (x *PlatformInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlatformInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PlatformInfo) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

// ListPlatformsResponse represents the response with platform list.
type ListPlatformsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platforms     []*PlatformInfo        `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformsResponse) Reset() {
	*x = ListPlatformsResponse{}
	mi := &file_platform_v1_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformsResponse) ProtoMessage() {}

func (x *ListPlatformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformsResponse.ProtoReflect.Descriptor instead.
func (*ListPlatformsResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlatformsResponse) GetPlatforms() []*PlatformInfo {
	if x != nil {
		return x.Platforms
	}
	return nil
}

// ListPlatformMethodsRequest represents a request to list platform methods.
type ListPlatformMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // Platform name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformMethodsRequest) Reset() {
	*x = ListPlatformMethodsRequest{}
	mi := &file_platform_v1_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformMethodsRequest) ProtoMessage() {}

func (x *ListPlatformMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListPlatformMethodsRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlatformMethodsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// ListPlatformMethodsResponse represents the response with method list.
type ListPlatformMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []string               `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformMethodsResponse) Reset() {
	*x = ListPlatformMethodsResponse{}
	mi := &file_platform_v1_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformMethodsResponse) ProtoMessage() {}

func (x *ListPlatformMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListPlatformMethodsResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{6}
}

func (x *ListPlatformMethodsResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

// ReloadPlatformConfigResponse represents the response after reloading config.
type ReloadPlatformConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPlatformConfigResponse) Reset() {
	*x = ReloadPlatformConfigResponse{}
	mi := &file_platform_v1_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPlatformConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPlatformConfigResponse) ProtoMessage() {}

func (x *ReloadPlatformConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPlatformConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadPlatformConfigResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_platform_proto_rawDescGZIP(), []int{7}
}

func (x *ReloadPlatformConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadPlatformConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_platform_v1_platform_proto protoreflect.FileDescriptor

const file_platform_v1_platform_proto_rawDesc = "" +
	"\n" +
	"\x1aplatform/v1/platform.proto\x12\x14croupier.platform.v1\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x13CallPlatformRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\arequest\x18\x03 \x01(\fR\arequest\"H\n" +
	"\x14CallPlatformResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x16\n" +
	"\x14ListPlatformsRequest\"V\n" +
	"\fPlatformInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\"Y\n" +
	"\x15ListPlatformsResponse\x12@\n" +
	"\tplatforms\x18\x01 \x03(\v2\".croupier.platform.v1.PlatformInfoR\tplatforms\"8\n" +
	"\x1aListPlatformMethodsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"7\n" +
	"\x1bListPlatformMethodsResponse\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\"R\n" +
	"\x1cReloadPlatformConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc2\x03\n" +
	"\x0fPlatformService\x12e\n" +
	"\fCallPlatform\x12).croupier.platform.v1.CallPlatformRequest\x1a*.croupier.platform.v1.CallPlatformResponse\x12h\n" +
	"\rListPlatforms\x12*.croupier.platform.v1.ListPlatformsRequest\x1a+.croupier.platform.v1.ListPlatformsResponse\x12z\n" +
	"\x13ListPlatformMethods\x120.croupier.platform.v1.ListPlatformMethodsRequest\x1a1.croupier.platform.v1.ListPlatformMethodsResponse\x12b\n" +
	"\x14ReloadPlatformConfig\x12\x16.google.protobuf.Empty\x1a2.croupier.platform.v1.ReloadPlatformConfigResponseB\xd7\x01\n" +
	"\x18com.croupier.platform.v1B\rPlatformProtoP\x01Z:github.com/cuihairu/croupier/pkg/pb/platform/v1;platformv1\xa2\x02\x03CPX\xaa\x02\x14Croupier.Platform.V1\xca\x02\x14Croupier\\Platform\\V1\xe2\x02 Croupier\\Platform\\V1\\GPBMetadata\xea\x02\x16Croupier::Platform::V1b\x06proto3"

var (
	file_platform_v1_platform_proto_rawDescOnce sync.Once
	file_platform_v1_platform_proto_rawDescData []byte
)

func file_platform_v1_platform_proto_rawDescGZIP() []byte {
	file_platform_v1_platform_proto_rawDescOnce.Do(func() {
		file_platform_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_platform_proto_rawDesc), len(file_platform_v1_platform_proto_rawDesc)))
	})
	return file_platform_v1_platform_proto_rawDescData
}

var file_platform_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_platform_v1_platform_proto_goTypes = []any{
	(*CallPlatformRequest)(nil),          // 0: croupier.platform.v1.CallPlatformRequest
	(*CallPlatformResponse)(nil),         // 1: croupier.platform.v1.CallPlatformResponse
	(*ListPlatformsRequest)(nil),         // 2: croupier.platform.v1.ListPlatformsRequest
	(*PlatformInfo)(nil),                 // 3: croupier.platform.v1.PlatformInfo
	(*ListPlatformsResponse)(nil),        // 4: croupier.platform.v1.ListPlatformsResponse
	(*ListPlatformMethodsRequest)(nil),   // 5: croupier.platform.v1.ListPlatformMethodsRequest
	(*ListPlatformMethodsResponse)(nil),  // 6: croupier.platform.v1.ListPlatformMethodsResponse
	(*ReloadPlatformConfigResponse)(nil), // 7: croupier.platform.v1.ReloadPlatformConfigResponse
	(*emptypb.Empty)(nil),                // 8: google.protobuf.Empty
}
var file_platform_v1_platform_proto_depIdxs = []int32{
	3, // 0: croupier.platform.v1.ListPlatformsResponse.platforms:type_name -> croupier.platform.v1.PlatformInfo
	0, // 1: croupier.platform.v1.PlatformService.CallPlatform:input_type -> croupier.platform.v1.CallPlatformRequest
	2, // 2: croupier.platform.v1.PlatformService.ListPlatforms:input_type -> croupier.platform.v1.ListPlatformsRequest
	5, // 3: croupier.platform.v1.PlatformService.ListPlatformMethods:input_type -> croupier.platform.v1.ListPlatformMethodsRequest
	8, // 4: croupier.platform.v1.PlatformService.ReloadPlatformConfig:input_type -> google.protobuf.Empty
	1, // 5: croupier.platform.v1.PlatformService.CallPlatform:output_type -> croupier.platform.v1.CallPlatformResponse
	4, // 6: croupier.platform.v1.PlatformService.ListPlatforms:output_type -> croupier.platform.v1.ListPlatformsResponse
	6, // 7: croupier.platform.v1.PlatformService.ListPlatformMethods:output_type -> croupier.platform.v1.ListPlatformMethodsResponse
	7, // 8: croupier.platform.v1.PlatformService.ReloadPlatformConfig:output_type -> croupier.platform.v1.ReloadPlatformConfigResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platform_v1_platform_proto_init() }
func file_platform_v1_platform_proto_init() {
	if File_platform_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_platform_proto_rawDesc), len(file_platform_v1_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_v1_platform_proto_goTypes,
		DependencyIndexes: file_platform_v1_platform_proto_depIdxs,
		MessageInfos:      file_platform_v1_platform_proto_msgTypes,
	}.Build()
	File_platform_v1_platform_proto = out.File
	file_platform_v1_platform_proto_goTypes = nil
	file_platform_v1_platform_proto_depIdxs = nil
}
