package otp

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"net/url"
	"strings"
)

// DefaultIssuer is the `issuer` written into otpauth:// URIs. Authenticator
// apps use it to group entries, and Google Authenticator refuses to import an
// entry whose label prefix and issuer parameter disagree.
const DefaultIssuer = "Croupier"

// AlgorithmSHA1 is the only HMAC algorithm RFC 6238 apps are required to
// support, and the one every mainstream authenticator defaults to. Kept
// explicit in the URI so the scanned entry is unambiguous.
const AlgorithmSHA1 = "SHA1"

// OtpauthURI builds a spec-compliant `otpauth://totp/...` provisioning URI.
//
// The label MUST be `Issuer:account` (percent-encoded), and `issuer` MUST also
// appear as a query parameter — Google Authenticator validates that they match
// and silently drops entries that disagree. `algorithm`, `digits` and `period`
// are emitted explicitly rather than relying on receiver defaults.
//
// The previous hand-rolled form was
//
//	otpauth://totp/Croupier:%s?secret=%s&issuer=Croupier
//
// which did not escape the account part at all: a username containing '@', '/'
// or non-ASCII would produce a URI that authenticator apps parse incorrectly
// (or not at all). See docs/BUGS.md BUG-013.
func OtpauthURI(issuer, account, secret string) (string, error) {
	issuer = strings.TrimSpace(issuer)
	account = strings.TrimSpace(account)
	if issuer == "" {
		issuer = DefaultIssuer
	}
	if account == "" {
		return "", fmt.Errorf("otpauth: 账号名不能为空")
	}
	secret = strings.TrimSpace(secret)
	if secret == "" {
		return "", fmt.Errorf("otpauth: 密钥不能为空")
	}
	// 规范要求 label 为 "Issuer:account"，整体做 percent-encoding。
	label := url.PathEscape(issuer + ":" + account)

	q := url.Values{}
	q.Set("secret", secret)
	q.Set("issuer", issuer)
	q.Set("algorithm", AlgorithmSHA1)
	q.Set("digits", fmt.Sprintf("%d", Digits))
	q.Set("period", fmt.Sprintf("%d", Period))

	return fmt.Sprintf("otpauth://totp/%s?%s", label, q.Encode()), nil
}

// ---------------------------------------------------------------------------
// 备用恢复码（recovery codes）
// ---------------------------------------------------------------------------

const (
	// RecoveryCodeCount is how many codes are issued per enrollment.
	RecoveryCodeCount = 10
	// RecoveryCodeLength is the character count of one code.
	RecoveryCodeLength = 10
)

// recoveryAlphabet 刻意去掉容易混淆的 0/O、1/I/l，方便用户手抄与口述。
const recoveryAlphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"

var recoveryRandRead = rand.Read

// GenerateRecoveryCodes issues RecoveryCodeCount one-time recovery codes.
//
// 每码 RecoveryCodeLength 位，取自 30 字符字母表（约 49.5 bit 熵）。对随机
// 生成的高熵短码用 SHA-256 存储即可抗离线爆破（对比：用户自设密码需要 bcrypt
// 这类慢哈希，正因为其熵低、可被字典枚举）。
func GenerateRecoveryCodes() ([]string, error) {
	codes := make([]string, 0, RecoveryCodeCount)
	for i := 0; i < RecoveryCodeCount; i++ {
		buf := make([]byte, RecoveryCodeLength)
		if _, err := recoveryRandRead(buf); err != nil {
			return nil, err
		}
		code := make([]byte, RecoveryCodeLength)
		for j, b := range buf {
			code[j] = recoveryAlphabet[int(b)%len(recoveryAlphabet)]
		}
		codes = append(codes, string(code))
	}
	return codes, nil
}

// HashRecoveryCode returns the storage form of a recovery code.
//
// 归一化规则与呈现一致：去空白、转大写。用户在 UI 上按 4 位一组抄写或粘贴时
// 常带空格/换行，不归一会导致「明明对却提示无效」。
func HashRecoveryCode(code string) string {
	normalized := strings.ToUpper(strings.Map(func(r rune) rune {
		if r == ' ' || r == '\t' || r == '\n' || r == '\r' || r == '-' {
			return -1
		}
		return r
	}, code))
	sum := sha256.Sum256([]byte(normalized))
	return hex.EncodeToString(sum[:])
}

// NormalizeRecoveryCode exposes the normalization used before hashing, so the
// service can detect (and reject) codes that were not generated by us.
func NormalizeRecoveryCode(code string) string {
	return strings.ToUpper(strings.Map(func(r rune) rune {
		if r == ' ' || r == '\t' || r == '\n' || r == '\r' || r == '-' {
			return -1
		}
		return r
	}, code))
}

// RecoveryCodeMatches compares a presented code against a stored hash in
// constant time.
func RecoveryCodeMatches(presented, storedHash string) bool {
	if storedHash == "" {
		return false
	}
	want, err := hex.DecodeString(storedHash)
	if err != nil {
		return false
	}
	got := HashRecoveryCode(presented)
	gotBytes, err := hex.DecodeString(got)
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare(want, gotBytes) == 1
}

// IsWellFormedRecoveryCode reports whether a normalized code has the expected
// length and alphabet. Used to reject junk before touching the database.
func IsWellFormedRecoveryCode(code string) bool {
	normalized := NormalizeRecoveryCode(code)
	if len([]rune(normalized)) != RecoveryCodeLength {
		return false
	}
	for _, r := range normalized {
		if !strings.ContainsRune(recoveryAlphabet, r) {
			return false
		}
	}
	return true
}
