// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	agent "github.com/cuihairu/croupier/services/agent/internal/handler/agent"
	"github.com/cuihairu/croupier/services/agent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/agent/:agent_id/health",
				Handler: agent.AgentHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/agent/:agent_id/metrics",
				Handler: agent.AgentMetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/agent/heartbeat",
				Handler: agent.AgentHeartbeatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/agent/register",
				Handler: agent.AgentRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/function/register",
				Handler: agent.FunctionRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/job/:job_id/status",
				Handler: agent.JobStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/job/execute",
				Handler: agent.JobExecuteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
