/**
 * 运行控制台动态菜单图标的运行期解析：PageSpec.Icon 存的是图标名字符串
 * （契约值），而 ProLayout MenuDataItem.icon 需要 ReactNode。静态路由的
 * icon 由 umi 构建期解析，运行期注入的字符串必须经这里的映射器转换。
 *
 * 清单覆盖页面编辑器（IconPicker）提供的全部候选图标；未知名兜底
 * AppstoreOutlined，保证菜单永远可渲染。
 */
import React from 'react';
import {
  AppstoreOutlined,
  BarChartOutlined,
  BellOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  ControlOutlined,
  CustomerServiceOutlined,
  DatabaseOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FilterOutlined,
  FireOutlined,
  FormOutlined,
  FunctionOutlined,
  FundOutlined,
  GiftOutlined,
  GlobalOutlined,
  HeartOutlined,
  HomeOutlined,
  LayoutOutlined,
  MailOutlined,
  MoneyCollectOutlined,
  OrderedListOutlined,
  PayCircleOutlined,
  PieChartOutlined,
  ProfileOutlined,
  RocketOutlined,
  SafetyOutlined,
  SettingOutlined,
  ShopOutlined,
  StarOutlined,
  TableOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UserOutlined,
} from '@ant-design/icons';

export const MENU_ICON_NAMES = [
  'AppstoreOutlined',
  'BarChartOutlined',
  'BellOutlined',
  'CloudUploadOutlined',
  'ClusterOutlined',
  'ControlOutlined',
  'CustomerServiceOutlined',
  'DatabaseOutlined',
  'FileSearchOutlined',
  'FileTextOutlined',
  'FilterOutlined',
  'FireOutlined',
  'FormOutlined',
  'FunctionOutlined',
  'FundOutlined',
  'GiftOutlined',
  'GlobalOutlined',
  'HeartOutlined',
  'HomeOutlined',
  'LayoutOutlined',
  'MailOutlined',
  'MoneyCollectOutlined',
  'OrderedListOutlined',
  'PayCircleOutlined',
  'PieChartOutlined',
  'ProfileOutlined',
  'RocketOutlined',
  'SafetyOutlined',
  'SettingOutlined',
  'ShopOutlined',
  'StarOutlined',
  'TableOutlined',
  'TeamOutlined',
  'ThunderboltOutlined',
  'ToolOutlined',
  'TrophyOutlined',
  'UserOutlined',
] as const;

export type MenuIconName = (typeof MENU_ICON_NAMES)[number];

const ICON_MAP: Record<string, React.ReactNode> = {
  AppstoreOutlined: <AppstoreOutlined />,
  BarChartOutlined: <BarChartOutlined />,
  BellOutlined: <BellOutlined />,
  CloudUploadOutlined: <CloudUploadOutlined />,
  ClusterOutlined: <ClusterOutlined />,
  ControlOutlined: <ControlOutlined />,
  CustomerServiceOutlined: <CustomerServiceOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  FileSearchOutlined: <FileSearchOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  FilterOutlined: <FilterOutlined />,
  FireOutlined: <FireOutlined />,
  FormOutlined: <FormOutlined />,
  FunctionOutlined: <FunctionOutlined />,
  FundOutlined: <FundOutlined />,
  GiftOutlined: <GiftOutlined />,
  GlobalOutlined: <GlobalOutlined />,
  HeartOutlined: <HeartOutlined />,
  HomeOutlined: <HomeOutlined />,
  LayoutOutlined: <LayoutOutlined />,
  MailOutlined: <MailOutlined />,
  MoneyCollectOutlined: <MoneyCollectOutlined />,
  OrderedListOutlined: <OrderedListOutlined />,
  PayCircleOutlined: <PayCircleOutlined />,
  PieChartOutlined: <PieChartOutlined />,
  ProfileOutlined: <ProfileOutlined />,
  RocketOutlined: <RocketOutlined />,
  SafetyOutlined: <SafetyOutlined />,
  SettingOutlined: <SettingOutlined />,
  ShopOutlined: <ShopOutlined />,
  StarOutlined: <StarOutlined />,
  TableOutlined: <TableOutlined />,
  TeamOutlined: <TeamOutlined />,
  ThunderboltOutlined: <ThunderboltOutlined />,
  ToolOutlined: <ToolOutlined />,
  TrophyOutlined: <TrophyOutlined />,
  UserOutlined: <UserOutlined />,
};

/** 图标名 → ReactNode；未知名返回 undefined（由调用方决定兜底）。 */
export function resolveMenuIcon(
  name: string | undefined | null,
  fallback: React.ReactNode = <AppstoreOutlined />,
): React.ReactNode | undefined {
  if (!name || typeof name !== 'string') return undefined;
  return ICON_MAP[name] ?? fallback;
}
