// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Migrated to Gin: Phase 4 (All modules)

package handler

import (
	admin "github.com/cuihairu/croupier/services/server/internal/handler/admin"
	adminGames "github.com/cuihairu/croupier/services/server/internal/handler/adminGames"
	agent "github.com/cuihairu/croupier/services/server/internal/handler/agent"
	alert "github.com/cuihairu/croupier/services/server/internal/handler/alert"
	analyticsBehavior "github.com/cuihairu/croupier/services/server/internal/handler/analytics_behavior"
	analyticsOverview "github.com/cuihairu/croupier/services/server/internal/handler/analytics_overview"
	analyticsPayments "github.com/cuihairu/croupier/services/server/internal/handler/analytics_payments"
	analyticsRetention "github.com/cuihairu/croupier/services/server/internal/handler/analytics_retention"
	approval "github.com/cuihairu/croupier/services/server/internal/handler/approval"
	assignment "github.com/cuihairu/croupier/services/server/internal/handler/assignment"
	audit "github.com/cuihairu/croupier/services/server/internal/handler/audit"
	auth "github.com/cuihairu/croupier/services/server/internal/handler/auth"
	backup "github.com/cuihairu/croupier/services/server/internal/handler/backup"
	certificate "github.com/cuihairu/croupier/services/server/internal/handler/certificate"
	component "github.com/cuihairu/croupier/services/server/internal/handler/component"
	config "github.com/cuihairu/croupier/services/server/internal/handler/config"
	entity "github.com/cuihairu/croupier/services/server/internal/handler/entity"
	faq "github.com/cuihairu/croupier/services/server/internal/handler/faq"
	feedback "github.com/cuihairu/croupier/services/server/internal/handler/feedback"
	function "github.com/cuihairu/croupier/services/server/internal/handler/function"
	game "github.com/cuihairu/croupier/services/server/internal/handler/game"
	job "github.com/cuihairu/croupier/services/server/internal/handler/job"
	message "github.com/cuihairu/croupier/services/server/internal/handler/message"
	meta "github.com/cuihairu/croupier/services/server/internal/handler/meta"
	node "github.com/cuihairu/croupier/services/server/internal/handler/node"
	openapi "github.com/cuihairu/croupier/services/server/internal/handler/openapi"
	ops "github.com/cuihairu/croupier/services/server/internal/handler/ops"
	pack "github.com/cuihairu/croupier/services/server/internal/handler/pack"
	platform "github.com/cuihairu/croupier/services/server/internal/handler/platform"
	player "github.com/cuihairu/croupier/services/server/internal/handler/player"
	profile "github.com/cuihairu/croupier/services/server/internal/handler/profile"
	provider "github.com/cuihairu/croupier/services/server/internal/handler/provider"
	rateLimit "github.com/cuihairu/croupier/services/server/internal/handler/rate_limit"
	routes "github.com/cuihairu/croupier/services/server/internal/handler/routes"
	schema "github.com/cuihairu/croupier/services/server/internal/handler/schema"
	storage "github.com/cuihairu/croupier/services/server/internal/handler/storage"
	terms "github.com/cuihairu/croupier/services/server/internal/handler/terms"
	ticket "github.com/cuihairu/croupier/services/server/internal/handler/ticket"
	workspace "github.com/cuihairu/croupier/services/server/internal/handler/workspace"
	"github.com/cuihairu/croupier/services/server/internal/svc"

	"github.com/gin-gonic/gin"
)

func RegisterHandlers(r *gin.Engine, serverCtx *svc.ServiceContext) {
	v1 := r.Group("/api/v1")

	// 公开路由（无认证）
	registerAuthRoutes(v1, serverCtx)
	registerMetaRoutes(v1, serverCtx)
	registerRegistryRoutes(v1.Group("/registry"), serverCtx) // 公开访问
	registerAuditRoutes(v1, serverCtx)                       // 审计日志在 v1 根路径
	registerOpenAPIRoutes(v1, serverCtx)                     // OpenAPI 在 v1 根路径

	// 需要认证的路由（使用 Authority 中间件）
	protected := v1.Group("/")
	protected.Use(serverCtx.Authority)
	{
		registerAdminRoutes(protected.Group("/admin"), serverCtx)
		registerRoutesRoutes(protected.Group("/routes"), serverCtx)
		registerFunctionRoutes(protected.Group("/functions"), serverCtx)
		registerGameRoutes(protected.Group("/games"), serverCtx)
		registerJobRoutes(protected.Group("/jobs"), serverCtx)
		registerNodeRoutes(protected.Group("/nodes"), serverCtx)
		registerOpsRoutes(protected.Group("/ops"), serverCtx)
		registerStorageRoutes(protected.Group("/storage"), serverCtx)

		// 剩余模块路由
		registerAgentRoutes(protected.Group("/agent"), serverCtx)
		registerAlertRoutes(protected.Group("/alerts"), serverCtx)
		registerAnalyticsRoutes(protected.Group("/analytics"), serverCtx)
		registerApprovalRoutes(protected.Group("/approvals"), serverCtx)
		registerAssignmentRoutes(protected.Group("/assignments"), serverCtx)
		registerBackupRoutes(protected.Group("/backups"), serverCtx)
		registerCertificateRoutes(protected.Group("/certificates"), serverCtx)
		registerComponentRoutes(protected.Group("/components"), serverCtx)
		registerConfigRoutes(protected.Group("/configs"), serverCtx)
		registerEntityRoutes(protected.Group("/entities"), serverCtx)
		registerFAQRoutes(protected.Group("/faqs"), serverCtx)
		registerFeedbackRoutes(protected.Group("/feedback"), serverCtx)
		registerMessageRoutes(protected.Group("/messages"), serverCtx)
		registerPackRoutes(protected.Group("/packs"), serverCtx)
		registerPlatformRoutes(protected.Group("/platforms"), serverCtx)
		registerPlayerRoutes(protected.Group("/players"), serverCtx)
		registerProfileRoutes(protected.Group("/profile"), serverCtx)
		registerProviderRoutes(protected.Group("/providers"), serverCtx)
		registerRateLimitRoutes(protected.Group("/rate-limits"), serverCtx)
		registerSchemaRoutes(protected.Group("/schemas"), serverCtx)
		registerTermsRoutes(protected.Group("/terms"), serverCtx)
		registerTicketRoutes(protected.Group("/tickets"), serverCtx)
		registerWorkspaceRoutes(protected.Group("/workspaces"), serverCtx)
	}
}

func registerAuthRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.POST("/login", auth.LoginHandler(ctx))
	g.POST("/logout", auth.LogoutHandler(ctx))
}

func registerMetaRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", meta.RootHandler(ctx))
}

func registerAdminRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", admin.AdminsListHandler(ctx))
	g.POST("/", admin.AdminCreateHandler(ctx))
	g.GET("/:id", admin.AdminDetailHandler(ctx))
	g.PUT("/:id", admin.AdminUpdateHandler(ctx))
	g.DELETE("/:id", admin.AdminDeleteHandler(ctx))
	g.POST("/:id/password-reset", admin.AdminPasswordResetHandler(ctx))
	g.GET("/:id/games", adminGames.AdminGamesHandler(ctx))
	g.PUT("/:id/games", adminGames.AdminGamesUpdateHandler(ctx))
}

func registerRoutesRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", routes.GetRoutesHandler(ctx))
}

// ============================================================================
// Function 路由注册
// ============================================================================
func registerFunctionRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	// 基础 CRUD
	g.GET("/", function.FunctionsListHandler(ctx))
	g.GET("/:id", function.FunctionDetailHandler(ctx))
	g.DELETE("/:id", function.FunctionDeleteHandler(ctx))

	// 函数操作
	g.POST("/:id/enable", function.FunctionEnableHandler(ctx))
	g.POST("/:id/disable", function.FunctionDisableHandler(ctx))
	g.POST("/:id/copy", function.FunctionCopyHandler(ctx))
	g.POST("/:id/invoke", function.FunctionInvokeHandler(ctx))
	g.POST("/:id/publish", function.FunctionPublishHandler(ctx))

	// 函数实例
	g.GET("/:id/instances", function.FunctionInstancesHandler(ctx))
	g.GET("/instances", function.FunctionInstancesAllHandler(ctx))

	// 权限管理
	g.GET("/:id/permissions", function.FunctionPermissionsHandler(ctx))
	g.PUT("/:id/permissions", function.FunctionPermissionsUpdateHandler(ctx))

	// UI 配置
	g.GET("/:id/ui", function.FunctionUIHandler(ctx))
	g.PUT("/:id/ui", function.FunctionUIUpdateHandler(ctx))
	g.GET("/:id/ui/history", function.FunctionUIHistoryHandler(ctx))
	g.POST("/:id/ui/rollback", function.FunctionUIRollbackHandler(ctx))

	// 路由配置
	g.GET("/:id/route", function.FunctionRouteHandler(ctx))
	g.PUT("/:id/route", function.FunctionRouteUpdateHandler(ctx))

	// 历史与分析
	g.GET("/:id/history", function.FunctionHistoryHandler(ctx))
	g.GET("/:id/analytics", function.FunctionAnalyticsHandler(ctx))

	// 描述符
	g.GET("/descriptors", function.DescriptorsHandler(ctx))

	// 待处理
	g.GET("/pending", function.FunctionsPendingHandler(ctx))

	// 批量操作
	g.POST("/batch-update", function.BatchUpdateFunctionsHandler(ctx))
	g.POST("/batch-copy", function.BatchCopyFunctionsHandler(ctx))
	g.POST("/batch-delete", function.BatchDeleteFunctionsHandler(ctx))
	g.GET("/warnings", function.FunctionWarningsHandler(ctx))
}

// ============================================================================
// Game 路由注册
// ============================================================================
func registerGameRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	// 基础 CRUD
	g.GET("/", game.GamesListHandler(ctx))
	g.POST("/", game.GameCreateHandler(ctx))
	g.GET("/:id", game.GameDetailHandler(ctx))
	g.PUT("/:id", game.GameUpdateHandler(ctx))
	g.DELETE("/:id", game.GameDeleteHandler(ctx))

	// 环境管理
	g.GET("/:id/envs", game.GameEnvsListHandler(ctx))
	g.POST("/:id/envs", game.GameEnvAddHandler(ctx))
	g.PUT("/:id/envs/:envId", game.GameEnvUpdateHandler(ctx))
	g.DELETE("/:id/envs/:envId", game.GameEnvDeleteHandler(ctx))
}

// ============================================================================
// Job 路由注册
// ============================================================================
func registerJobRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", job.JobListHandler(ctx))
	g.POST("/", job.JobStartHandler(ctx))
	g.POST("/:id/cancel", job.JobCancelHandler(ctx))
	g.GET("/:id/result", job.JobResultHandler(ctx))
	g.GET("/:jobId/stream", job.StreamJobHandler(ctx))
}

// ============================================================================
// Node 路由注册
// ============================================================================
func registerNodeRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", node.NodesListHandler(ctx))
	g.GET("/:id/meta", node.NodeMetaHandler(ctx))
	g.PUT("/:id/meta", node.NodeMetaUpdateHandler(ctx))
	g.POST("/:id/drain", node.NodeDrainHandler(ctx))
	g.POST("/:id/undrain", node.NodeUndrainHandler(ctx))
	g.POST("/:id/restart", node.NodeRestartHandler(ctx))
	g.GET("/commands", node.NodeCommandsHandler(ctx))
}

// ============================================================================
// Ops 路由注册
// ============================================================================
func registerOpsRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	// Agent Ops
	g.GET("/agents", ops.OpsAgentsListHandler(ctx))
	g.GET("/agents/metrics", ops.OpsAgentMetricsHandler(ctx))
	g.GET("/agents/:agentId/system-info", ops.OpsAgentSystemInfoHandler(ctx))
	g.GET("/agents/:agentId/processes", ops.OpsAgentProcessesHandler(ctx))
	g.POST("/agents/:agentId/processes/:name/restart", ops.OpsAgentProcessRestartHandler(ctx))
	g.POST("/agents/:agentId/processes/:name/stop", ops.OpsAgentProcessStopHandler(ctx))
	g.POST("/agents/:agentId/processes/:name/start", ops.OpsAgentProcessStartHandler(ctx))
	g.POST("/agents/:agentId/exec", ops.OpsAgentExecCommandHandler(ctx))

	// 核心 Ops
	g.PUT("/agent-meta", ops.OpsAgentMetaHandler(ctx))
	g.GET("/alerts", ops.OpsAlertsHandler(ctx))
	g.POST("/alerts/silence", ops.OpsAlertSilenceHandler(ctx))
	g.DELETE("/silences/:id", ops.OpsSilenceDeleteHandler(ctx))
	g.GET("/silences", ops.OpsSilencesHandler(ctx))

	// 备份
	g.POST("/backups", ops.OpsBackupCreateHandler(ctx))
	g.GET("/backups", ops.OpsBackupsListHandler(ctx))
	g.DELETE("/backups/:id", ops.OpsBackupDeleteHandler(ctx))
	g.GET("/backups/:id/download", ops.OpsBackupDownloadHandler(ctx))

	// 配置与状态
	g.GET("/config", ops.OpsConfigHandler(ctx))
	g.GET("/functions", ops.OpsFunctionsHandler(ctx))
	g.GET("/health", ops.OpsHealthGetHandler(ctx))
	g.POST("/health/run", ops.OpsHealthRunHandler(ctx))
	g.PUT("/health", ops.OpsHealthUpdateHandler(ctx))
	g.GET("/maintenance", ops.OpsMaintenanceGetHandler(ctx))
	g.PUT("/maintenance", ops.OpsMaintenanceUpdateHandler(ctx))
	g.GET("/metrics", ops.OpsMetricsHandler(ctx))
	g.GET("/mq", ops.OpsMQHandler(ctx))
	g.GET("/notifications", ops.OpsNotificationsGetHandler(ctx))
	g.PUT("/notifications", ops.OpsNotificationsUpdateHandler(ctx))
	g.GET("/services", ops.OpsServicesHandler(ctx))

	// 节点 Ops
	g.GET("/nodes", ops.OpsNodesHandler(ctx))
	g.GET("/nodes/commands", ops.OpsNodeCommandsHandler(ctx))
	g.GET("/nodes/:nodeId/meta", ops.OpsNodeMetaHandler(ctx))
	g.POST("/nodes/:nodeId/drain", ops.OpsNodeDrainHandler(ctx))
	g.POST("/nodes/:nodeId/undrain", ops.OpsNodeUndrainHandler(ctx))
	g.POST("/nodes/:nodeId/restart", ops.OpsNodeRestartHandler(ctx))
}

// ============================================================================
// Storage 路由注册
// ============================================================================
func registerStorageRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/signed-url", storage.SignedUrlHandler(ctx))
	g.GET("/objects", storage.ListObjectsHandler(ctx))
	g.POST("/objects", storage.UploadObjectHandler(ctx))
	g.DELETE("/objects", storage.DeleteObjectHandler(ctx))
	g.POST("/objects/batch-delete", storage.BatchDeleteObjectsHandler(ctx))
	g.POST("/directories", storage.CreateDirectoryHandler(ctx))
	g.POST("/directories/rename", storage.RenameDirectoryHandler(ctx))
}

// ============================================================================
// Registry 路由注册（公开访问，无需认证）
// ============================================================================
func registerRegistryRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	// Registry 模块路由暂时为空，通过 NNG 控制 API 处理
	// 预留扩展空间
}

// ============================================================================
// Audit 路由注册（公开访问，在 v1 根路径）
// ============================================================================
func registerAuditRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/audit", audit.AuditHandler(ctx))
}

// ============================================================================
// OpenAPI 路由注册（公开访问，在 v1 根路径）
// ============================================================================
func registerOpenAPIRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/functions/:id/openapi", openapi.FunctionOpenAPISpecHandler(ctx))
	g.POST("/functions/_import", openapi.OpenAPIImportHandler(ctx))
	g.GET("/entities/:id/functions", openapi.EntityFunctionsHandler(ctx))
	g.GET("/openapi/spec", openapi.OpenAPIDocumentHandler(ctx))
}

// ============================================================================
// Agent 路由注册
// ============================================================================
func registerAgentRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/analytics-filters", agent.AgentAnalyticsFiltersHandler(ctx))
	g.POST("/meta", agent.AgentMetaHandler(ctx))
}

// ============================================================================
// Alert 路由注册
// ============================================================================
func registerAlertRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", alert.AlertsListHandler(ctx))
	g.POST("/:id/silence", alert.AlertSilenceHandler(ctx))
	g.GET("/silences", alert.SilencesListHandler(ctx))
	g.DELETE("/silences/:id", alert.SilenceDeleteHandler(ctx))
}

// ============================================================================
// Analytics 路由注册（合并所有 analytics_* 模块）
// ============================================================================
func registerAnalyticsRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	// Overview 模块
	g.GET("/overview", analyticsOverview.OverviewHandler(ctx))
	g.GET("/realtime", analyticsOverview.RealtimeHandler(ctx))
	g.GET("/realtime/series", analyticsOverview.RealtimeSeriesHandler(ctx))
	g.POST("/ingest", analyticsOverview.IngestHandler(ctx))
	g.GET("/filters", analyticsOverview.FiltersGetHandler(ctx))
	g.PUT("/filters", analyticsOverview.FiltersUpdateHandler(ctx))

	// Behavior 模块 - 使用 /behavior 子路径
	behaviorGroup := g.Group("/behavior")
	{
		behaviorGroup.GET("/", analyticsBehavior.BehaviorHandler(ctx))
		behaviorGroup.GET("/events", analyticsBehavior.BehaviorEventsHandler(ctx))
		behaviorGroup.GET("/paths", analyticsBehavior.BehaviorPathsHandler(ctx))
		behaviorGroup.POST("/funnel", analyticsBehavior.BehaviorFunnelHandler(ctx))
		behaviorGroup.GET("/adoption", analyticsBehavior.BehaviorAdoptionHandler(ctx))
		behaviorGroup.GET("/adoption/breakdown", analyticsBehavior.BehaviorAdoptionBreakdownHandler(ctx))
	}

	// Payments 模块 - 使用 /payments 子路径
	paymentsGroup := g.Group("/payments")
	{
		paymentsGroup.GET("/", analyticsPayments.PaymentsHandler(ctx))
		paymentsGroup.GET("/summary", analyticsPayments.PaymentsSummaryHandler(ctx))
		paymentsGroup.GET("/product-trend", analyticsPayments.PaymentsProductTrendHandler(ctx))
		paymentsGroup.GET("/transactions", analyticsPayments.PaymentsTransactionsHandler(ctx))
		paymentsGroup.POST("/ingest", analyticsPayments.PaymentsIngestHandler(ctx))
	}

	// Retention 模块 - 使用 /retention 和 /levels 子路径
	g.GET("/retention", analyticsRetention.RetentionHandler(ctx))
	g.GET("/levels", analyticsRetention.LevelsHandler(ctx))
	g.GET("/levels/episodes", analyticsRetention.LevelsEpisodesHandler(ctx))
	g.GET("/levels/maps", analyticsRetention.LevelsMapsHandler(ctx))
}

// ============================================================================
// Approval 路由注册
// ============================================================================
func registerApprovalRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", approval.ApprovalsListHandler(ctx))
	g.GET("/:id", approval.ApprovalGetHandler(ctx))
	g.POST("/:id/approve", approval.ApprovalApproveHandler(ctx))
	g.POST("/:id/reject", approval.ApprovalRejectHandler(ctx))
}

// ============================================================================
// Assignment 路由注册
// ============================================================================
func registerAssignmentRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", assignment.AssignmentsListHandler(ctx))
	g.GET("/history", assignment.AssignmentsHistoryHandler(ctx))
	g.PUT("/", assignment.AssignmentsUpdateHandler(ctx))
}

// ============================================================================
// Backup 路由注册
// ============================================================================
func registerBackupRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", backup.BackupsListHandler(ctx))
	g.POST("/", backup.BackupCreateHandler(ctx))
	g.DELETE("/:id", backup.BackupDeleteHandler(ctx))
	g.GET("/:id/download", backup.BackupDownloadHandler(ctx))
}

// ============================================================================
// Certificate 路由注册
// ============================================================================
func registerCertificateRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", certificate.CertificatesListHandler(ctx))
	g.POST("/", certificate.CertificateAddHandler(ctx))
	g.GET("/:id", certificate.CertificateDetailHandler(ctx))
	g.POST("/:id/check", certificate.CertificateCheckHandler(ctx))
	g.DELETE("/:id", certificate.CertificateDeleteHandler(ctx))
	g.GET("/stats", certificate.CertificateStatsHandler(ctx))
	g.POST("/alerts", certificate.CertificateAlertAddHandler(ctx))
	g.GET("/alerts", certificate.CertificateAlertsListHandler(ctx))
	g.POST("/check-all", certificate.CertificateCheckAllHandler(ctx))
	g.GET("/domain-info", certificate.CertificateDomainInfoHandler(ctx))
	g.GET("/expiring", certificate.CertificateExpiringHandler(ctx))
}

// ============================================================================
// Component 路由注册
// ============================================================================
func registerComponentRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", component.ComponentsListHandler(ctx))
	g.POST("/install", component.ComponentsInstallHandler(ctx))
	g.GET("/:id", component.ComponentsDetailHandler(ctx))
	g.POST("/:id/enable", component.ComponentsEnableHandler(ctx))
	g.POST("/:id/disable", component.ComponentsDisableHandler(ctx))
	g.DELETE("/:id", component.ComponentsDeleteHandler(ctx))
	g.PATCH("/:id", component.ComponentsPatchHandler(ctx))
}

// ============================================================================
// Config 路由注册
// ============================================================================
func registerConfigRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.POST("/", config.ConfigUpsertHandler(ctx))
	g.GET("/version", config.ConfigVersionDetailHandler(ctx))
	g.GET("/versions", config.ConfigVersionsHandler(ctx))
}

// ============================================================================
// Entity 路由注册
// ============================================================================
func registerEntityRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", entity.EntitiesListHandler(ctx))
	g.POST("/", entity.EntityCreateHandler(ctx))
	g.GET("/:id", entity.EntityDetailHandler(ctx))
	g.PUT("/:id", entity.EntityUpdateHandler(ctx))
	g.DELETE("/:id", entity.EntityDeleteHandler(ctx))
	g.GET("/:id/preview", entity.EntityPreviewHandler(ctx))
	g.POST("/validate", entity.EntityValidateHandler(ctx))
}

// ============================================================================
// FAQ 路由注册
// ============================================================================
func registerFAQRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", faq.FAQListHandler(ctx))
	g.POST("/", faq.FAQCreateHandler(ctx))
	g.PUT("/:id", faq.FAQUpdateHandler(ctx))
	g.DELETE("/:id", faq.FAQDeleteHandler(ctx))
	g.GET("/categories", faq.FAQCategoriesHandler(ctx))
}

// ============================================================================
// Feedback 路由注册
// ============================================================================
func registerFeedbackRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", feedback.FeedbackListHandler(ctx))
	g.POST("/", feedback.FeedbackCreateHandler(ctx))
	g.PUT("/:id", feedback.FeedbackUpdateHandler(ctx))
	g.DELETE("/:id", feedback.FeedbackDeleteHandler(ctx))
	g.GET("/stats", feedback.FeedbackStatsHandler(ctx))
}

// ============================================================================
// Message 路由注册
// ============================================================================
func registerMessageRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", message.MessagesListHandler(ctx))
	g.POST("/", message.MessageSendHandler(ctx))
	g.GET("/:id", message.MessageDetailHandler(ctx))
	g.POST("/:id/read", message.MessageReadHandler(ctx))
	g.GET("/unread-count", message.MessagesUnreadCountHandler(ctx))
	g.GET("/stream", message.StreamMessagesHandler(ctx))
}

// ============================================================================
// Pack 路由注册
// ============================================================================
func registerPackRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/export", pack.PacksExportHandler(ctx))
	g.POST("/import", pack.PacksImportHandler(ctx))
	g.GET("/", pack.PacksListHandler(ctx))
	g.POST("/reload", pack.PacksReloadHandler(ctx))
	g.GET("/plugin", pack.PacksPluginHandler(ctx))
}

// ============================================================================
// Platform 路由注册
// ============================================================================
func registerPlatformRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.POST("/call", platform.CallPlatformHandler(ctx))
	g.GET("/", platform.ListPlatformsHandler(ctx))
	g.GET("/:platform/methods", platform.ListPlatformMethodsHandler(ctx))
	g.POST("/reload", platform.ReloadPlatformConfigHandler(ctx))
}

// ============================================================================
// Player 路由注册
// ============================================================================
func registerPlayerRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", player.PlayersListHandler(ctx))
	g.POST("/", player.PlayerCreateHandler(ctx))
	g.GET("/:id", player.PlayerDetailHandler(ctx))
	g.PUT("/:id", player.PlayerUpdateHandler(ctx))
	g.DELETE("/:id", player.PlayerDeleteHandler(ctx))
	g.POST("/:id/balance", player.PlayerBalanceHandler(ctx))
}

// ============================================================================
// Profile 路由注册
// ============================================================================
func registerProfileRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", profile.ProfileGetHandler(ctx))
	g.PUT("/", profile.ProfileUpdateHandler(ctx))
	g.PUT("/password", profile.ProfilePasswordHandler(ctx))
	g.GET("/permissions", profile.ProfilePermissionsHandler(ctx))
	g.GET("/games", profile.ProfileGamesHandler(ctx))
}

// ============================================================================
// Provider 路由注册
// ============================================================================
func registerProviderRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", provider.ProvidersListHandler(ctx))
	g.GET("/capabilities", provider.ProvidersCapabilitiesHandler(ctx))
	g.GET("/descriptors", provider.ProvidersDescriptorsHandler(ctx))
	g.GET("/:id", provider.ProvidersDetailHandler(ctx))
	g.GET("/:id/entities", provider.ProvidersEntitiesHandler(ctx))
	g.DELETE("/:id", provider.ProvidersDeleteHandler(ctx))
	g.POST("/:id/reload", provider.ProvidersReloadHandler(ctx))
}

// ============================================================================
// RateLimit 路由注册
// ============================================================================
func registerRateLimitRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", rateLimit.RateLimitsListHandler(ctx))
	g.GET("/:id", rateLimit.RateLimitGetHandler(ctx))
	g.PUT("/", rateLimit.RateLimitUpsertHandler(ctx))
	g.DELETE("/:id", rateLimit.RateLimitDeleteHandler(ctx))
	g.POST("/preview", rateLimit.RateLimitPreviewHandler(ctx))
}

// ============================================================================
// Schema 路由注册
// ============================================================================
func registerSchemaRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", schema.SchemasListHandler(ctx))
	g.POST("/", schema.SchemaCreateHandler(ctx))
	g.GET("/:id", schema.SchemaDetailHandler(ctx))
	g.PUT("/:id", schema.SchemaUpdateHandler(ctx))
	g.DELETE("/:id", schema.SchemaDeleteHandler(ctx))
	g.POST("/:id/validate", schema.SchemaValidateHandler(ctx))
	g.POST("/raw-validate", schema.SchemaRawValidateHandler(ctx))
	g.GET("/:id/ui-config", schema.SchemaUiConfigHandler(ctx))
	g.PUT("/:id/ui-config", schema.SchemaUiConfigUpdateHandler(ctx))
}

// ============================================================================
// Terms 路由注册
// ============================================================================
func registerTermsRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", terms.TermsListHandler(ctx))
	g.PUT("/", terms.TermUpsertHandler(ctx))
	g.DELETE("/", terms.TermDeleteHandler(ctx))
}

// ============================================================================
// Ticket 路由注册
// ============================================================================
func registerTicketRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/", ticket.TicketsListHandler(ctx))
	g.POST("/", ticket.TicketCreateHandler(ctx))
	g.GET("/:id", ticket.TicketDetailHandler(ctx))
	g.PUT("/:id", ticket.TicketUpdateHandler(ctx))
	g.DELETE("/:id", ticket.TicketDeleteHandler(ctx))
	g.POST("/:id/transition", ticket.TicketTransitionHandler(ctx))
	g.GET("/:ticketId/comments", ticket.TicketCommentsHandler(ctx))
	g.POST("/:ticketId/comments", ticket.TicketCommentCreateHandler(ctx))
}

// ============================================================================
// Workspace 路由注册
// ============================================================================
func registerWorkspaceRoutes(g *gin.RouterGroup, ctx *svc.ServiceContext) {
	g.GET("/configs", workspace.WorkspaceConfigsListHandler(ctx))
	g.GET("/published", workspace.WorkspacePublishedListHandler(ctx))
	g.GET("/:objectKey/config", workspace.WorkspaceConfigGetHandler(ctx))
	g.PUT("/:objectKey/config", workspace.WorkspaceConfigSaveHandler(ctx))
	g.DELETE("/:objectKey/config", workspace.WorkspaceConfigDeleteHandler(ctx))
	g.POST("/:objectKey/publish", workspace.WorkspacePublishHandler(ctx))
	g.POST("/:objectKey/unpublish", workspace.WorkspaceUnpublishHandler(ctx))
	g.GET("/:objectKey/versions", workspace.WorkspaceVersionsHandler(ctx))
	g.GET("/:objectKey/versions/:versionId", workspace.WorkspaceVersionDetailHandler(ctx))
	g.POST("/:objectKey/rollback", workspace.WorkspaceRollbackHandler(ctx))
}
