// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	openapi "github.com/cuihairu/croupier/services/server/internal/handler/openapi"
	"github.com/cuihairu/croupier/services/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取实体关联的函数列表
				Method:  http.MethodGet,
				Path:    "/entities/:id/functions",
				Handler: openapi.EntityFunctionsHandler(serverCtx),
			},
			{
				// 获取函数的 OpenAPI spec
				Method:  http.MethodGet,
				Path:    "/functions/:id/openapi",
				Handler: openapi.FunctionOpenAPISpecHandler(serverCtx),
			},
			{
				// 导入 OpenAPI spec
				Method:  http.MethodPost,
				Path:    "/functions/_import",
				Handler: openapi.OpenAPIImportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
