import React from 'react';
import { SecurityScanOutlined, SettingOutlined } from '@ant-design/icons';

export interface PermissionDomain {
  domain: string;
  description: string;
  permissions: string[];
  color: string;
  icon: React.ReactNode;
}

// 权限域数据
export const permissionDomains: PermissionDomain[] = [
  {
    domain: 'system',
    description: '系统级操作权限',
    permissions: [
      'system:config',
      'system:restart',
      'system:backup',
      'system:monitor',
      'system:security',
      'system:audit',
    ],
    color: '#ff4d4f',
    icon: <SettingOutlined />,
  },
  {
    domain: 'user',
    description: '用户管理权限',
    permissions: [
      'user:create',
      'user:update',
      'user:delete',
      'user:view',
      'user:developer:manage',
      'user:support:manage',
    ],
    color: '#fa541c',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'game',
    description: '游戏配置管理权限',
    permissions: [
      'game:config',
      'game:deploy',
      'game:restart',
      'game:config:read',
      'game:config:update',
      'game:config:numerical',
    ],
    color: '#fa8c16',
    icon: <SettingOutlined />,
  },
  {
    domain: 'player',
    description: '玩家管理权限',
    permissions: [
      'player:query',
      'player:update',
      'player:ban',
      'player:create:test',
      'player:update:basic',
      'player:export',
      'player:communicate',
      'player:behavior',
      'player:segment',
      'player:bot',
      'player:security',
      'player:audit',
    ],
    color: '#faad14',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'function',
    description: '函数管理权限',
    permissions: [
      'function:register',
      'function:update',
      'function:test',
      'function:view',
      'function:deploy',
    ],
    color: '#1890ff',
    icon: <SettingOutlined />,
  },
  {
    domain: 'job',
    description: '任务管理权限',
    permissions: ['job:create', 'job:view', 'job:cancel', 'job:retry', 'job:create:readonly'],
    color: '#13c2c2',
    icon: <SettingOutlined />,
  },
  {
    domain: 'audit',
    description: '审计查看权限',
    permissions: [
      'audit:view',
      'audit:export',
      'audit:content',
      'audit:support',
      'audit:gm',
      'audit:bot',
      'audit:view:player',
      'audit:view:user',
    ],
    color: '#52c41a',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'monitor',
    description: '监控数据权限',
    permissions: ['monitor:view', 'monitor:alert', 'monitor:bot', 'monitor:security'],
    color: '#722ed1',
    icon: <SettingOutlined />,
  },
  {
    domain: 'data',
    description: '数据分析权限',
    permissions: [
      'data:query',
      'data:export',
      'data:report',
      'data:operation',
      'data:marketing',
      'data:economy',
      'data:balance',
      'data:level',
      'data:user',
      'data:bot',
      'data:audit',
    ],
    color: '#eb2f96',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'design',
    description: '游戏设计/策划权限',
    permissions: [
      'design:level',
      'design:system',
      'design:feature',
      'design:numerical',
      'design:ui',
      'design:view',
      'design:research',
    ],
    color: '#f759ab',
    icon: <SettingOutlined />,
  },
  {
    domain: 'numerical',
    description: '数值配置权限',
    permissions: ['numerical:balance', 'numerical:economy'],
    color: '#ff85c0',
    icon: <SettingOutlined />,
  },
  {
    domain: 'level',
    description: '关卡管理权限',
    permissions: ['level:create', 'level:edit', 'level:publish'],
    color: '#b37feb',
    icon: <SettingOutlined />,
  },
  {
    domain: 'content',
    description: '内容管理权限',
    permissions: [
      'content:create',
      'content:edit',
      'content:publish',
      'content:manage',
      'content:level',
      'content:system',
      'content:ui',
      'content:marketing',
      'content:community',
    ],
    color: '#9254de',
    icon: <SettingOutlined />,
  },
  {
    domain: 'marketing',
    description: '市场营销权限',
    permissions: ['marketing:campaign', 'marketing:analytics'],
    color: '#73d13d',
    icon: <SettingOutlined />,
  },
  {
    domain: 'community',
    description: '社区管理权限',
    permissions: ['community:moderate', 'community:event'],
    color: '#95de64',
    icon: <SettingOutlined />,
  },
  {
    domain: 'event',
    description: '活动管理权限',
    permissions: [
      'event:create',
      'event:config',
      'event:start',
      'event:design',
      'event:marketing',
      'event:content',
      'event:community',
      'event:gm',
    ],
    color: '#5cdbd3',
    icon: <SettingOutlined />,
  },
  {
    domain: 'announcement',
    description: '公告系统权限',
    permissions: [
      'announcement:create',
      'announcement:publish',
      'announcement:marketing',
      'announcement:community',
      'announcement:gm',
    ],
    color: '#69c0ff',
    icon: <SettingOutlined />,
  },
  {
    domain: 'mail',
    description: '邮件系统权限',
    permissions: [
      'mail:send',
      'mail:template',
      'mail:system',
      'mail:support',
      'mail:support:template',
    ],
    color: '#85a5ff',
    icon: <SettingOutlined />,
  },
  {
    domain: 'ban',
    description: '封禁管理权限',
    permissions: ['ban:player', 'ban:temporary', 'ban:permanent'],
    color: '#ffc069',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'reward',
    description: '奖励发放权限',
    permissions: [
      'reward:send',
      'reward:config',
      'reward:compensation',
      'reward:compensation:basic',
    ],
    color: '#ffd666',
    icon: <SettingOutlined />,
  },
  {
    domain: 'gm',
    description: 'GM工具权限',
    permissions: ['gm:teleport', 'gm:spawn', 'gm:modify'],
    color: '#fff566',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'bot',
    description: '机器人/托管理权限',
    permissions: ['bot:create', 'bot:config', 'bot:control'],
    color: '#d3adf7',
    icon: <SettingOutlined />,
  },
  {
    domain: 'security',
    description: '安全管理权限',
    permissions: ['security:monitor', 'security:investigate'],
    color: '#efdbff',
    icon: <SecurityScanOutlined />,
  },
  {
    domain: 'economy',
    description: '游戏经济系统权限',
    permissions: ['economy:balance', 'economy:report', 'economy:analyze'],
    color: '#f9f0ff',
    icon: <SettingOutlined />,
  },
  {
    domain: 'support',
    description: '客服功能权限',
    permissions: ['support:ticket', 'support:chat'],
    color: '#ff7875',
    icon: <SecurityScanOutlined />,
  },
];
