// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package httpserver

import (
    auditchain "github.com/cuihairu/croupier/internal/audit/chain"
    "github.com/cuihairu/croupier/internal/security/rbac"
    jwt "github.com/cuihairu/croupier/internal/security/token"
    "github.com/cuihairu/croupier/internal/connpool"
    // loadbalancer types replaced by local AgentStats in http layer
    repogames "github.com/cuihairu/croupier/internal/repo/gorm/games"
    registry "github.com/cuihairu/croupier/internal/platform/registry"
    gamesvc "github.com/cuihairu/croupier/internal/service/games"
)

// InitServerApp composes *Server with DB, repo, service and external deps.
func InitServerApp(descriptorDir string, invoker FunctionInvoker, audit *auditchain.Writer, policy rbac.PolicyInterface, reg *registry.Store, jwtMgr *jwt.Manager, locator interface{ GetJobAddr(string) (string, bool) }, statsProv interface{ GetStats() map[string]*AgentStats; GetPoolStats() *connpool.PoolStats }) (*Server, error) {
    db, err := ProvideGormDBFromEnv()
    if err != nil {
        return nil, err
    }
    // Migrate games tables best-effort
    _ = repogames.AutoMigrate(db)
    repo := repogames.NewRepo(db)
    portRepo := repogames.NewPortRepo(repo)
    defaults := ProvideGamesDefaults()
    svc := gamesvc.NewService(portRepo, defaults)
    certStore := ProvideCertStore(db)
    objStore, objConf := ProvideObjectStoreFromEnv()
    ch := ProvideClickHouseFromEnv()
    s, err := NewServer(descriptorDir, invoker, audit, policy, reg, jwtMgr, locator, statsProv)
    if err != nil {
        return nil, err
    }
    s.gdb = db
    s.games = repo
    s.gamesSvc = svc
    if certStore != nil { s.certStore = certStore }
    if objStore != nil { s.obj = objStore }
    s.objConf = objConf
    if ch != nil { s.ch = ch }
    return s, nil
}

// InitServerAppAuto composes *Server by constructing audit/rbac/jwt from environment.
func InitServerAppAuto(descriptorDir string, invoker FunctionInvoker, reg *registry.Store, locator interface{ GetJobAddr(string) (string, bool) }, statsProv interface{ GetStats() map[string]*AgentStats; GetPoolStats() *connpool.PoolStats }) (*Server, error) {
    db, err := ProvideGormDBFromEnv()
    if err != nil {
        return nil, err
    }
    _ = repogames.AutoMigrate(db)
    repo := repogames.NewRepo(db)
    portRepo := repogames.NewPortRepo(repo)
    defaults := ProvideGamesDefaults()
    svc := gamesvc.NewService(portRepo, defaults)
    audit, err := ProvideAuditWriterDefault()
    if err != nil {
        return nil, err
    }
    pol := ProvideRBACPolicyAuto()
    jwtMgr := ProvideJWTManagerFromEnv()
    certStore := ProvideCertStore(db)
    objStore, objConf := ProvideObjectStoreFromEnv()
    ch := ProvideClickHouseFromEnv()
    s, err := NewServer(descriptorDir, invoker, audit, pol, reg, jwtMgr, locator, statsProv)
    if err != nil {
        return nil, err
    }
    s.gdb = db
    s.games = repo
    s.gamesSvc = svc
    if certStore != nil { s.certStore = certStore }
    if objStore != nil { s.obj = objStore }
    s.objConf = objConf
    if ch != nil { s.ch = ch }
    return s, nil
}
