// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: croupier/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FunctionDescriptor describes a function registered by an Agent.
// Designed to be compatible with OpenAPI 3.0 operation object structure.
// See: https://spec.openapis.org/oas/v3.0.3.html#operation-object
type FunctionDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this function (e.g., "player.ban", "game_server.get_role")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Version of this function (semver, e.g. "1.2.0")
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Tags for categorization and UI grouping (e.g., ["player", "combat", "admin"])
	// Corresponds to OpenAPI 3.0 'tags' field
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// Short summary of what this function does
	// Corresponds to OpenAPI 3.0 'summary' field
	Summary string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// Detailed description of the function behavior
	// Corresponds to OpenAPI 3.0 'description' field
	// Supports CommonMark markdown syntax for rich text representation
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Whether this function is deprecated
	// Corresponds to OpenAPI 3.0 'deprecated' field
	Deprecated bool `protobuf:"varint,6,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// Operation ID from OpenAPI spec (unique identifier for the operation)
	// Corresponds to OpenAPI 3.0 'operationId' field
	OperationId string `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// External documentation for this function
	// Corresponds to OpenAPI 3.0 'externalDocs' field
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,8,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Parameters applicable to this function
	// Corresponds to OpenAPI 3.0 'parameters' field
	Parameters []*ParameterDescriptor `protobuf:"bytes,9,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Request body schema for this function
	// Corresponds to OpenAPI 3.0 'requestBody' field
	RequestBody *RequestBodyDescriptor `protobuf:"bytes,10,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	// Expected responses from this function
	// Corresponds to OpenAPI 3.0 'responses' field
	// Simplified: only describes success response schema
	Response *ResponseDescriptor `protobuf:"bytes,11,opt,name=response,proto3" json:"response,omitempty"`
	// Whether this function is currently enabled
	Enabled bool `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Legacy fields for backward compatibility (deprecated, use tags instead)
	Category      string `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`   // DEPRECATED: Use tags[0]
	Risk          string `protobuf:"bytes,14,opt,name=risk,proto3" json:"risk,omitempty"`           // DEPRECATED: Use tags to indicate risk level
	Entity        string `protobuf:"bytes,15,opt,name=entity,proto3" json:"entity,omitempty"`       // DEPRECATED: Use tags to indicate entity type
	Operation     string `protobuf:"bytes,16,opt,name=operation,proto3" json:"operation,omitempty"` // DEPRECATED: Use operation_id or tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDescriptor) Reset() {
	*x = FunctionDescriptor{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDescriptor) ProtoMessage() {}

func (x *FunctionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDescriptor.ProtoReflect.Descriptor instead.
func (*FunctionDescriptor) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FunctionDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FunctionDescriptor) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FunctionDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDescriptor) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *FunctionDescriptor) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *FunctionDescriptor) GetExternalDocs() *ExternalDocumentation {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *FunctionDescriptor) GetParameters() []*ParameterDescriptor {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *FunctionDescriptor) GetRequestBody() *RequestBodyDescriptor {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *FunctionDescriptor) GetResponse() *ResponseDescriptor {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FunctionDescriptor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FunctionDescriptor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FunctionDescriptor) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *FunctionDescriptor) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *FunctionDescriptor) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// ExternalDocumentation corresponds to OpenAPI 3.0 External Documentation Object
type ExternalDocumentation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A short description of the target documentation
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// The URL for the target documentation
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalDocumentation) Reset() {
	*x = ExternalDocumentation{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalDocumentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalDocumentation) ProtoMessage() {}

func (x *ExternalDocumentation) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalDocumentation.ProtoReflect.Descriptor instead.
func (*ExternalDocumentation) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalDocumentation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExternalDocumentation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ParameterDescriptor describes a parameter for a function.
// Corresponds to OpenAPI 3.0 parameter object.
type ParameterDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameter name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Parameter location: "query", "path", "header", "cookie"
	In string `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	// Parameter description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Whether this parameter is required
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Whether this parameter is deprecated
	Deprecated bool `protobuf:"varint,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// Parameter type: "string", "number", "integer", "boolean", "array", "object"
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// Type format: e.g., "int32", "int64", "float", "double", "date-time"
	Format string `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	// Default value (as JSON string)
	Default string `protobuf:"bytes,8,opt,name=default,proto3" json:"default,omitempty"`
	// Enum allowed values (as JSON array string)
	Enum string `protobuf:"bytes,9,opt,name=enum,proto3" json:"enum,omitempty"`
	// JSON schema for the parameter (for complex types)
	Schema        string `protobuf:"bytes,10,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterDescriptor) Reset() {
	*x = ParameterDescriptor{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDescriptor) ProtoMessage() {}

func (x *ParameterDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterDescriptor.ProtoReflect.Descriptor instead.
func (*ParameterDescriptor) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ParameterDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterDescriptor) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *ParameterDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParameterDescriptor) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ParameterDescriptor) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *ParameterDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParameterDescriptor) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ParameterDescriptor) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *ParameterDescriptor) GetEnum() string {
	if x != nil {
		return x.Enum
	}
	return ""
}

func (x *ParameterDescriptor) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// RequestBodyDescriptor corresponds to OpenAPI 3.0 Request Body Object
// Describes a single request body for a function
type RequestBodyDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A brief description of the request body
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the request body is required
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// The content of the request body (content_type -> schema mapping)
	// For simplicity, we support JSON schema as string
	Content       map[string]string `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "application/json" -> schema JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBodyDescriptor) Reset() {
	*x = RequestBodyDescriptor{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBodyDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBodyDescriptor) ProtoMessage() {}

func (x *RequestBodyDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBodyDescriptor.ProtoReflect.Descriptor instead.
func (*RequestBodyDescriptor) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *RequestBodyDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestBodyDescriptor) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *RequestBodyDescriptor) GetContent() map[string]string {
	if x != nil {
		return x.Content
	}
	return nil
}

// ResponseDescriptor corresponds to OpenAPI 3.0 Response Object
// Describes a single response from a function
type ResponseDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A short description of the response (REQUIRED in OpenAPI)
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Maps content type to schema
	Content map[string]string `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "application/json" -> schema JSON
	// HTTP status code this response describes (for reference only)
	StatusCode    string `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // e.g., "200", "201", "2XX"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseDescriptor) Reset() {
	*x = ResponseDescriptor{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDescriptor) ProtoMessage() {}

func (x *ResponseDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDescriptor.ProtoReflect.Descriptor instead.
func (*ResponseDescriptor) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseDescriptor) GetContent() map[string]string {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ResponseDescriptor) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // agent unique id
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                // agent version
	Functions     []*FunctionDescriptor  `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`            // summarized function list
	RpcAddr       string                 `protobuf:"bytes,4,opt,name=rpc_addr,json=rpcAddr,proto3" json:"rpc_addr,omitempty"` // agent's reachable gRPC address (DEV ONLY)
	GameId        string                 `protobuf:"bytes,5,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`    // game scope (required for multi-game)
	Env           string                 `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`                        // environment (optional: prod/stage/test)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetFunctions() []*FunctionDescriptor {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *RegisterRequest) GetRpcAddr() string {
	if x != nil {
		return x.RpcAddr
	}
	return ""
}

func (x *RegisterRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RegisterRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` // epoch seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{8}
}

// Provider capabilities (manifest) — language-agnostic declaration
type ProviderMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Sdk           string                 `protobuf:"bytes,4,opt,name=sdk,proto3" json:"sdk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMeta) Reset() {
	*x = ProviderMeta{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMeta) ProtoMessage() {}

func (x *ProviderMeta) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMeta.ProtoReflect.Descriptor instead.
func (*ProviderMeta) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderMeta) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ProviderMeta) GetSdk() string {
	if x != nil {
		return x.Sdk
	}
	return ""
}

type RegisterCapabilitiesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       *ProviderMeta          `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ManifestJsonGz []byte                 `protobuf:"bytes,2,opt,name=manifest_json_gz,json=manifestJsonGz,proto3" json:"manifest_json_gz,omitempty"` // gzipped manifest.json
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterCapabilitiesRequest) Reset() {
	*x = RegisterCapabilitiesRequest{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCapabilitiesRequest) ProtoMessage() {}

func (x *RegisterCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*RegisterCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterCapabilitiesRequest) GetProvider() *ProviderMeta {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *RegisterCapabilitiesRequest) GetManifestJsonGz() []byte {
	if x != nil {
		return x.ManifestJsonGz
	}
	return nil
}

type RegisterCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCapabilitiesResponse) Reset() {
	*x = RegisterCapabilitiesResponse{}
	mi := &file_croupier_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCapabilitiesResponse) ProtoMessage() {}

func (x *RegisterCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*RegisterCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_croupier_control_v1_control_proto_rawDescGZIP(), []int{11}
}

var File_croupier_control_v1_control_proto protoreflect.FileDescriptor

const file_croupier_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"!croupier/control/v1/control.proto\x12\x13croupier.control.v1\"\x80\x05\n" +
	"\x12FunctionDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x06 \x01(\bR\n" +
	"deprecated\x12!\n" +
	"\foperation_id\x18\a \x01(\tR\voperationId\x12O\n" +
	"\rexternal_docs\x18\b \x01(\v2*.croupier.control.v1.ExternalDocumentationR\fexternalDocs\x12H\n" +
	"\n" +
	"parameters\x18\t \x03(\v2(.croupier.control.v1.ParameterDescriptorR\n" +
	"parameters\x12M\n" +
	"\frequest_body\x18\n" +
	" \x01(\v2*.croupier.control.v1.RequestBodyDescriptorR\vrequestBody\x12C\n" +
	"\bresponse\x18\v \x01(\v2'.croupier.control.v1.ResponseDescriptorR\bresponse\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12\x1a\n" +
	"\bcategory\x18\r \x01(\tR\bcategory\x12\x12\n" +
	"\x04risk\x18\x0e \x01(\tR\x04risk\x12\x16\n" +
	"\x06entity\x18\x0f \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\x10 \x01(\tR\toperation\"K\n" +
	"\x15ExternalDocumentation\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x89\x02\n" +
	"\x13ParameterDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02in\x18\x02 \x01(\tR\x02in\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x05 \x01(\bR\n" +
	"deprecated\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x18\n" +
	"\adefault\x18\b \x01(\tR\adefault\x12\x12\n" +
	"\x04enum\x18\t \x01(\tR\x04enum\x12\x16\n" +
	"\x06schema\x18\n" +
	" \x01(\tR\x06schema\"\xe4\x01\n" +
	"\x15RequestBodyDescriptor\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12Q\n" +
	"\acontent\x18\x03 \x03(\v27.croupier.control.v1.RequestBodyDescriptor.ContentEntryR\acontent\x1a:\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x01\n" +
	"\x12ResponseDescriptor\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12N\n" +
	"\acontent\x18\x02 \x03(\v24.croupier.control.v1.ResponseDescriptor.ContentEntryR\acontent\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\tR\n" +
	"statusCode\x1a:\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12E\n" +
	"\tfunctions\x18\x03 \x03(\v2'.croupier.control.v1.FunctionDescriptorR\tfunctions\x12\x19\n" +
	"\brpc_addr\x18\x04 \x01(\tR\arpcAddr\x12\x17\n" +
	"\agame_id\x18\x05 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03env\x18\x06 \x01(\tR\x03env\"N\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\"L\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x13\n" +
	"\x11HeartbeatResponse\"^\n" +
	"\fProviderMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x10\n" +
	"\x03sdk\x18\x04 \x01(\tR\x03sdk\"\x86\x01\n" +
	"\x1bRegisterCapabilitiesRequest\x12=\n" +
	"\bprovider\x18\x01 \x01(\v2!.croupier.control.v1.ProviderMetaR\bprovider\x12(\n" +
	"\x10manifest_json_gz\x18\x02 \x01(\fR\x0emanifestJsonGz\"\x1e\n" +
	"\x1cRegisterCapabilitiesResponse2\xc2\x02\n" +
	"\x0eControlService\x12W\n" +
	"\bRegister\x12$.croupier.control.v1.RegisterRequest\x1a%.croupier.control.v1.RegisterResponse\x12Z\n" +
	"\tHeartbeat\x12%.croupier.control.v1.HeartbeatRequest\x1a&.croupier.control.v1.HeartbeatResponse\x12{\n" +
	"\x14RegisterCapabilities\x120.croupier.control.v1.RegisterCapabilitiesRequest\x1a1.croupier.control.v1.RegisterCapabilitiesResponseB\xd8\x01\n" +
	"\x17com.croupier.control.v1B\fControlProtoP\x01ZAgithub.com/cuihairu/croupier/pkg/pb/croupier/control/v1;controlv1\xa2\x02\x03CCX\xaa\x02\x13Croupier.Control.V1\xca\x02\x13Croupier\\Control\\V1\xe2\x02\x1fCroupier\\Control\\V1\\GPBMetadata\xea\x02\x15Croupier::Control::V1b\x06proto3"

var (
	file_croupier_control_v1_control_proto_rawDescOnce sync.Once
	file_croupier_control_v1_control_proto_rawDescData []byte
)

func file_croupier_control_v1_control_proto_rawDescGZIP() []byte {
	file_croupier_control_v1_control_proto_rawDescOnce.Do(func() {
		file_croupier_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_control_v1_control_proto_rawDesc), len(file_croupier_control_v1_control_proto_rawDesc)))
	})
	return file_croupier_control_v1_control_proto_rawDescData
}

var file_croupier_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_croupier_control_v1_control_proto_goTypes = []any{
	(*FunctionDescriptor)(nil),           // 0: croupier.control.v1.FunctionDescriptor
	(*ExternalDocumentation)(nil),        // 1: croupier.control.v1.ExternalDocumentation
	(*ParameterDescriptor)(nil),          // 2: croupier.control.v1.ParameterDescriptor
	(*RequestBodyDescriptor)(nil),        // 3: croupier.control.v1.RequestBodyDescriptor
	(*ResponseDescriptor)(nil),           // 4: croupier.control.v1.ResponseDescriptor
	(*RegisterRequest)(nil),              // 5: croupier.control.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 6: croupier.control.v1.RegisterResponse
	(*HeartbeatRequest)(nil),             // 7: croupier.control.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 8: croupier.control.v1.HeartbeatResponse
	(*ProviderMeta)(nil),                 // 9: croupier.control.v1.ProviderMeta
	(*RegisterCapabilitiesRequest)(nil),  // 10: croupier.control.v1.RegisterCapabilitiesRequest
	(*RegisterCapabilitiesResponse)(nil), // 11: croupier.control.v1.RegisterCapabilitiesResponse
	nil,                                  // 12: croupier.control.v1.RequestBodyDescriptor.ContentEntry
	nil,                                  // 13: croupier.control.v1.ResponseDescriptor.ContentEntry
}
var file_croupier_control_v1_control_proto_depIdxs = []int32{
	1,  // 0: croupier.control.v1.FunctionDescriptor.external_docs:type_name -> croupier.control.v1.ExternalDocumentation
	2,  // 1: croupier.control.v1.FunctionDescriptor.parameters:type_name -> croupier.control.v1.ParameterDescriptor
	3,  // 2: croupier.control.v1.FunctionDescriptor.request_body:type_name -> croupier.control.v1.RequestBodyDescriptor
	4,  // 3: croupier.control.v1.FunctionDescriptor.response:type_name -> croupier.control.v1.ResponseDescriptor
	12, // 4: croupier.control.v1.RequestBodyDescriptor.content:type_name -> croupier.control.v1.RequestBodyDescriptor.ContentEntry
	13, // 5: croupier.control.v1.ResponseDescriptor.content:type_name -> croupier.control.v1.ResponseDescriptor.ContentEntry
	0,  // 6: croupier.control.v1.RegisterRequest.functions:type_name -> croupier.control.v1.FunctionDescriptor
	9,  // 7: croupier.control.v1.RegisterCapabilitiesRequest.provider:type_name -> croupier.control.v1.ProviderMeta
	5,  // 8: croupier.control.v1.ControlService.Register:input_type -> croupier.control.v1.RegisterRequest
	7,  // 9: croupier.control.v1.ControlService.Heartbeat:input_type -> croupier.control.v1.HeartbeatRequest
	10, // 10: croupier.control.v1.ControlService.RegisterCapabilities:input_type -> croupier.control.v1.RegisterCapabilitiesRequest
	6,  // 11: croupier.control.v1.ControlService.Register:output_type -> croupier.control.v1.RegisterResponse
	8,  // 12: croupier.control.v1.ControlService.Heartbeat:output_type -> croupier.control.v1.HeartbeatResponse
	11, // 13: croupier.control.v1.ControlService.RegisterCapabilities:output_type -> croupier.control.v1.RegisterCapabilitiesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_croupier_control_v1_control_proto_init() }
func file_croupier_control_v1_control_proto_init() {
	if File_croupier_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_control_v1_control_proto_rawDesc), len(file_croupier_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_croupier_control_v1_control_proto_goTypes,
		DependencyIndexes: file_croupier_control_v1_control_proto_depIdxs,
		MessageInfos:      file_croupier_control_v1_control_proto_msgTypes,
	}.Build()
	File_croupier_control_v1_control_proto = out.File
	file_croupier_control_v1_control_proto_goTypes = nil
	file_croupier_control_v1_control_proto_depIdxs = nil
}
