// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type Admin struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Nickname  string   `json:"nickname"`
	Email     string   `json:"email"`
	Phone     string   `json:"phone"`
	Roles     []string `json:"roles"`
	Status    int      `json:"status"` // 1:active 0:disabled
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}
type AdminCreateRequest struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Nickname string   `json:"nickname,optional"`
	Email    string   `json:"email,optional"`
	Phone    string   `json:"phone,optional"`
	Roles    []string `json:"roles"`
}
type AdminCreateResponse struct {
	Admin
}
type AdminDeleteRequest struct {
	ID string `path:"id"`
}
type AdminDeleteResponse struct {
	Message string `json:"message"`
}
type AdminDetailRequest struct {
	ID string `path:"id"`
}
type AdminDetailResponse struct {
	Admin
}
type AdminPasswordResetRequest struct {
	ID          string `path:"id"`
	NewPassword string `json:"newPassword"`
}
type AdminPasswordResetResponse struct {
	Message string `json:"message"`
}
type AdminUpdateRequest struct {
	ID       string   `path:"id"`
	Nickname string   `json:"nickname,optional"`
	Email    string   `json:"email,optional"`
	Phone    string   `json:"phone,optional"`
	Roles    []string `json:"roles,optional"`
	Status   int      `json:"status,optional"`
}
type AdminUpdateResponse struct {
	Admin
}
type AdminsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Search   string `form:"search,optional"`
	Role     string `form:"role,optional"`
	Status   int    `form:"status,optional"`
}
type AdminsListResponse struct {
	Items []Admin `json:"items"`
	Total int64   `json:"total"`
	Page  int     `json:"page"`
	Size  int     `json:"pageSize"`
}
type Permission struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Category    string `json:"category"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}
type PermissionDetailRequest struct {
	ID string `path:"id"`
}
type PermissionDetailResponse struct {
	Permission
}
type PermissionsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Category string `form:"category,optional"`
	Resource string `form:"resource,optional"`
}
type PermissionsListResponse struct {
	Items []Permission `json:"items"`
	Total int64        `json:"total"`
	Page  int          `json:"page"`
	Size  int          `json:"pageSize"`
}
type Role struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Permissions []string `json:"permissions"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}
type RoleCreateRequest struct {
	Name        string   `json:"name"`
	Description string   `json:"description,optional"`
	Category    string   `json:"category,optional"`
	Permissions []string `json:"permissions,optional"`
}
type RoleCreateResponse struct {
	Role
}
type RoleDeleteRequest struct {
	ID string `path:"id"`
}
type RoleDetailRequest struct {
	ID string `path:"id"`
}
type RoleDetailResponse struct {
	Role
}
type RoleUpdateRequest struct {
	ID          string   `path:"id"`
	Name        string   `json:"name,optional"`
	Description string   `json:"description,optional"`
	Category    string   `json:"category,optional"`
	Permissions []string `json:"permissions,optional"`
}
type RoleUpdateResponse struct {
	Role
}
type RolesListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Category string `form:"category,optional"`
	Search   string `form:"search,optional"`
}
type RolesListResponse struct {
	Items []Role `json:"items"`
	Total int64  `json:"total"`
	Page  int    `json:"page"`
	Size  int    `json:"pageSize"`
}
