// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type BehaviorAdoptionBreakdownRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	Feature   string `form:"feature"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type BehaviorAdoptionBreakdownResponse struct {
	BySegment interface{} `json:"bySegment"`
	ByTime    interface{} `json:"byTime"`
}
type BehaviorAdoptionRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	Feature   string `form:"feature,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type BehaviorAdoptionResponse struct {
	Features []FeatureAdoption `json:"features"`
}
type BehaviorEvent struct {
	EventType string      `json:"eventType"`
	UserId    string      `json:"userId"`
	Data      interface{} `json:"data"`
	Timestamp string      `json:"timestamp"`
}
type BehaviorEventsRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	EventType string `form:"eventType,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	Limit     int    `form:"limit,optional,default=100"`
}
type BehaviorEventsResponse struct {
	Items []BehaviorEvent `json:"items"`
	Total int64           `json:"total"`
}
type BehaviorFunnelRequest struct {
	GameId    string   `form:"gameId,optional"`
	Env       string   `form:"env,optional"`
	Steps     []string `json:"steps"`
	StartDate string   `form:"startDate,optional"`
	EndDate   string   `form:"endDate,optional"`
}
type BehaviorFunnelResponse struct {
	Steps []FunnelStep `json:"steps"`
}
type BehaviorPathsRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	Depth     int    `form:"depth,optional,default=5"`
}
type BehaviorPathsResponse struct {
	Paths interface{} `json:"paths"`
}
type BehaviorRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type BehaviorResponse struct {
	TopActions interface{} `json:"topActions"`
	UserFlows  interface{} `json:"userFlows"`
	HeatMap    interface{} `json:"heatMap"`
}
type EpisodeMetrics struct {
	EpisodeId      string  `json:"episodeId"`
	Players        int     `json:"players"`
	CompletionRate float64 `json:"completionRate"`
	AvgProgress    float64 `json:"avgProgress"`
}
type FunnelStep struct {
	Step           string  `json:"step"`
	Users          int     `json:"users"`
	ConversionRate float64 `json:"conversionRate"`
	DropOffRate    float64 `json:"dropOffRate"`
}
type LevelMetrics struct {
	LevelId        string  `json:"levelId"`
	Attempts       int     `json:"attempts"`
	Completions    int     `json:"completions"`
	CompletionRate float64 `json:"completionRate"`
	AvgDuration    float64 `json:"avgDuration"`
	AvgRetries     float64 `json:"avgRetries"`
}
type LevelsEpisodesRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type LevelsEpisodesResponse struct {
	Episodes []EpisodeMetrics `json:"episodes"`
}
type LevelsMapsRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type LevelsMapsResponse struct {
	Maps []MapMetrics `json:"maps"`
}
type LevelsRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type LevelsResponse struct {
	Levels []LevelMetrics `json:"levels"`
}
type MapMetrics struct {
	MapId      string      `json:"mapId"`
	HeatMap    interface{} `json:"heatMap"`
	DeathSpots interface{} `json:"deathSpots"`
}
type OverviewMetrics struct {
	DAU        int     `json:"dau"`
	MAU        int     `json:"mau"`
	NewUsers   int     `json:"newUsers"`
	Revenue    float64 `json:"revenue"`
	ARPU       float64 `json:"arpu"`
	ARPPU      float64 `json:"arppu"`
	PayingRate float64 `json:"payingRate"`
}
type OverviewRequest struct {
	AnalyticsQuery
}
type OverviewResponse struct {
	Metrics OverviewMetrics `json:"metrics"`
	Trends  interface{}     `json:"trends"`
}
type PaymentsIngestRequest struct {
	GameId       string      `json:"gameId"`
	Env          string      `json:"env"`
	Transactions interface{} `json:"transactions"`
	Timestamp    string      `json:"timestamp,optional"`
}
type PaymentsIngestResponse struct {
	Accepted int    `json:"accepted"`
	Rejected int    `json:"rejected"`
	BatchId  string `json:"batchId"`
}
type PaymentsMetrics struct {
	Revenue        float64 `json:"revenue"`
	Transactions   int     `json:"transactions"`
	PayingUsers    int     `json:"payingUsers"`
	ARPU           float64 `json:"arpu"`
	ARPPU          float64 `json:"arppu"`
	ConversionRate float64 `json:"conversionRate"`
}
type PaymentsProductTrendRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	Limit     int    `form:"limit,optional,default=10"`
}
type PaymentsProductTrendResponse struct {
	Items []ProductTrend `json:"items"`
}
type PaymentsRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type PaymentsResponse struct {
	Metrics PaymentsMetrics `json:"metrics"`
	Trends  interface{}     `json:"trends"`
}
type PaymentsSummary struct {
	Date         string  `json:"date"`
	Revenue      float64 `json:"revenue"`
	Transactions int     `json:"transactions"`
	Users        int     `json:"users"`
}
type PaymentsSummaryRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	GroupBy   string `form:"groupBy,optional,default=day"` // day, week, month
}
type PaymentsSummaryResponse struct {
	Items []PaymentsSummary `json:"items"`
}
type PaymentsTransactionsRequest struct {
	Page      int    `form:"page,optional,default=1"`
	PageSize  int    `form:"pageSize,optional,default=20"`
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	Status    string `form:"status,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type PaymentsTransactionsResponse struct {
	Items []PaymentTransaction `json:"items"`
	Total int64                `json:"total"`
	Page  int                  `json:"page"`
	Size  int                  `json:"pageSize"`
}
type RealtimeMetrics struct {
	OnlineUsers    int         `json:"onlineUsers"`
	ActiveSessions int         `json:"activeSessions"`
	QPS            float64     `json:"qps"`
	AvgLatency     float64     `json:"avgLatency"`
	ErrorRate      float64     `json:"errorRate"`
	TopEvents      interface{} `json:"topEvents"`
}
type RealtimeRequest struct {
	GameId string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}
type RealtimeResponse struct {
	RealtimeMetrics
	Timestamp string `json:"timestamp"`
}
type RealtimeSeriesRequest struct {
	GameId   string `form:"gameId,optional"`
	Env      string `form:"env,optional"`
	Interval string `form:"interval,optional,default=1m"` // 1m, 5m, 15m
	Duration int    `form:"duration,optional,default=60"` // 分钟
}
type RealtimeSeriesResponse struct {
	Series interface{} `json:"series"`
}
type RetentionCohort struct {
	Cohort    string    `json:"cohort"`
	Users     int       `json:"users"`
	Retention []float64 `json:"retention"` // Day 1, 3, 7, 14, 30
}
type RetentionRequest struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	Cohort    string `form:"cohort,optional"` // daily, weekly, monthly
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type RetentionResponse struct {
	Cohorts []RetentionCohort `json:"cohorts"`
}
