// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type ApprovalApproveRequest struct {
	ID string `path:"id"` // 审批ID
}
type ApprovalApproveResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ApprovalGetRequest struct {
	ID string `path:"id"` // 审批ID
}
type ApprovalGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ApprovalRejectRequest struct {
	ID     string `path:"id"`     // 审批ID
	Reason string `json:"reason"` // 拒绝原因
}
type ApprovalRejectResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ApprovalsListRequest struct {
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
	Status   string `form:"status,optional"`   // 状态过滤
}
type ApprovalsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
