// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type AuditRequest struct {
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
	Action   string `form:"action,optional"`   // 操作类型过滤
	UserID   string `form:"userId,optional"`   // 用户ID过滤
}
type AuditResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
