// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type CertificateAddRequest struct {
	Domain      string `json:"domain"`
	Certificate string `json:"certificate,optional"`
	PrivateKey  string `json:"privateKey,optional"`
}
type CertificateAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateAlertAddRequest struct {
	Domain    string `json:"domain"`
	Threshold int    `json:"threshold,optional"`
}
type CertificateAlertAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateAlertsListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}
type CertificateAlertsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateCheckAllRequest struct {
}
type CertificateCheckAllResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateCheckRequest struct {
	ID string `path:"id"`
}
type CertificateCheckResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateDeleteRequest struct {
	ID string `path:"id"`
}
type CertificateDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateDetailRequest struct {
	ID string `path:"id"`
}
type CertificateDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateDomainInfoRequest struct {
	Domain string `form:"domain"`
}
type CertificateDomainInfoResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateExpiringRequest struct {
	Days int `form:"days,optional"`
}
type CertificateExpiringResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificateStatsRequest struct {
}
type CertificateStatsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type CertificatesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}
type CertificatesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
