// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type AnalyticsFilters struct {
	GameId  string      `json:"gameId"`
	Filters interface{} `json:"filters"`
}
type AnalyticsFiltersQuery struct {
}
type AnalyticsQuery struct {
	GameId    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}
type BatchCopyFunctionsRequest struct {
	FunctionIds []string `json:"function_ids"`
}
type BatchCopyFunctionsResponse struct {
	Updated int      `json:"updated"`
	Failed  []string `json:"failed"`
	Copied  []string `json:"copied"` // 新复制的函数ID列表
}
type BatchDeleteFunctionsRequest struct {
	FunctionIds []string `json:"function_ids"`
}
type BatchDeleteFunctionsResponse struct {
	Updated int      `json:"updated"`
	Failed  []string `json:"failed"`
}
type BatchUpdateFunctionsRequest struct {
	FunctionIds []string `json:"function_ids"`
	Enabled     bool     `json:"enabled"`
}
type BatchUpdateFunctionsResponse struct {
	Updated int      `json:"updated"`
	Failed  []string `json:"failed"`
}
type EntitiesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Type     string `form:"type,optional"`
}
type EntitiesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type FeatureAdoption struct {
	Feature      string  `json:"feature"`
	Users        int     `json:"users"`
	AdoptionRate float64 `json:"adoptionRate"`
	Frequency    float64 `json:"frequency"`
}
type FiltersGetRequest struct {
	GameId string `form:"gameId,optional"`
}
type FiltersGetResponse struct {
	Items []AnalyticsFilters `json:"items"`
}
type FiltersUpdateRequest struct {
	GameId  string      `json:"gameId"`
	Filters interface{} `json:"filters"`
}
type PaymentTransaction struct {
	Id            string  `json:"id"`
	UserId        string  `json:"userId"`
	ProductId     string  `json:"productId"`
	Amount        float64 `json:"amount"`
	Currency      string  `json:"currency"`
	Status        string  `json:"status"`
	PaymentMethod string  `json:"paymentMethod"`
	CreatedAt     string  `json:"createdAt"`
}
type PendingFunction struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	Requester string `json:"requester"`
	CreatedAt string `json:"createdAt"`
}
type ProductTrend struct {
	ProductId   string  `json:"productId"`
	ProductName string  `json:"productName"`
	Revenue     float64 `json:"revenue"`
	Sales       int     `json:"sales"`
	Growth      float64 `json:"growth"`
}
type UISchemaRequest struct {
	Type string `form:"type"`
}
type UISchemaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
