// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type Descriptor struct {
	Id          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Schema      interface{} `json:"schema"`
}
type DescriptorsRequest struct {
	Type   string `form:"type,optional"`
	GameId string `form:"gameId,optional"`
}
type DescriptorsResponse struct {
	Items []Descriptor `json:"items"`
}
