// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type EntityCreateRequest struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}
type EntityCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type EntityDeleteRequest struct {
	ID string `path:"id"`
}
type EntityDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type EntityDetailRequest struct {
	ID string `path:"id"`
}
type EntityDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type EntityPreviewRequest struct {
	ID string `path:"id"`
}
type EntityPreviewResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type EntityUpdateRequest struct {
	ID   string      `path:"id"`
	Data interface{} `json:"data"`
}
type EntityUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type EntityValidateRequest struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}
type EntityValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
