// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type FAQ struct {
	Id        int64    `json:"id"`
	Question  string   `json:"question"`
	Answer    string   `json:"answer"`
	Category  string   `json:"category"`
	Tags      []string `json:"tags"`
	Visible   bool     `json:"visible"`
	Sort      int      `json:"sort"`
	Views     int      `json:"views"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}
type FAQCategoriesRequest struct {
}
type FAQCategoriesResponse struct {
	Items []FAQCategory `json:"items"`
}
type FAQCategory struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}
type FAQCreateRequest struct {
	Question string   `json:"question"`
	Answer   string   `json:"answer"`
	Category string   `json:"category"`
	Tags     []string `json:"tags,optional"`
	Visible  bool     `json:"visible,optional,default=true"`
	Sort     int      `json:"sort,optional,default=0"`
}
type FAQDeleteRequest struct {
	ID string `path:"id"`
}
type FAQDetailResponse struct {
	FAQ
}
type FAQListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Category string `form:"category,optional"`
	Keyword  string `form:"keyword,optional"`
	Visible  *bool  `form:"visible,optional"`
}
type FAQListResponse struct {
	Items []FAQ `json:"items"`
	Total int64 `json:"total"`
	Page  int   `json:"page"`
	Size  int   `json:"pageSize"`
}
type FAQUpdateRequest struct {
	ID       string   `path:"id"`
	Question string   `json:"question,optional"`
	Answer   string   `json:"answer,optional"`
	Category string   `json:"category,optional"`
	Tags     []string `json:"tags,optional"`
	Visible  *bool    `json:"visible,optional"`
	Sort     *int     `json:"sort,optional"`
}
