// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type Function struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Category    string `json:"category"`
	GameId      string `json:"gameId"`
	Status      int    `json:"status"`
	Version     string `json:"version"`
	Instances   int    `json:"instances"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}
type FunctionActionRequest struct {
	ID string `path:"id"`
}
type FunctionCopyRequest struct {
	ID string `path:"id"`
}
type FunctionCopyResponse struct {
	FunctionId string `json:"function_id"`
	NewId      string `json:"new_id"`
}
type FunctionDescriptor struct {
	Input  interface{} `json:"input"`
	Output interface{} `json:"output"`
	Schema interface{} `json:"schema"`
}
type FunctionDetailRequest struct {
	ID string `path:"id"`
}
type FunctionDetailResponse struct {
	Function
	Descriptor FunctionDescriptor `json:"descriptor"`
}
type FunctionInstance struct {
	AgentId   string `json:"agentId"`
	AgentName string `json:"agentName"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updatedAt"`
}
type FunctionInstancesRequest struct {
	ID string `path:"id"`
}
type FunctionInstancesResponse struct {
	Items []FunctionInstance `json:"items"`
}
type FunctionInvokeRequest struct {
	ID              string      `path:"id"`
	Params          interface{} `json:"params,optional"`
	Payload         interface{} `json:"payload,optional"`
	GameID          string      `json:"gameId,optional"`
	Env             string      `json:"env,optional"`
	Mode            string      `json:"mode,optional"`
	Route           string      `json:"route,optional"`
	TargetServiceID string      `json:"target_service_id,optional"`
	HashKey         string      `json:"hash_key,optional"`
}
type FunctionInvokeResponse struct {
	JobId  string      `json:"jobId"`
	JobID  string      `json:"jobID,omitempty"`
	Result interface{} `json:"result,omitempty"`
}
type FunctionPermission struct {
	Resource string   `json:"resource"`
	Actions  []string `json:"actions"`
	Roles    []string `json:"roles"`
}
type FunctionPermissionsRequest struct {
	ID string `path:"id"`
}
type FunctionPermissionsResponse struct {
	Items []FunctionPermission `json:"items"`
}
type FunctionPermissionsUpdateRequest struct {
	ID          string               `path:"id"`
	Permissions []FunctionPermission `json:"permissions"`
}
type FunctionPublishRequest struct {
	ID string `path:"id"`
}
type FunctionPublishResponse struct {
	ApprovalId string `json:"approvalId,omitempty"` // 如果需要审批
	Published  bool   `json:"published"`
}
type FunctionUIRequest struct {
	ID string `path:"id"`
}
type FunctionUIResponse struct {
	Schema     interface{} `json:"schema"`
	Layout     interface{} `json:"layout"`
	Components interface{} `json:"components"`
}
type FunctionUIUpdateRequest struct {
	ID         string      `path:"id"`
	Schema     interface{} `json:"schema,optional"`
	Layout     interface{} `json:"layout,optional"`
	Components interface{} `json:"components,optional"`
}
type FunctionsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	GameId   string `form:"gameId,optional"`
	Category string `form:"category,optional"`
	Status   int    `form:"status,optional"`
}
type FunctionsListResponse struct {
	Items []Function `json:"items"`
	Total int64      `json:"total"`
	Page  int        `json:"page"`
	Size  int        `json:"pageSize"`
}
type FunctionsPendingRequest struct {
}
type FunctionsPendingResponse struct {
	Items []PendingFunction `json:"items"`
}
