// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type GameCreateRequest struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Config      string `json:"config,optional"`
}
type GameCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type GameDeleteRequest struct {
	ID string `path:"id"`
}
type GameDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type GameDetailRequest struct {
	ID string `path:"id"`
}
type GameDetailResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    GameInfo `json:"data,omitempty"`
}
type GameEnvAddRequest struct {
	ID   string `path:"id"`
	Name string `json:"name"`
	Type string `json:"type,optional"`
}
type GameEnvAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type GameEnvDeleteRequest struct {
	ID    string `path:"id"`
	EnvID string `path:"envId"`
}
type GameEnvDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type GameEnvItem struct {
	Env         string `json:"env"`
	Description string `json:"description,optional"`
	Color       string `json:"color,optional"`
}
type GameEnvUpdateRequest struct {
	ID    string `path:"id"`
	EnvID string `path:"envId"`
	Name  string `json:"name,optional"`
	Type  string `json:"type,optional"`
}
type GameEnvUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type GameEnvsData struct {
	Envs []GameEnvItem `json:"envs"`
}
type GameEnvsListRequest struct {
	ID string `path:"id"`
}
type GameEnvsListResponse struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    GameEnvsData `json:"data,omitempty"`
}
type GameInfo struct {
	ID          uint          `json:"id"`
	Name        string        `json:"name"`
	Icon        string        `json:"icon,optional"`
	Description string        `json:"description,optional"`
	Enabled     bool          `json:"enabled"`
	AliasName   string        `json:"aliasName,optional"`
	Homepage    string        `json:"homepage,optional"`
	Status      string        `json:"status"`
	GameType    string        `json:"gameType,optional"`
	GenreCode   string        `json:"genreCode,optional"`
	Color       string        `json:"color,optional"`
	Envs        []GameEnvItem `json:"envs,optional"`
	CreatedAt   string        `json:"createdAt,optional"`
	UpdatedAt   string        `json:"updatedAt,optional"`
}
type GameUpdateRequest struct {
	ID          string `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Config      string `json:"config,optional"`
	Status      string `json:"status,optional"`
}
type GameUpdateResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    GameInfo `json:"data,omitempty"`
}
type GamesData struct {
	Games []GameInfo `json:"games"`
	Total int        `json:"total,optional"`
}
type GamesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}
type GamesListResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    GamesData `json:"data,omitempty"`
}
