// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type JobCancelRequest struct {
	ID string `path:"id"` // 任务ID
}
type JobCancelResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type JobItem struct {
	ID         string `json:"id"`
	FunctionID string `json:"function_id,omitempty"`
	Actor      string `json:"actor,omitempty"`
	State      string `json:"state,omitempty"`
	GameID     string `json:"game_id,omitempty"`
	Env        string `json:"env,omitempty"`
	RPCAddr    string `json:"rpc_addr,omitempty"`
	StartedAt  string `json:"started_at,omitempty"`
	EndedAt    string `json:"ended_at,omitempty"`
	DurationMs int64  `json:"duration_ms,omitempty"`
	Error      string `json:"error,omitempty"`
}
type JobListRequest struct {
	Status     string `form:"status,optional"`
	FunctionID string `form:"function_id,optional"`
	Actor      string `form:"actor,optional"`
	GameID     string `form:"game_id,optional"`
	Env        string `form:"env,optional"`
	Page       int    `form:"page,optional,default=1"`
	Size       int    `form:"size,optional,default=20"`
}
type JobListResponse struct {
	Jobs  []JobItem `json:"jobs"`
	Total int       `json:"total"`
}
type JobResultRequest struct {
	ID string `path:"id"` // 任务ID
}
type JobResultResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type JobStartRequest struct {
	FunctionID string      `json:"functionId"` // 函数ID
	Params     interface{} `json:"params,optional"`
}
type JobStartResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
