// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type ListPlatformMethodsResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Methods []string `json:"methods,omitempty"`
}
type ListPlatformsResponse struct {
	Code      int            `json:"code"`
	Message   string         `json:"message"`
	Platforms []PlatformInfo `json:"platforms,omitempty"`
}
type PlatformInfo struct {
	Name    string   `json:"name"`    // 平台名称
	Enabled bool     `json:"enabled"` // 是否启用
	Methods []string `json:"methods"` // 支持的方法列表
}
