// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type Player struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	GameId    string `json:"gameId"`
	Status    int    `json:"status"`  // 1:active 0:banned 2:suspended
	Balance   int64  `json:"balance"` // 游戏货币
	Level     int    `json:"level"`
	Vip       int    `json:"vip"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
type PlayerBalanceRequest struct {
	ID     string `path:"id"`
	Amount int64  `json:"amount"`
	Reason string `json:"reason"`
}
type PlayerBalanceResponse struct {
	Player
}
type PlayerCreateRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	GameId   string `json:"gameId"`
}
type PlayerCreateResponse struct {
	Player
}
type PlayerDeleteRequest struct {
	ID string `path:"id"`
}
type PlayerDetailRequest struct {
	ID string `path:"id"`
}
type PlayerDetailResponse struct {
	Player
}
type PlayerUpdateRequest struct {
	ID       string `path:"id"`
	Nickname string `json:"nickname,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Status   int    `json:"status,optional"`
	Level    int    `json:"level,optional"`
	Vip      int    `json:"vip,optional"`
}
type PlayerUpdateResponse struct {
	Player
}
type PlayersListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	GameId   string `form:"gameId,optional"`
	Search   string `form:"search,optional"`
	Status   int    `form:"status,optional"`
	Level    int    `form:"level,optional"`
	Vip      int    `form:"vip,optional"`
}
type PlayersListResponse struct {
	Items []Player `json:"items"`
	Total int64    `json:"total"`
	Page  int      `json:"page"`
	Size  int      `json:"pageSize"`
}
