// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type CallPlatformRequest struct {
	Platform string `json:"platform"` // 平台名称，如 "quicksdk"
	Method   string `json:"method"`   // API 方法名
	Request  string `json:"request"`  // 请求参数（JSON 字符串格式）
}
type CallPlatformResponse struct {
	Code     int         `json:"code"`
	Message  string      `json:"message"`
	Response interface{} `json:"response,omitempty"` // 平台返回的响应
}
type IngestRequest struct {
	GameId    string      `json:"gameId"`
	Env       string      `json:"env"`
	Events    interface{} `json:"events"`
	Timestamp string      `json:"timestamp,optional"`
}
type IngestResponse struct {
	Accepted int    `json:"accepted"`
	Rejected int    `json:"rejected"`
	BatchId  string `json:"batchId"`
}
type ProviderActionRequest struct {
	ID string `path:"id"`
}
type ProviderDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ProviderDetailRequest struct {
	ID string `path:"id"`
}
type ProviderDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ProviderReloadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ProvidersCapabilitiesRequest struct {
}
type ProvidersCapabilitiesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ProvidersDescriptorsRequest struct {
}
type ProvidersDescriptorsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ProvidersEntitiesRequest struct {
	ID string `path:"id"`
}
type ProvidersEntitiesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ProvidersListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}
type ProvidersListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type ReloadPlatformConfigResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Success bool   `json:"success,omitempty"`
}
type RootRequest struct {
}
type RootResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SignedUrlRequest struct {
	Path   string `form:"path"`
	Expire int    `form:"expire,optional"`
}
type SignedUrlResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type StatusRequest struct {
}
type StatusResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type StreamJobRequest struct {
	JobID string `path:"jobId"`
}
type StreamJobResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type StreamMessagesRequest struct {
}
type StreamMessagesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
