// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type SchemaCreateRequest struct {
	Name   string      `json:"name"`
	Schema interface{} `json:"schema"`
}
type SchemaCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaDeleteRequest struct {
	ID string `path:"id"`
}
type SchemaDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaDetailRequest struct {
	ID string `path:"id"`
}
type SchemaDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaRawValidateRequest struct {
	Schema interface{} `json:"schema"`
	Data   interface{} `json:"data"`
}
type SchemaRawValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaUIConfigRequest struct {
	ID string `path:"id"`
}
type SchemaUIConfigResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaUIConfigUpdateRequest struct {
	ID     string      `path:"id"`
	Config interface{} `json:"config"`
}
type SchemaUIConfigUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaUpdateRequest struct {
	ID     string      `path:"id"`
	Schema interface{} `json:"schema"`
}
type SchemaUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemaValidateRequest struct {
	ID   string      `path:"id"`
	Data interface{} `json:"data"`
}
type SchemaValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
type SchemasListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}
type SchemasListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
