// Code generated by goctl. DO NOT EDIT.
// This file is automatically split from types.go by scripts/split-types.sh

package types

type Comment struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	Author    string `json:"author"`
	CreatedAt string `json:"createdAt"`
}
type Ticket struct {
	Id        int64    `json:"id"`
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	Category  string   `json:"category"`
	Priority  string   `json:"priority"`
	Status    string   `json:"status"`
	Assignee  string   `json:"assignee"`
	Tags      []string `json:"tags"`
	PlayerId  string   `json:"playerId"`
	Contact   string   `json:"contact"`
	GameId    string   `json:"gameId"`
	Env       string   `json:"env"`
	Source    string   `json:"source"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}
type TicketCommentCreateRequest struct {
	TicketID string `path:"ticketId"`
	Content  string `json:"content"`
}
type TicketCommentsRequest struct {
	TicketID string `path:"ticketId"`
}
type TicketCommentsResponse struct {
	Items []Comment `json:"items"`
}
type TicketCreateRequest struct {
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category string   `json:"category"`
	Priority string   `json:"priority,optional,default=medium"`
	Tags     []string `json:"tags,optional"`
	PlayerId string   `json:"playerId,optional"`
	Contact  string   `json:"contact,optional"`
	GameId   string   `json:"gameId,optional"`
	Env      string   `json:"env,optional"`
}
type TicketDeleteRequest struct {
	ID string `path:"id"`
}
type TicketDetailRequest struct {
	ID string `path:"id"`
}
type TicketDetailResponse struct {
	Ticket
	Comments []Comment `json:"comments,omitempty"`
}
type TicketTransitionRequest struct {
	ID     string `path:"id"`
	Status string `json:"status"` // open, in_progress, resolved, closed
	Note   string `json:"note,optional"`
}
type TicketUpdateRequest struct {
	ID       string   `path:"id"`
	Title    string   `json:"title,optional"`
	Content  string   `json:"content,optional"`
	Category string   `json:"category,optional"`
	Priority string   `json:"priority,optional"`
	Assignee string   `json:"assignee,optional"`
	Tags     []string `json:"tags,optional"`
}
type TicketsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Status   string `form:"status,optional"`
	Category string `form:"category,optional"`
	Priority string `form:"priority,optional"`
	Assignee string `form:"assignee,optional"`
}
type TicketsListResponse struct {
	Items []Ticket `json:"items"`
	Total int64    `json:"total"`
	Page  int      `json:"page"`
	Size  int      `json:"pageSize"`
}
