// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import "encoding/json"

type AssignmentsQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
}

type AssignmentsResponse struct {
	Assignments map[string][]string `json:"assignments"`
}

type AssignmentsUpdateRequest struct {
	GameId    string   `json:"game_id"`
	Env       string   `json:"env"`
	Functions []string `json:"functions"`
}

type AssignmentsUpdateResponse struct {
	Ok      bool     `json:"ok"`
	Unknown []string `json:"unknown"`
}

type AnalyticsFiltersQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsFiltersResponse struct {
	Events          []string `json:"events"`
	PaymentsEnabled bool     `json:"payments_enabled"`
	SampleGlobal    int      `json:"sample_global"`
}

type AnalyticsFiltersUpdateRequest struct {
	GameId          string   `json:"game_id"`
	Env             string   `json:"env"`
	Events          []string `json:"events"`
	PaymentsEnabled *bool    `json:"payments_enabled,optional"`
	SampleGlobal    *int     `json:"sample_global,optional"`
}

type AnalyticsFiltersUpdateResponse struct {
	Ok bool `json:"ok"`
}

type AnalyticsOverviewQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
	Start  string `form:"start,optional"`
	End    string `form:"end,optional"`
}

type AnalyticsOverviewSeries struct {
	NewUsers     [][]any `json:"new_users"`
	PeakOnline   [][]any `json:"peak_online"`
	RevenueCents [][]any `json:"revenue_cents"`
}

type AnalyticsOverviewResponse struct {
	Dau          uint64                  `json:"dau"`
	Wau          uint64                  `json:"wau"`
	Mau          uint64                  `json:"mau"`
	NewUsers     uint64                  `json:"new_users"`
	RevenueCents uint64                  `json:"revenue_cents"`
	PayRate      float64                 `json:"pay_rate"`
	Arpu         float64                 `json:"arpu"`
	Arppu        float64                 `json:"arppu"`
	D1           float64                 `json:"d1"`
	D7           float64                 `json:"d7"`
	D30          float64                 `json:"d30"`
	Series       AnalyticsOverviewSeries `json:"series"`
}

type AnalyticsRealtimeQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsRealtimeResponse struct {
	Online            uint64  `json:"online"`
	Active1m          uint64  `json:"active_1m"`
	Active5m          uint64  `json:"active_5m"`
	Active15m         uint64  `json:"active_15m"`
	Rev5m             uint64  `json:"rev_5m"`
	RevToday          uint64  `json:"rev_today"`
	Rev5mYuan         string  `json:"rev_5m_yuan"`
	RevTodayYuan      string  `json:"rev_today_yuan"`
	PaySuccRate       float64 `json:"pay_succ_rate"`
	RegisteredTotal   uint64  `json:"registered_total"`
	OnlinePeakToday   uint64  `json:"online_peak_today"`
	OnlinePeakAllTime uint64  `json:"online_peak_all_time"`
	DauToday          uint64  `json:"dau_today"`
	NewToday          uint64  `json:"new_today"`
}

type AnalyticsRealtimeSeriesQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
	Start  string `form:"start"`
	End    string `form:"end"`
}

type AnalyticsRealtimeSeriesResponse struct {
	Online       [][]any `json:"online"`
	Active5mSum  [][]any `json:"active_5m_sum"`
	Active15mSum [][]any `json:"active_15m_sum"`
	RevenueCents [][]any `json:"revenue_cents"`
}

type AnalyticsBehaviorEventsQuery struct {
	GameId  string `form:"game_id,optional"`
	Env     string `form:"env,optional"`
	Event   string `form:"event,optional"`
	PropKey string `form:"prop_key,optional"`
	PropVal string `form:"prop_val,optional"`
	Start   string `form:"start,optional"`
	End     string `form:"end,optional"`
	Page    int    `form:"page,optional"`
	Size    int    `form:"size,optional"`
}

type AnalyticsBehaviorEvent struct {
	Time   string `json:"time"`
	Event  string `json:"event"`
	UserId string `json:"user_id"`
}

type AnalyticsBehaviorEventsResponse struct {
	Events []AnalyticsBehaviorEvent `json:"events"`
	Total  uint64                   `json:"total"`
}

type AnalyticsBehaviorFunnelQuery struct {
	GameId      string `form:"game_id,optional"`
	Env         string `form:"env,optional"`
	Steps       string `form:"steps"`
	Start       string `form:"start,optional"`
	End         string `form:"end,optional"`
	Sequential  string `form:"sequential,optional"`
	SameSession string `form:"same_session,optional"`
	GapSec      int    `form:"gap_sec,optional"`
	MaxUsers    int    `form:"max_users,optional"`
}

type AnalyticsBehaviorFunnelStep struct {
	Step  string  `json:"step"`
	Users uint64  `json:"users"`
	Rate  float64 `json:"rate"`
}

type AnalyticsBehaviorFunnelResponse struct {
	Steps []AnalyticsBehaviorFunnelStep `json:"steps"`
}

type AnalyticsBehaviorPathsQuery struct {
	GameId      string `form:"game_id,optional"`
	Env         string `form:"env,optional"`
	Per         string `form:"per,optional"`
	Steps       int    `form:"steps,optional"`
	Limit       int    `form:"limit,optional"`
	Include     string `form:"include,optional"`
	Exclude     string `form:"exclude,optional"`
	SameSession string `form:"same_session,optional"`
	GapSec      int    `form:"gap_sec,optional"`
	MaxGroups   int    `form:"max_groups,optional"`
	PathRe      string `form:"path_re,optional"`
	PathNotRe   string `form:"path_not_re,optional"`
	Start       string `form:"start,optional"`
	End         string `form:"end,optional"`
}

type AnalyticsBehaviorPath struct {
	Path   string `json:"path"`
	Groups uint64 `json:"groups"`
}

type AnalyticsBehaviorPathsResponse struct {
	Paths []AnalyticsBehaviorPath `json:"paths"`
}

type AnalyticsBehaviorAdoptionQuery struct {
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	Per      string `form:"per,optional"`
	Features string `form:"features"`
	Start    string `form:"start,optional"`
	End      string `form:"end,optional"`
}

type AnalyticsBehaviorAdoptionFeature struct {
	Feature string  `json:"feature"`
	Groups  uint64  `json:"groups"`
	Rate    float64 `json:"rate"`
}

type AnalyticsBehaviorAdoptionResponse struct {
	Features []AnalyticsBehaviorAdoptionFeature `json:"features"`
	Baseline uint64                             `json:"baseline"`
}

type AnalyticsBehaviorAdoptionBreakdownQuery struct {
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	Per      string `form:"per,optional"`
	Features string `form:"features"`
	By       string `form:"by,optional"`
	Start    string `form:"start,optional"`
	End      string `form:"end,optional"`
}

type AnalyticsBehaviorAdoptionBreakdownRow struct {
	Dim      string  `json:"dim"`
	Baseline uint64  `json:"baseline"`
	Groups   uint64  `json:"groups"`
	Rate     float64 `json:"rate"`
}

type AnalyticsBehaviorAdoptionBreakdownResponse struct {
	By   string                                  `json:"by"`
	Rows []AnalyticsBehaviorAdoptionBreakdownRow `json:"rows"`
}

type AnalyticsIngestRequest struct {
	Events []map[string]interface{} `json:"events"`
}

type AnalyticsPaymentsIngestRequest struct {
	Events []map[string]interface{} `json:"events"`
}

type MeProfileResponse struct {
	Username    string   `json:"username"`
	DisplayName string   `json:"display_name"`
	Email       string   `json:"email"`
	Phone       string   `json:"phone"`
	Active      bool     `json:"active"`
	Roles       []string `json:"roles"`
}

type MeGame struct {
	Id          uint         `json:"id"`
	Name        string       `json:"name"`
	AliasName   string       `json:"alias_name"`
	Status      string       `json:"status"`
	Enabled     bool         `json:"enabled"`
	Description string       `json:"description"`
	Icon        string       `json:"icon"`
	Homepage    string       `json:"homepage"`
	Envs        []string     `json:"envs"`
	GameEnvs    []MeGameEnv  `json:"game_envs"`
}

type MeGameEnv struct {
	Env         string `json:"env"`
	Description string `json:"description"`
	ApiBase     string `json:"api_base"`
	Color       string `json:"color"`
}

type MeGamesResponse struct {
	Games []MeGame `json:"games"`
}

type MeProfileUpdateRequest struct {
	DisplayName string `json:"display_name,optional"`
	Email       string `json:"email,optional"`
	Phone       string `json:"phone,optional"`
}

type MePasswordRequest struct {
	Current  string `json:"current"`
	Password string `json:"password"`
	OldPassword string `json:"old_password,optional"`
	NewPassword string `json:"new_password,optional"`
}

type AnalyticsPaymentsSummaryQuery struct {
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	Channel  string `form:"channel,optional"`
	Platform string `form:"platform,optional"`
	Country  string `form:"country,optional"`
	Region   string `form:"region,optional"`
	City     string `form:"city,optional"`
	Start    string `form:"start,optional"`
	End      string `form:"end,optional"`
}

type AnalyticsPaymentsSummaryTotals struct {
	RevenueCents uint64  `json:"revenue_cents"`
	RefundsCents uint64  `json:"refunds_cents"`
	Failed       uint64  `json:"failed"`
	SuccessRate  float64 `json:"success_rate"`
}

type AnalyticsPaymentsSummaryItem struct {
	Channel      string  `json:"channel,omitempty"`
	Platform     string  `json:"platform,omitempty"`
	Country      string  `json:"country,omitempty"`
	Region       string  `json:"region,omitempty"`
	City         string  `json:"city,omitempty"`
	ProductId    string  `json:"product_id,omitempty"`
	RevenueCents uint64  `json:"revenue_cents"`
	Success      uint64  `json:"success"`
	Total        uint64  `json:"total"`
	SuccessRate  float64 `json:"success_rate"`
}

type AnalyticsPaymentsSummaryResponse struct {
	Totals     AnalyticsPaymentsSummaryTotals `json:"totals"`
	ByChannel  []AnalyticsPaymentsSummaryItem `json:"by_channel"`
	ByPlatform []AnalyticsPaymentsSummaryItem `json:"by_platform"`
	ByCountry  []AnalyticsPaymentsSummaryItem `json:"by_country"`
	ByRegion   []AnalyticsPaymentsSummaryItem `json:"by_region"`
	ByCity     []AnalyticsPaymentsSummaryItem `json:"by_city"`
	ByProduct  []AnalyticsPaymentsSummaryItem `json:"by_product"`
}

type AnalyticsPaymentsTransactionsQuery struct {
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	Channel  string `form:"channel,optional"`
	Platform string `form:"platform,optional"`
	Country  string `form:"country,optional"`
	Region   string `form:"region,optional"`
	City     string `form:"city,optional"`
	Status   string `form:"status,optional"`
	Start    string `form:"start,optional"`
	End      string `form:"end,optional"`
	Page     int    `form:"page,optional"`
	Size     int    `form:"size,optional"`
}

type AnalyticsPaymentsTransaction struct {
	Time        string `json:"time"`
	OrderId     string `json:"order_id"`
	UserId      string `json:"user_id"`
	AmountCents uint64 `json:"amount_cents"`
	Status      string `json:"status"`
	Channel     string `json:"channel"`
}

type AnalyticsPaymentsTransactionsResponse struct {
	Transactions []AnalyticsPaymentsTransaction `json:"transactions"`
	Total        uint64                         `json:"total"`
}

type AnalyticsPaymentsProductTrendQuery struct {
	GameId      string `form:"game_id,optional"`
	Env         string `form:"env,optional"`
	Channel     string `form:"channel,optional"`
	Platform    string `form:"platform,optional"`
	Country     string `form:"country,optional"`
	Region      string `form:"region,optional"`
	City        string `form:"city,optional"`
	ProductId   string `form:"product_id"`
	Granularity string `form:"granularity,optional"`
	Start       string `form:"start"`
	End         string `form:"end"`
}

type AnalyticsPaymentsProductTrendPoint struct {
	Time         string `json:"time"`
	Success      uint64 `json:"success"`
	Total        uint64 `json:"total"`
	RevenueCents uint64 `json:"revenue_cents"`
}

type AnalyticsPaymentsProductTrend struct {
	ProductId string                               `json:"product_id"`
	Points    []AnalyticsPaymentsProductTrendPoint `json:"points"`
}

type AnalyticsPaymentsProductTrendResponse struct {
	Products []AnalyticsPaymentsProductTrend `json:"products"`
}

type AnalyticsLevelsQuery struct {
	GameId  string `form:"game_id,optional"`
	Env     string `form:"env,optional"`
	Episode string `form:"episode,optional"`
	Start   string `form:"start,optional"`
	End     string `form:"end,optional"`
}

type AnalyticsLevelsFunnelStep struct {
	Step  string  `json:"step"`
	Users uint64  `json:"users"`
	Rate  float64 `json:"rate"`
}

type AnalyticsLevelsPerLevel struct {
	Level          string  `json:"level"`
	Players        uint64  `json:"players"`
	WinRate        float64 `json:"win_rate"`
	AvgDurationSec float64 `json:"avg_duration_sec"`
	AvgRetries     float64 `json:"avg_retries"`
	Difficulty     string  `json:"difficulty"`
}

type AnalyticsLevelsSegmentEntry struct {
	Level   string  `json:"level"`
	Players uint64  `json:"players"`
	WinRate float64 `json:"win_rate"`
}

type AnalyticsLevelsSegments struct {
	New       []AnalyticsLevelsSegmentEntry `json:"new"`
	Payer     []AnalyticsLevelsSegmentEntry `json:"payer"`
	Returning []AnalyticsLevelsSegmentEntry `json:"returning"`
}

type AnalyticsLevelsResponse struct {
	Funnel           []AnalyticsLevelsFunnelStep `json:"funnel"`
	PerLevel         []AnalyticsLevelsPerLevel   `json:"per_level"`
	PerLevelSegments AnalyticsLevelsSegments     `json:"per_level_segments"`
}

type AnalyticsLevelsEpisodesQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
	Start  string `form:"start,optional"`
	End    string `form:"end,optional"`
}

type AnalyticsLevelsPerLevelSummary struct {
	Level   string  `json:"level"`
	Players uint64  `json:"players"`
	WinRate float64 `json:"win_rate"`
}

type AnalyticsLevelsEpisode struct {
	Episode  string                           `json:"episode"`
	PerLevel []AnalyticsLevelsPerLevelSummary `json:"per_level"`
}

type AnalyticsLevelsEpisodesResponse struct {
	Episodes []AnalyticsLevelsEpisode `json:"episodes"`
}

type AnalyticsLevelsMap struct {
	Map      string                           `json:"map"`
	PerLevel []AnalyticsLevelsPerLevelSummary `json:"per_level"`
}

type AnalyticsLevelsMapsResponse struct {
	Maps []AnalyticsLevelsMap `json:"maps"`
}

type AnalyticsRetentionQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
	Cohort string `form:"cohort,optional"`
	Start  string `form:"start,optional"`
	End    string `form:"end,optional"`
}

type AnalyticsRetentionCohort struct {
	Day string  `json:"day"`
	D1  float64 `json:"d1"`
	D7  float64 `json:"d7"`
	D30 float64 `json:"d30"`
}

type AnalyticsRetentionResponse struct {
	Cohorts []AnalyticsRetentionCohort `json:"cohorts"`
}

type OpsService struct {
	AgentId        string            `json:"agent_id"`
	GameId         string            `json:"game_id"`
	Env            string            `json:"env"`
	RpcAddr        string            `json:"rpc_addr"`
	Ip             string            `json:"ip"`
	Region         string            `json:"region"`
	Zone           string            `json:"zone"`
	Labels         map[string]string `json:"labels"`
	Type           string            `json:"type"`
	Version        string            `json:"version"`
	Functions      int               `json:"functions"`
	Healthy        bool              `json:"healthy"`
	ExpiresInSec   int               `json:"expires_in_sec"`
	ActiveConns    int64             `json:"active_conns"`
	TotalRequests  int64             `json:"total_requests"`
	FailedRequests int64             `json:"failed_requests"`
	ErrorRate      float64           `json:"error_rate"`
	AvgLatencyMs   int64             `json:"avg_latency_ms"`
	LastSeen       string            `json:"last_seen"`
	Qps1m          float64           `json:"qps_1m"`
	QpsLimit       int               `json:"qps_limit"`
}

type OpsServicesResponse struct {
	Services []OpsService `json:"services"`
}

type OpsAgentMetaUpdateRequest struct {
	Id     string            `path:"id"`
	Region string            `json:"region,optional"`
	Zone   string            `json:"zone,optional"`
	Labels map[string]string `json:"labels,optional"`
}

type AgentMetaReportRequest struct {
	AgentId string            `json:"agent_id"`
	Region  string            `json:"region,optional"`
	Zone    string            `json:"zone,optional"`
	Labels  map[string]string `json:"labels,optional"`
}

type GenericOkResponse struct {
	Ok bool `json:"ok"`
}

type HealthCheck struct {
	Id          string `json:"id"`
	Kind        string `json:"kind"`
	Target      string `json:"target"`
	Expect      string `json:"expect,optional"`
	IntervalSec int    `json:"interval_sec,optional"`
	TimeoutMs   int    `json:"timeout_ms,optional"`
	Region      string `json:"region,optional"`
}

type HealthStatus struct {
	Id        string `json:"id"`
	Ok        bool   `json:"ok"`
	LatencyMs int64  `json:"latency_ms"`
	Error     string `json:"error,optional"`
	CheckedAt string `json:"checked_at"`
}

type OpsHealthResponse struct {
	Checks []HealthCheck  `json:"checks"`
	Status []HealthStatus `json:"status"`
}

type OpsHealthUpdateRequest struct {
	Checks []HealthCheck `json:"checks"`
}

type OpsHealthRunRequest struct {
	Id string `form:"id,optional"`
}

type RateLimitRule struct {
	Scope    string            `json:"scope"`
	Key      string            `json:"key"`
	LimitQPS int               `json:"limit_qps"`
	Match    map[string]string `json:"match,optional"`
	Percent  int               `json:"percent,optional"`
}

type RateLimitRulesResponse struct {
	Rules []RateLimitRule `json:"rules"`
}

type RateLimitRulesRequest struct {
	Rules []RateLimitRule `json:"rules"`
}

type RateLimitDeleteRequest struct {
	Scope string `form:"scope"`
	Key   string `form:"key"`
}

type RateLimitPreviewQuery struct {
	Scope       string `form:"scope"`
	Key         string `form:"key,optional"`
	LimitQPS    int    `form:"limit_qps,optional"`
	Percent     int    `form:"percent,optional"`
	MatchGameId string `form:"match_game_id,optional"`
	MatchEnv    string `form:"match_env,optional"`
	MatchRegion string `form:"match_region,optional"`
	MatchZone   string `form:"match_zone,optional"`
}

type RateLimitPreviewAgent struct {
	AgentId string  `json:"agent_id"`
	GameId  string  `json:"game_id"`
	Env     string  `json:"env"`
	Region  string  `json:"region"`
	Zone    string  `json:"zone"`
	RpcAddr string  `json:"rpc_addr"`
	Qps     int     `json:"qps"`
	Qps1m   float64 `json:"qps_1m"`
}

type RateLimitPreviewResponse struct {
	Matched int                     `json:"matched"`
	Agents  []RateLimitPreviewAgent `json:"agents"`
}

type OpsMQResponse struct {
	Type    string           `json:"type"`
	Redis   *OpsMQRedis      `json:"redis,optional"`
	Kafka   *OpsMQKafka      `json:"kafka,optional"`
	Lengths map[string]int64 `json:"lengths,optional"`
	Groups  []OpsMQGroup     `json:"groups,optional"`
}

type OpsMQRedis struct {
	URL     string            `json:"url"`
	Streams map[string]string `json:"streams"`
}

type OpsMQKafka struct {
	Brokers string            `json:"brokers"`
	Topics  map[string]string `json:"topics"`
}

type OpsMQGroup struct {
	Stream      string `json:"stream"`
	Name        string `json:"name"`
	Consumers   int64  `json:"consumers"`
	Pending     int64  `json:"pending"`
	EntriesRead int64  `json:"entries_read"`
	Lag         int64  `json:"lag"`
}

type OpsFunction struct {
	Id       string `json:"id"`
	Category string `json:"category,omitempty"`
}

type OpsFunctionsResponse struct {
	Functions []OpsFunction `json:"functions"`
}

type OpsConfigResponse struct {
	AlertmanagerUrl   string `json:"alertmanager_url"`
	GrafanaExploreUrl string `json:"grafana_explore_url"`
}

type OpsMetricsQuery struct {
	Instance string `form:"instance,optional"`
	Range    string `form:"range,optional"`
	Step     string `form:"step,optional"`
}

type OpsMetricsResponse struct {
	Qps     [][]interface{} `json:"qps"`
	ErrRate [][]interface{} `json:"err_rate"`
	P95Ms   [][]interface{} `json:"p95_ms"`
}

type BackupEntry struct {
	Id        string `json:"id"`
	Kind      string `json:"kind"`
	Target    string `json:"target,optional"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
	Status    string `json:"status"`
	Error     string `json:"error,optional"`
	CreatedAt string `json:"created_at"`
}

type OpsBackupsResponse struct {
	Backups []BackupEntry `json:"backups"`
}

type OpsBackupCreateRequest struct {
	Kind   string `json:"kind"`
	Target string `json:"target,optional"`
}

type OpsBackupCreateResponse struct {
	Id string `json:"id"`
}

type ConfigsListQuery struct {
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
	Format string `form:"format,optional"`
	IdLike string `form:"id_like,optional"`
}

type ConfigListItem struct {
	Id            string `json:"id"`
	GameId        string `json:"game_id"`
	Env           string `json:"env"`
	Format        string `json:"format"`
	LatestVersion int    `json:"latest_version"`
}

type ConfigsListResponse struct {
	Items []ConfigListItem `json:"items"`
}

type ConfigDetailRequest struct {
	Id     string `path:"id"`
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
}

type ConfigDetailResponse struct {
	Id      string `json:"id"`
	GameId  string `json:"game_id"`
	Env     string `json:"env"`
	Format  string `json:"format"`
	Version int    `json:"version"`
	Content string `json:"content"`
}

type ConfigValidateRequest struct {
	Id      string `path:"id"`
	Format  string `json:"format"`
	Content string `json:"content"`
}

type ConfigValidateResponse struct {
	Valid  bool     `json:"valid"`
	Errors []string `json:"errors"`
}

type ConfigUpsertRequest struct {
	Id          string `path:"id"`
	GameId      string `json:"game_id"`
	Env         string `json:"env"`
	Format      string `json:"format"`
	Content     string `json:"content"`
	Message     string `json:"message,omitempty"`
	BaseVersion int    `json:"base_version,omitempty"`
}

type ConfigUpsertResponse struct {
	Ok      bool   `json:"ok"`
	Version int    `json:"version"`
	Etag    string `json:"etag"`
}

type ConfigVersionsRequest struct {
	Id     string `path:"id"`
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
}

type ConfigVersionItem struct {
	Version   int    `json:"version"`
	Message   string `json:"message"`
	Editor    string `json:"editor"`
	CreatedAt string `json:"created_at"`
	Size      int    `json:"size"`
	Etag      string `json:"etag"`
}

type ConfigVersionsResponse struct {
	Versions []ConfigVersionItem `json:"versions"`
}

type ConfigVersionDetailRequest struct {
	Id     string `path:"id"`
	Ver    int    `path:"ver"`
	GameId string `form:"game_id,optional"`
	Env    string `form:"env,optional"`
}

type ConfigVersionDetailResponse struct {
	Version int    `json:"version"`
	Content string `json:"content"`
}

type GameInfo struct {
	Id          int64         `json:"id"`
	Name        string        `json:"name"`
	Icon        string        `json:"icon"`
	Description string        `json:"description"`
	Enabled     bool          `json:"enabled"`
	AliasName   string        `json:"alias_name"`
	Homepage    string        `json:"homepage"`
	Status      string        `json:"status"`
	GameType    string        `json:"game_type"`
	GenreCode   string        `json:"genre_code"`
	Envs        []string      `json:"envs"`
	GameEnvs    []GameEnvItem `json:"game_envs"`
	CreatedAt   string        `json:"created_at"`
	UpdatedAt   string        `json:"updated_at"`
}

type GamesListResponse struct {
	Games []GameInfo `json:"games"`
}

type GameUpsertRequest struct {
	Id          int64  `json:"id,omitempty"`
	Name        string `json:"name"`
	Icon        string `json:"icon,omitempty"`
	Description string `json:"description,omitempty"`
	Enabled     bool   `json:"enabled"`
	Status      string `json:"status,omitempty"`
	AliasName   string `json:"alias_name,omitempty"`
	Homepage    string `json:"homepage,omitempty"`
	GameType    string `json:"game_type,omitempty"`
	GenreCode   string `json:"genre_code,omitempty"`
}

type GameUpsertResponse struct {
	Id int64 `json:"id"`
}

type GameUpdateRequest struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,omitempty"`
	Icon        string `json:"icon,omitempty"`
	Description string `json:"description,omitempty"`
	Enabled     bool   `json:"enabled"`
	Status      string `json:"status,omitempty"`
	AliasName   string `json:"alias_name,omitempty"`
	Homepage    string `json:"homepage,omitempty"`
	GameType    string `json:"game_type,omitempty"`
	GenreCode   string `json:"genre_code,omitempty"`
}

type GameDetailRequest struct {
	Id int64 `path:"id"`
}

type GameDetailResponse struct {
	Game GameInfo `json:"game"`
}

type GameEnvItem struct {
	Env         string `json:"env"`
	Description string `json:"description,omitempty"`
	Color       string `json:"color,omitempty"`
}

type GameEnvsResponse struct {
	Envs []GameEnvItem `json:"envs"`
}

type GameEnvAddRequest struct {
	Id          int64  `path:"id"`
	Env         string `json:"env"`
	Description string `json:"description,omitempty"`
	Color       string `json:"color,omitempty"`
}

type GameEnvUpdateRequest struct {
	Id          int64  `path:"id"`
	OldEnv      string `json:"old_env"`
	Env         string `json:"env"`
	Description string `json:"description,omitempty"`
	Color       string `json:"color,omitempty"`
}

type GameEnvDeleteRequest struct {
	Id  int64  `path:"id"`
	Env string `form:"env"`
}

type SupportTicket struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Category  string `json:"category"`
	Priority  string `json:"priority"`
	Status    string `json:"status"`
	Assignee  string `json:"assignee"`
	Tags      string `json:"tags"`
	PlayerId  string `json:"player_id"`
	Contact   string `json:"contact"`
	GameId    string `json:"game_id"`
	Env       string `json:"env"`
	Source    string `json:"source"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SupportTicketsQuery struct {
	Q        string `form:"q,optional"`
	Status   string `form:"status,optional"`
	Priority string `form:"priority,optional"`
	Category string `form:"category,optional"`
	Assignee string `form:"assignee,optional"`
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	Page     int    `form:"page,optional"`
	Size     int    `form:"size,optional"`
}

type SupportTicketsResponse struct {
	Tickets []SupportTicket `json:"tickets"`
	Total   int64           `json:"total"`
	Page    int             `json:"page"`
	Size    int             `json:"size"`
}

type SupportTicketCreateRequest struct {
	Title    string `json:"title"`
	Content  string `json:"content,optional"`
	Category string `json:"category,optional"`
	Priority string `json:"priority,optional"`
	Status   string `json:"status,optional"`
	Assignee string `json:"assignee,optional"`
	Tags     string `json:"tags,optional"`
	PlayerId string `json:"player_id,optional"`
	Contact  string `json:"contact,optional"`
	GameId   string `json:"game_id,optional"`
	Env      string `json:"env,optional"`
	Source   string `json:"source,optional"`
}

type SupportTicketUpdateRequest struct {
	Id       int64  `path:"id"`
	Title    string `json:"title,optional"`
	Content  string `json:"content,optional"`
	Category string `json:"category,optional"`
	Priority string `json:"priority,optional"`
	Status   string `json:"status,optional"`
	Assignee string `json:"assignee,optional"`
	Tags     string `json:"tags,optional"`
	PlayerId string `json:"player_id,optional"`
	Contact  string `json:"contact,optional"`
	GameId   string `json:"game_id,optional"`
	Env      string `json:"env,optional"`
	Source   string `json:"source,optional"`
}

type SupportTicketResponse struct {
	Ticket SupportTicket `json:"ticket"`
}

type SupportTicketCreateResponse struct {
	Id int64 `json:"id"`
}

type SupportComment struct {
	Id        int64  `json:"id"`
	Author    string `json:"author"`
	Content   string `json:"content"`
	Attach    string `json:"attach"`
	CreatedAt string `json:"created_at"`
}

type SupportCommentsResponse struct {
	Comments []SupportComment `json:"comments"`
}

type SupportCommentCreateRequest struct {
	Id      int64  `path:"id"`
	Content string `json:"content"`
	Attach  string `json:"attach,optional"`
}

type SupportCommentCreateResponse struct {
	Id int64 `json:"id"`
}

type SupportTicketTransitionRequest struct {
	Id      int64  `path:"id"`
	Status  string `json:"status"`
	Comment string `json:"comment,optional"`
}

type SupportFAQ struct {
	Id        int64  `json:"id"`
	Question  string `json:"question"`
	Answer    string `json:"answer"`
	Category  string `json:"category"`
	Tags      string `json:"tags"`
	Visible   bool   `json:"visible"`
	Sort      int    `json:"sort"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SupportFAQQuery struct {
	Q        string `form:"q,optional"`
	Category string `form:"category,optional"`
	Visible  string `form:"visible,optional"`
}

type SupportFAQListResponse struct {
	Faq []SupportFAQ `json:"faq"`
}

type SupportFAQCreateRequest struct {
	Question string `json:"question"`
	Answer   string `json:"answer,optional"`
	Category string `json:"category,optional"`
	Tags     string `json:"tags,optional"`
	Visible  *bool  `json:"visible,optional"`
	Sort     *int   `json:"sort,optional"`
}

type SupportFAQUpdateRequest struct {
	Id       int64  `path:"id"`
	Question string `json:"question,optional"`
	Answer   string `json:"answer,optional"`
	Category string `json:"category,optional"`
	Tags     string `json:"tags,optional"`
	Visible  *bool  `json:"visible,optional"`
	Sort     *int   `json:"sort,optional"`
}

type SupportFAQDeleteRequest struct {
	Id int64 `path:"id"`
}

type SupportFAQCreateResponse struct {
	Id int64 `json:"id"`
}

type SupportFeedback struct {
	Id        int64  `json:"id"`
	PlayerId  string `json:"player_id"`
	Contact   string `json:"contact"`
	Content   string `json:"content"`
	Category  string `json:"category"`
	Priority  string `json:"priority"`
	Status    string `json:"status"`
	Attach    string `json:"attach"`
	GameId    string `json:"game_id"`
	Env       string `json:"env"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SupportFeedbackQuery struct {
	Q        string `form:"q,optional"`
	Category string `form:"category,optional"`
	Status   string `form:"status,optional"`
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	Page     int    `form:"page,optional"`
	Size     int    `form:"size,optional"`
}

type SupportFeedbackListResponse struct {
	Feedback []SupportFeedback `json:"feedback"`
	Total    int64             `json:"total"`
	Page     int               `json:"page"`
	Size     int               `json:"size"`
}

type SupportFeedbackCreateRequest struct {
	PlayerId string `json:"player_id,optional"`
	Contact  string `json:"contact,optional"`
	Content  string `json:"content"`
	Category string `json:"category,optional"`
	Priority string `json:"priority,optional"`
	Status   string `json:"status,optional"`
	Attach   string `json:"attach,optional"`
	GameId   string `json:"game_id,optional"`
	Env      string `json:"env,optional"`
}

type SupportFeedbackUpdateRequest struct {
	Id       int64  `path:"id"`
	Category string `json:"category,optional"`
	Priority string `json:"priority,optional"`
	Status   string `json:"status,optional"`
	Attach   string `json:"attach,optional"`
}

type SupportFeedbackDeleteRequest struct {
	Id int64 `path:"id"`
}

type SupportFeedbackCreateResponse struct {
	Id int64 `json:"id"`
}

type AuthLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthUserInfo struct {
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type AuthLoginResponse struct {
	Token string       `json:"token"`
	User  AuthUserInfo `json:"user"`
}

type AuthMeResponse struct {
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type UploadResponse struct {
	Key string `json:"Key"`
	Url string `json:"URL"`
}

type OpsNotificationChannel struct {
	Id       string `json:"id"`
	Type     string `json:"type"`
	Url      string `json:"url"`
	Secret   string `json:"secret,omitempty"`
	Provider string `json:"provider,omitempty"`
	Account  string `json:"account,omitempty"`
	From     string `json:"from,omitempty"`
	To       string `json:"to,omitempty"`
}

type OpsNotificationRule struct {
	Event         string   `json:"event"`
	Channels      []string `json:"channels"`
	ThresholdDays int      `json:"threshold_days,omitempty"`
}

type OpsNotificationsResponse struct {
	Channels []OpsNotificationChannel `json:"channels"`
	Rules    []OpsNotificationRule    `json:"rules"`
}

type OpsNotificationsUpdateRequest struct {
	Channels []OpsNotificationChannel `json:"channels"`
	Rules    []OpsNotificationRule    `json:"rules"`
}

type OpsNode struct {
	Id           string            `json:"id"`
	Type         string            `json:"type"`
	GameId       string            `json:"game_id,omitempty"`
	Env          string            `json:"env,omitempty"`
	Addr         string            `json:"addr"`
	HttpAddr     string            `json:"http_addr,omitempty"`
	Ip           string            `json:"ip"`
	Version      string            `json:"version"`
	Region       string            `json:"region,omitempty"`
	Zone         string            `json:"zone,omitempty"`
	Healthy      bool              `json:"healthy"`
	ExpiresInSec int               `json:"expires_in_sec,omitempty"`
	LastSeen     string            `json:"last_seen,omitempty"`
	Draining     bool              `json:"draining"`
	Labels       map[string]string `json:"labels,omitempty"`
}

type OpsNodesResponse struct {
	Nodes []OpsNode `json:"nodes"`
}

type OpsNodeActionRequest struct {
	Id string `path:"id"`
}

type OpsNodeMetaRequest struct {
	Type     string `json:"type"`
	Id       string `json:"id"`
	Addr     string `json:"addr"`
	HttpAddr string `json:"http_addr,omitempty"`
	Version  string `json:"version,omitempty"`
	Region   string `json:"region,omitempty"`
	Zone     string `json:"zone,omitempty"`
}

type OpsNodeCommandsQuery struct {
	NodeId string `form:"node_id"`
}

type OpsNodeCommandsResponse struct {
	Commands []string `json:"commands"`
}

type OpsMaintenanceWindow struct {
	Id          string `json:"id"`
	GameId      string `json:"game_id,omitempty"`
	Env         string `json:"env,omitempty"`
	Start       string `json:"start"`
	End         string `json:"end"`
	Message     string `json:"message,omitempty"`
	BlockWrites bool   `json:"block_writes,omitempty"`
}

type OpsMaintenanceResponse struct {
	Windows []OpsMaintenanceWindow `json:"windows"`
}

type OpsMaintenanceUpdateRequest struct {
	Windows []OpsMaintenanceWindow `json:"windows"`
}

type OpsStatusResponse struct {
	Maintenance []OpsMaintenanceWindow `json:"maintenance"`
}

type OpsJobsQuery struct {
	Status     string `form:"status,optional"`
	FunctionId string `form:"function_id,optional"`
	Actor      string `form:"actor,optional"`
	GameId     string `form:"game_id,optional"`
	Env        string `form:"env,optional"`
	Page       int    `form:"page,optional"`
	Size       int    `form:"size,optional"`
}

type OpsJob struct {
	Id         string `json:"id"`
	FunctionId string `json:"function_id"`
	Actor      string `json:"actor"`
	GameId     string `json:"game_id"`
	Env        string `json:"env"`
	State      string `json:"state"`
	StartedAt  string `json:"started_at"`
	EndedAt    string `json:"ended_at"`
	DurationMs int64  `json:"duration_ms"`
	Error      string `json:"error"`
	RpcAddr    string `json:"rpc_addr"`
	TraceId    string `json:"trace_id"`
}

type OpsJobsResponse struct {
	Jobs  []OpsJob `json:"jobs"`
	Total int      `json:"total"`
	Page  int      `json:"page"`
	Size  int      `json:"size"`
}

type OpsAlert struct {
	Labels      map[string]string `json:"labels"`
	Annotations map[string]string `json:"annotations"`
	Severity    string            `json:"severity"`
	Instance    string            `json:"instance"`
	Service     string            `json:"service"`
	Summary     string            `json:"summary"`
	StartsAt    string            `json:"starts_at"`
	EndsAt      string            `json:"ends_at"`
	Silenced    bool              `json:"silenced"`
	Duration    string            `json:"duration"`
}

type OpsAlertsResponse struct {
	Alerts []OpsAlert `json:"alerts"`
}

type OpsAlertSilenceRequest struct {
	Matchers map[string]string `json:"matchers"`
	Duration string            `json:"duration,omitempty"`
	Creator  string            `json:"creator,omitempty"`
	Comment  string            `json:"comment,omitempty"`
}

type OpsAlertSilenceDeleteRequest struct {
	Id string `path:"id"`
}

type OpsSilenceMatcher struct {
	Name    string `json:"name"`
	Value   string `json:"value"`
	IsRegex bool   `json:"is_regex"`
}

type OpsSilence struct {
	Id        string              `json:"id"`
	Matchers  []OpsSilenceMatcher `json:"matchers"`
	CreatedBy string              `json:"created_by"`
	Comment   string              `json:"comment"`
	StartsAt  string              `json:"starts_at"`
	EndsAt    string              `json:"ends_at"`
	Status    map[string]string   `json:"status"`
}

type OpsSilencesResponse struct {
	Silences []OpsSilence `json:"silences"`
}

type ComponentActionRequest struct {
	Id string `path:"id"`
}

type ComponentDetailRequest struct {
	Id string `path:"id"`
}

type ComponentDetailResponse struct {
	Id           string                  `json:"id"`
	Name         string                  `json:"name"`
	Version      string                  `json:"version"`
	Description  string                  `json:"description"`
	Category     string                  `json:"category"`
	Author       string                  `json:"author"`
	License      string                  `json:"license"`
	Dependencies []string                `json:"dependencies"`
	Functions    []ComponentFunctionInfo `json:"functions"`
	Files        map[string]int          `json:"files"`
	SizeBytes    int64                   `json:"size_bytes"`
	Enabled      bool                    `json:"enabled"`
}

type ComponentFunctionInfo struct {
	Id          string `json:"id"`
	Version     string `json:"version"`
	Enabled     bool   `json:"enabled"`
	Description string `json:"description"`
	Registered  bool   `json:"registered"`
	AgentsCount int64  `json:"agents_count"`
}

type ComponentPatchRequest struct {
	Id        string                            `path:"id"`
	Enabled   *bool                             `json:"enabled,optional"`
	Functions map[string]map[string]interface{} `json:"functions,optional"`
}

type ComponentPatchResponse struct {
	Ok      bool     `json:"ok"`
	Updated []string `json:"updated"`
}

type ComponentUploadResponse struct {
	Ok bool `json:"ok"`
}

type ComponentsListResponse struct {
	Components interface{} `json:"components"`
}

type ComponentsQuery struct {
	Category string `form:"category,optional"`
}

type EntitiesListResponse struct {
	Entities []interface{} `json:"entities"`
}

type EntityCreateRequest struct {
	Id        string                 `json:"id"`
	Type      string                 `json:"type"`
	Component string                 `json:"component"`
	Data      map[string]interface{} `json:"data,optional"`
	Schema    map[string]interface{} `json:"schema,optional"`
}

type EntityCreateResponse struct {
	Id      string `json:"id"`
	Created bool   `json:"created"`
}

type EntityDeleteRequest struct {
	Id string `path:"id"`
}

type EntityDeleteResponse struct {
	Id      string `json:"id"`
	Deleted bool   `json:"deleted"`
}

type EntityDetailRequest struct {
	Id string `path:"id"`
}

type EntityDetailResponse struct {
	Id        string                 `json:"id"`
	Component string                 `json:"component"`
	Data      map[string]interface{} `json:"data"`
}

type EntityPreviewRequest struct {
	Id string `path:"id"`
}

type EntityPreviewResponse struct {
	ProTable interface{} `json:"pro_table"`
	ProForm  interface{} `json:"pro_form"`
}

type EntityUpdateRequest struct {
	Id   string                 `path:"id"`
	Data map[string]interface{} `json:"data"`
}

type EntityUpdateResponse struct {
	Id      string `json:"id"`
	Updated bool   `json:"updated"`
}

type EntityValidateRequest struct {
	Definition map[string]interface{} `json:"definition"`
}

type EntityValidateResponse struct {
	Valid  bool          `json:"valid"`
	Errors []interface{} `json:"errors"`
}

type FunctionActionRequest struct {
	Id string `path:"id"`
}

type FunctionActionResponse struct {
	Ok         bool   `json:"ok"`
	Message    string `json:"message"`
	FunctionId string `json:"function_id"`
}

type FunctionAgentInfo struct {
	AgentId  string `json:"agent_id"`
	GameId   string `json:"game_id"`
	Env      string `json:"env"`
	RpcAddr  string `json:"rpc_addr"`
	Version  string `json:"version"`
	Enabled  bool   `json:"enabled"`
	LastSeen string `json:"last_seen"`
}

type FunctionDetail struct {
	Id       string `json:"id"`
	Version  string `json:"version,optional"`
	Category string `json:"category,optional"`
	Risk     string `json:"risk,optional"`
	Source   string `json:"source"`
}

type FunctionDetailRequest struct {
	Id string `path:"id"`
}

type FunctionDetailResponse struct {
	Function  *FunctionDetail        `json:"function"`
	Agents    []FunctionAgentInfo    `json:"agents"`
	Providers []FunctionProviderInfo `json:"providers"`
}

type FunctionInstance struct {
	AgentId   string `json:"agent_id"`
	ServiceId string `json:"service_id"`
	Addr      string `json:"addr"`
	Version   string `json:"version"`
}

type FunctionInstancesRequest struct {
	GameId     string `form:"game_id,optional"`
	FunctionId string `form:"function_id,optional"`
}

type FunctionInstancesResponse struct {
	Instances []FunctionInstance `json:"instances"`
}

type FunctionProviderInfo struct {
	ProviderId string `json:"provider_id"`
	Version    string `json:"version,optional"`
	Category   string `json:"category,optional"`
	Risk       string `json:"risk,optional"`
	UpdatedAt  string `json:"updated_at,optional"`
}

type FunctionRecord struct {
	Id         string `json:"id"`
	Enabled    bool   `json:"enabled"`
	Source     string `json:"source"`
	SourceId   string `json:"source_id"`
	AgentId    string `json:"agent_id,optional"`
	ProviderId string `json:"provider_id,optional"`
	GameId     string `json:"game_id,optional"`
	Env        string `json:"env,optional"`
	RpcAddr    string `json:"rpc_addr,optional"`
	Version    string `json:"version,optional"`
	Category   string `json:"category,optional"`
	Risk       string `json:"risk,optional"`
	UpdatedAt  string `json:"updated_at,optional"`
	LastSeen   string `json:"last_seen,optional"`
}

type FunctionsListResponse struct {
	Functions []FunctionRecord `json:"functions"`
	Total     int64            `json:"total"`
}

type FunctionsQuery struct {
	GameId   string `form:"game_id,optional"`
	Env      string `form:"env,optional"`
	AgentId  string `form:"agent_id,optional"`
	Category string `form:"category,optional"`
	Enabled  string `form:"enabled,optional"`
}

type PacksImportResponse struct {
	Ok bool `json:"ok"`
}

type PacksListResponse struct {
	Manifest           interface{} `json:"manifest"`
	Counts             interface{} `json:"counts"`
	Etag               string      `json:"etag"`
	ExportAuthRequired bool        `json:"export_auth_required"`
}

type PacksReloadResponse struct {
	Ok bool `json:"ok"`
}

type ProviderActionRequest struct {
	Id string `path:"id"`
}

type ProviderDeleteResponse struct {
	Ok         bool   `json:"ok"`
	Message    string `json:"message"`
	ProviderId string `json:"provider_id"`
	Note       string `json:"note"`
}

type ProviderDetailRequest struct {
	Id string `path:"id"`
}

type ProviderInfo struct {
	Id             string      `json:"id"`
	Version        string      `json:"version"`
	Lang           string      `json:"lang"`
	Sdk            string      `json:"sdk"`
	UpdatedAt      string      `json:"updated_at"`
	FunctionsCount int64       `json:"functions_count"`
	EntitiesCount  int64       `json:"entities_count"`
	Manifest       interface{} `json:"manifest,optional"`
	Functions      interface{} `json:"functions,optional"`
	Entities       interface{} `json:"entities,optional"`
	Operations     interface{} `json:"operations,optional"`
}

type ProviderReloadResponse struct {
	Ok         bool   `json:"ok"`
	Message    string `json:"message"`
	ProviderId string `json:"provider_id"`
	Note       string `json:"note"`
}

type ProvidersCapabilitiesRequest struct {
	Provider struct {
		Id      string `json:"id"`
		Version string `json:"version,optional"`
		Lang    string `json:"lang,optional"`
		Sdk     string `json:"sdk,optional"`
	} `json:"provider"`
	Manifest json.RawMessage `json:"manifest_json"`
}

type ProvidersCapabilitiesResponse struct {
	Ok bool `json:"ok"`
}

type ProvidersDescriptorsResponse struct {
	Providers []ProviderDescriptor `json:"providers"`
}

type ProvidersEntitiesResponse struct {
	Providers []ProviderEntitySet `json:"providers"`
}

type ProviderDescriptor struct {
	Id        string      `json:"id"`
	Version   string      `json:"version"`
	Lang      string      `json:"lang"`
	Sdk       string      `json:"sdk"`
	Manifest  interface{} `json:"manifest"`
	UpdatedAt string      `json:"updated_at"`
}

type ProviderEntitySet struct {
	Provider ProviderReference `json:"provider"`
	Entities []interface{}     `json:"entities"`
}

type ProviderReference struct {
	Id      string `json:"id"`
	Version string `json:"version"`
}

type ProvidersListResponse struct {
	Providers []ProviderInfo `json:"providers"`
	Total     int64          `json:"total"`
}

type DescriptorsQuery struct {
	Detailed bool `form:"detailed,optional"`
}

type DescriptorsResponse struct {
	Descriptors       interface{} `json:"descriptors,omitempty"`
	LegacyDescriptors interface{} `json:"legacy_descriptors,omitempty"`
	ProviderManifests interface{} `json:"provider_manifests,omitempty"`
}

type RegistryAgent struct {
	AgentId      string `json:"agent_id"`
	GameId       string `json:"game_id"`
	Env          string `json:"env"`
	RpcAddr      string `json:"rpc_addr"`
	Ip           string `json:"ip"`
	Type         string `json:"type"`
	Version      string `json:"version"`
	Functions    int64  `json:"functions"`
	Healthy      bool   `json:"healthy"`
	ExpiresInSec int64  `json:"expires_in_sec"`
}

type RegistryCoverage struct {
	GameEnv   string                          `json:"game_env"`
	Functions map[string]RegistryFuncCoverage `json:"functions"`
	Uncovered []string                        `json:"uncovered"`
}

type RegistryFuncCoverage struct {
	Healthy int64 `json:"healthy"`
	Total   int64 `json:"total"`
}

type RegistryFunction struct {
	GameId string `json:"game_id"`
	Id     string `json:"id"`
	Agents int64  `json:"agents"`
}

type RegistryResponse struct {
	Agents      []RegistryAgent     `json:"agents"`
	Functions   []RegistryFunction  `json:"functions"`
	Assignments map[string][]string `json:"assignments"`
	Coverage    []RegistryCoverage  `json:"coverage"`
}

type SchemaCreateRequest struct {
	Id          string                 `json:"id"`
	Schema      map[string]interface{} `json:"schema"`
	UIConfig    interface{}            `json:"ui_config,optional"`
	Description string                 `json:"description,optional"`
	Category    string                 `json:"category,optional"`
	Type        string                 `json:"type,optional"`
}

type SchemaCreateResponse struct {
	Id string `json:"id"`
	Ok bool   `json:"ok"`
}

type SchemaUpdateRequest struct {
	Id       string                 `path:"id"`
	Schema   map[string]interface{} `json:"schema,optional"`
	UIConfig interface{}            `json:"ui_schema,optional"`
}

type SchemaUpdateResponse struct {
	Ok bool `json:"ok"`
}

type SchemaDeleteRequest struct {
	Id string `path:"id"`
}

type SchemaDeleteResponse struct {
	Ok bool `json:"ok"`
}

type SchemaDetailRequest struct {
	Id string `path:"id"`
}

type SchemaDetailResponse struct {
	Id        string      `json:"id"`
	Schema    interface{} `json:"schema"`
	UISchema  interface{} `json:"ui_schema"`
	UpdatedAt string      `json:"updated_at"`
	Size      int64       `json:"size"`
}

type SchemasQuery struct {
	Category string `form:"category,optional"`
	Search   string `form:"search,optional"`
}

type SchemaInfo struct {
	Id          string      `json:"id"`
	Title       interface{} `json:"title"`
	Description interface{} `json:"description"`
	Category    string      `json:"category"`
	Type        interface{} `json:"type"`
	Version     interface{} `json:"version"`
	UpdatedAt   string      `json:"updated_at"`
	Size        int64       `json:"size"`
}

type SchemasListResponse struct {
	Schemas []SchemaInfo `json:"schemas"`
	Total   int64        `json:"total"`
}

type SchemaValidateRequest struct {
	Id   string      `path:"id"`
	Data interface{} `json:"data"`
}

type SchemaValidateResponse struct {
	Valid  bool     `json:"valid"`
	Errors []string `json:"errors"`
}

type SchemaRawValidateRequest struct {
	Schema map[string]interface{} `json:"schema"`
}

type SchemaRawValidateResponse struct {
	Valid  bool     `json:"valid"`
	Errors []string `json:"errors"`
}

type SchemaUIConfigRequest struct {
	Id string `path:"id"`
}

type SchemaUIConfigResponse struct {
	UIConfig interface{} `json:"ui_config"`
}

type SchemaUIConfigUpdateRequest struct {
	Id       string      `path:"id"`
	UIConfig interface{} `json:"ui_config"`
}

type SchemaUIConfigUpdateResponse struct {
	Ok bool `json:"ok"`
}

type UISchemaRequest struct {
	Id string `form:"id"`
}

type UISchemaResponse struct {
	Schema   interface{} `json:"schema"`
	UISchema interface{} `json:"uischema"`
}

type XRenderComponentsRequest struct {
	Category string `form:"category,optional"`
}

type XRenderComponentsResponse struct {
	Components map[string][]map[string]interface{} `json:"components"`
}

type XRenderGenerateRequest struct {
	SchemaId   string                 `json:"schema_id"`
	Components map[string]interface{} `json:"components"`
	UIConfig   map[string]interface{} `json:"ui_config,optional"`
}

type XRenderGenerateResponse struct {
	Id       string      `json:"id"`
	Schema   interface{} `json:"schema"`
	UISchema interface{} `json:"ui_schema"`
}

type XRenderPreviewRequest struct {
	Components map[string]interface{} `json:"components"`
}

type XRenderPreviewResponse struct {
	Schema   interface{} `json:"schema"`
	UISchema interface{} `json:"ui_schema"`
}

type XRenderTemplatesResponse struct {
	Templates map[string]interface{} `json:"templates"`
}

type AdminFunctionRequest struct {
	Fid string `path:"fid"`
}

type AdminFunctionUIResponse struct {
	FunctionId string      `json:"function_id"`
	UI         interface{} `json:"ui,omitempty"`
}

type AdminFunctionUIUpdateRequest struct {
	Fid string                 `path:"fid"`
	UI  map[string]interface{} `json:"-"`
}

type AdminFunctionUIUpdateResponse struct {
	Ok bool `json:"ok"`
}

type AdminFunctionPermissionsResponse struct {
	FunctionId  string      `json:"function_id"`
	Permissions interface{} `json:"permissions,omitempty"`
}

type AdminFunctionPermissionsUpdateRequest struct {
	Fid         string                 `path:"fid"`
	Permissions map[string]interface{} `json:"-"`
}

type AdminFunctionPermissionsUpdateResponse struct {
	Ok bool `json:"ok"`
}

type AdminPendingFunction struct {
	FunctionId           string      `json:"function_id"`
	DisplayName          interface{} `json:"display_name,omitempty"`
	Summary              interface{} `json:"summary,omitempty"`
	SuggestedPermissions interface{} `json:"suggested_permissions,omitempty"`
}

type AdminPendingResponse struct {
	Pending []AdminPendingFunction `json:"pending"`
}

type AdminPublishRequest struct {
	Fid string `path:"fid"`
}

type AdminPublishResponse struct {
	Ok bool `json:"ok"`
}
