// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminFunctionPermissionsGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AdminFunctionPermissionsUpdateRequest struct {
	Fid         string      `json:"fid"`         // 函数ID
	Permissions interface{} `json:"permissions"` // 权限配置
}

type AdminFunctionPermissionsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Ok      bool        `json:"ok,omitempty"`
	Data    interface{} `json:"data,omitempty"`
}

type AdminFunctionPublishResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Ok      bool        `json:"ok,omitempty"`
	Data    interface{} `json:"data,omitempty"`
}

type AdminFunctionRequest struct {
	Fid string `form:"fid"` // 函数ID
}

type AdminFunctionUIGetResponse struct {
	Code       int         `json:"code"`
	Message    string      `json:"message"`
	FunctionId string      `json:"functionId,omitempty"`
	UI         interface{} `json:"ui,omitempty"`
	Data       interface{} `json:"data,omitempty"`
}

type AdminFunctionUIUpdateRequest struct {
	Fid string      `json:"fid"` // 函数ID
	UI  interface{} `json:"ui"`  // UI配置
}

type AdminFunctionUIUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AdminPendingRequest struct {
}

type AdminPendingResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AdminPublishRequest struct {
	Fid string `json:"fid"` // 函数ID
}

type AgentAnalyticsFiltersResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AgentMetaReportRequest struct {
}

type AgentMetaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsBehaviorAdoptionBreakdownRequest struct {
	GameID  string `form:"gameId,optional"`
	Env     string `form:"env,optional"`
	Feature string `form:"feature,optional"`
}

type AnalyticsBehaviorAdoptionBreakdownResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsBehaviorAdoptionRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsBehaviorAdoptionResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsBehaviorEventsRequest struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	EventType string `form:"eventType,optional"`
}

type AnalyticsBehaviorEventsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsBehaviorFunnelRequest struct {
	GameID string   `form:"gameId,optional"`
	Env    string   `form:"env,optional"`
	Steps  []string `form:"steps,optional"`
}

type AnalyticsBehaviorFunnelResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsBehaviorPathsRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsBehaviorPathsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsBehaviorRequest struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}

type AnalyticsBehaviorResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsFiltersGetRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsFiltersGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsFiltersQuery struct {
}

type AnalyticsFiltersUpdateRequest struct {
	GameID          string   `json:"gameId"`
	Env             string   `json:"env"`
	Events          []string `json:"events,optional"`
	PaymentsEnabled bool     `json:"paymentsEnabled,optional"`
}

type AnalyticsFiltersUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsIngestRequest struct {
	GameID string        `json:"gameId"`
	Env    string        `json:"env"`
	Events []interface{} `json:"events"`
}

type AnalyticsIngestResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsLevelsEpisodesRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsLevelsEpisodesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsLevelsMapsRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsLevelsMapsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsLevelsRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsLevelsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsOverviewRequest struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}

type AnalyticsOverviewResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsPaymentsIngestRequest struct {
	GameID       string        `json:"gameId"`
	Env          string        `json:"env"`
	Transactions []interface{} `json:"transactions"`
}

type AnalyticsPaymentsIngestResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsPaymentsProductTrendRequest struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	ProductID string `form:"productId,optional"`
}

type AnalyticsPaymentsProductTrendResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsPaymentsRequest struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}

type AnalyticsPaymentsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsPaymentsSummaryRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsPaymentsSummaryResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsPaymentsTransactionsRequest struct {
	GameID   string `form:"gameId,optional"`
	Env      string `form:"env,optional"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
}

type AnalyticsPaymentsTransactionsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsQuery struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}

type AnalyticsRealtimeRequest struct {
	GameID string `form:"gameId,optional"`
	Env    string `form:"env,optional"`
}

type AnalyticsRealtimeResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsRealtimeSeriesRequest struct {
	GameID   string `form:"gameId,optional"`
	Env      string `form:"env,optional"`
	Interval string `form:"interval,optional"`
}

type AnalyticsRealtimeSeriesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AnalyticsRetentionRequest struct {
	GameID    string `form:"gameId,optional"`
	Env       string `form:"env,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}

type AnalyticsRetentionResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalApproveRequest struct {
	ID string `path:"id"` // 审批ID
}

type ApprovalApproveResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalGetRequest struct {
	ID string `path:"id"` // 审批ID
}

type ApprovalGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalRejectRequest struct {
	ID     string `path:"id"`     // 审批ID
	Reason string `json:"reason"` // 拒绝原因
}

type ApprovalRejectResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalsListRequest struct {
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
	Status   string `form:"status,optional"`   // 状态过滤
}

type ApprovalsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AssignmentsListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type AssignmentsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AssignmentsUpdateRequest struct {
	Assignments []interface{} `json:"assignments"`
}

type AssignmentsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AuditRequest struct {
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
	Action   string `form:"action,optional"`   // 操作类型过滤
	UserID   string `form:"userId,optional"`   // 用户ID过滤
}

type AuditResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AuthMeData struct {
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type AuthMeRequest struct {
}

type AuthMeResponse struct {
	Code    int        `json:"code"`
	Message string     `json:"message"`
	Data    AuthMeData `json:"data,omitempty"`
}

type CertificateAddRequest struct {
	Domain      string `json:"domain"`
	Certificate string `json:"certificate,optional"`
	PrivateKey  string `json:"privateKey,optional"`
}

type CertificateAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateAlertAddRequest struct {
	Domain    string `json:"domain"`
	Threshold int    `json:"threshold,optional"`
}

type CertificateAlertAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateAlertsListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type CertificateAlertsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateCheckAllRequest struct {
}

type CertificateCheckAllResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateCheckRequest struct {
	ID string `path:"id"`
}

type CertificateCheckResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateDeleteRequest struct {
	ID string `path:"id"`
}

type CertificateDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateDetailRequest struct {
	ID string `path:"id"`
}

type CertificateDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateDomainInfoRequest struct {
	Domain string `form:"domain"`
}

type CertificateDomainInfoResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateExpiringRequest struct {
	Days int `form:"days,optional"`
}

type CertificateExpiringResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateStatsRequest struct {
}

type CertificateStatsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificatesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}

type CertificatesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentActionRequest struct {
	ID string `path:"id"`
}

type ComponentDetailRequest struct {
	ID string `path:"id"`
}

type ComponentPatchRequest struct {
	ID    string      `path:"id"`
	Patch interface{} `json:"patch"`
}

type ComponentsDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsDisableResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsEnableResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsInstallRequest struct {
	Name    string `json:"name"`
	Version string `json:"version,optional"`
}

type ComponentsInstallResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type ComponentsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsPatchResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfigUpsertRequest struct {
	Key   string `json:"key"`   // 配置键
	Value string `json:"value"` // 配置值
}

type ConfigUpsertResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfigVersionDetailRequest struct {
	Key     string `form:"key"`     // 配置键
	Version int    `form:"version"` // 版本号
}

type ConfigVersionDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfigVersionsRequest struct {
	Key string `form:"key"` // 配置键
}

type ConfigVersionsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type DescriptorsRequest struct {
	Type string `form:"type,optional"`
}

type DescriptorsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntitiesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Type     string `form:"type,optional"`
}

type EntitiesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityCreateRequest struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}

type EntityCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityDeleteRequest struct {
	ID string `path:"id"`
}

type EntityDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityDetailRequest struct {
	ID string `path:"id"`
}

type EntityDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityPreviewRequest struct {
	ID string `path:"id"`
}

type EntityPreviewResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityUpdateRequest struct {
	ID   string      `path:"id"`
	Data interface{} `json:"data"`
}

type EntityUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityValidateRequest struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}

type EntityValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FunctionActionRequest struct {
	ID string `path:"id"`
}

type FunctionDetailRequest struct {
	ID string `path:"id"`
}

type FunctionDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FunctionDisableResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FunctionEnableResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FunctionInstancesRequest struct {
	ID string `path:"id"`
}

type FunctionInstancesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FunctionInvokeRequest struct {
	ID     string      `path:"id"`
	Params interface{} `json:"params,optional"`
}

type FunctionInvokeResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FunctionsListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	GameID   string `form:"gameId,optional"`
	Status   string `form:"status,optional"`
}

type FunctionsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameCreateRequest struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Config      string `json:"config,optional"`
}

type GameCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameDeleteRequest struct {
	ID string `path:"id"`
}

type GameDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameDetailRequest struct {
	ID string `path:"id"`
}

type GameDetailResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    GameInfo `json:"data,omitempty"`
}

type GameEnvAddRequest struct {
	ID   string `path:"id"`
	Name string `json:"name"`
	Type string `json:"type,optional"`
}

type GameEnvAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameEnvDeleteRequest struct {
	ID    string `path:"id"`
	EnvID string `path:"envId"`
}

type GameEnvDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameEnvItem struct {
	Env         string `json:"env"`
	Description string `json:"description,optional"`
	Color       string `json:"color,optional"`
}

type GameEnvUpdateRequest struct {
	ID    string `path:"id"`
	EnvID string `path:"envId"`
	Name  string `json:"name,optional"`
	Type  string `json:"type,optional"`
}

type GameEnvUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameEnvsData struct {
	Envs []GameEnvItem `json:"envs"`
}

type GameEnvsListRequest struct {
	ID string `path:"id"`
}

type GameEnvsListResponse struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    GameEnvsData `json:"data,omitempty"`
}

type GameInfo struct {
	ID          uint          `json:"id"`
	Name        string        `json:"name"`
	Icon        string        `json:"icon,optional"`
	Description string        `json:"description,optional"`
	Enabled     bool          `json:"enabled"`
	AliasName   string        `json:"aliasName,optional"`
	Homepage    string        `json:"homepage,optional"`
	Status      string        `json:"status"`
	GameType    string        `json:"gameType,optional"`
	GenreCode   string        `json:"genreCode,optional"`
	Envs        []GameEnvItem `json:"envs,optional"`
	CreatedAt   string        `json:"createdAt,optional"`
	UpdatedAt   string        `json:"updatedAt,optional"`
}

type GameUpdateRequest struct {
	ID          string `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Config      string `json:"config,optional"`
	Status      string `json:"status,optional"`
}

type GameUpdateResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    GameInfo `json:"data,omitempty"`
}

type GamesData struct {
	Games []GameInfo `json:"games"`
	Total int        `json:"total,optional"`
}

type GamesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}

type GamesListResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    GamesData `json:"data,omitempty"`
}

type HealthzRequest struct {
}

type HealthzResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type JobCancelRequest struct {
	ID string `path:"id"` // 任务ID
}

type JobCancelResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type JobResultRequest struct {
	ID string `path:"id"` // 任务ID
}

type JobResultResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type JobStartRequest struct {
	FunctionID string      `json:"functionId"` // 函数ID
	Params     interface{} `json:"params,optional"`
}

type JobStartResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type LoginData struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type LoginRequest struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data,omitempty"` // 包含 token 和 user 信息
}

type LogoutRequest struct {
}

type LogoutResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MeGamesRequest struct {
}

type MeGamesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MePasswordRequest struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type MePasswordResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MeProfileRequest struct {
}

type MeProfileResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MeProfileUpdateRequest struct {
	Name   string `json:"name,optional"`
	Avatar string `json:"avatar,optional"`
	Email  string `json:"email,optional"`
}

type MeProfileUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessageDetailRequest struct {
	ID string `path:"id"`
}

type MessageDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessageReadRequest struct {
	ID string `path:"id"`
}

type MessageReadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessageSendRequest struct {
	To      string      `json:"to"`
	Type    string      `json:"type"`
	Title   string      `json:"title,optional"`
	Content string      `json:"content"`
	Data    interface{} `json:"data,optional"`
}

type MessageSendResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessagesListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Type     string `form:"type,optional"`
	Status   string `form:"status,optional"`
}

type MessagesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessagesUnreadCountRequest struct {
}

type MessagesUnreadCountResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MetricsRequest struct {
}

type MetricsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsAgentMetaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsAgentMetaUpdateRequest struct {
	AgentID string      `json:"agentId"`
	Meta    interface{} `json:"meta"`
}

type OpsAlertSilenceDeleteRequest struct {
	ID string `path:"id"`
}

type OpsAlertSilenceRequest struct {
	AlertID  string `json:"alertId"`
	Duration int    `json:"duration"` // 静默时长（分钟）
}

type OpsAlertSilenceResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupCreateRequest struct {
	Name string `json:"name,optional"`
}

type OpsBackupCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupDeleteRequest struct {
	ID string `path:"id"`
}

type OpsBackupDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupDownloadRequest struct {
	ID string `path:"id"`
}

type OpsBackupDownloadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupsListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type OpsBackupsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsConfigRequest struct {
}

type OpsConfigResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsFunctionsRequest struct {
}

type OpsFunctionsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsHealthGetRequest struct {
}

type OpsHealthGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsHealthRunRequest struct {
}

type OpsHealthRunResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsHealthUpdateRequest struct {
	Enabled bool `json:"enabled"`
}

type OpsHealthUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMQRequest struct {
}

type OpsMQResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMaintenanceGetRequest struct {
}

type OpsMaintenanceGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMaintenanceUpdateRequest struct {
	Enabled bool   `json:"enabled"`
	Message string `json:"message,optional"`
}

type OpsMaintenanceUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMetricsQuery struct {
	Start string `form:"start,optional"`
	End   string `form:"end,optional"`
}

type OpsMetricsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeActionRequest struct {
	NodeID string `path:"nodeId"`
}

type OpsNodeCommandsQuery struct {
	NodeID string `form:"nodeId"`
}

type OpsNodeCommandsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeDrainResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeMetaRequest struct {
	NodeID string `path:"nodeId"`
}

type OpsNodeMetaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeRestartResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeUndrainResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodesRequest struct {
}

type OpsNodesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNotificationsGetRequest struct {
}

type OpsNotificationsGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNotificationsUpdateRequest struct {
	Enabled  bool     `json:"enabled"`
	Channels []string `json:"channels,optional"`
}

type OpsNotificationsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsRateLimitsDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsRateLimitsGetRequest struct {
}

type OpsRateLimitsGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsRateLimitsPreviewResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsRateLimitsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsServicesRequest struct {
}

type OpsServicesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsSilenceDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsSilencesRequest struct {
}

type OpsSilencesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type PacksExportRequest struct {
	ID string `form:"id"`
}

type PacksExportResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type PacksImportRequest struct {
}

type PacksImportResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type PacksListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type PacksListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type PacksReloadRequest struct {
}

type PacksReloadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProviderActionRequest struct {
	ID string `path:"id"`
}

type ProviderDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProviderDetailRequest struct {
	ID string `path:"id"`
}

type ProviderDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProviderReloadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersCapabilitiesRequest struct {
}

type ProvidersCapabilitiesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersDescriptorsRequest struct {
}

type ProvidersDescriptorsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersEntitiesRequest struct {
	ID string `path:"id"`
}

type ProvidersEntitiesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type ProvidersListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RateLimitDeleteRequest struct {
	ID string `path:"id"`
}

type RateLimitPreviewQuery struct {
	Rule string `form:"rule"`
}

type RateLimitRulesRequest struct {
	Rules []interface{} `json:"rules"`
}

type RoleCreateRequest struct {
	Name        string   `json:"name"`
	Description string   `json:"description,optional"`
	Permissions []string `json:"permissions,optional"`
}

type RoleCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RoleDeleteRequest struct {
	ID string `path:"id"`
}

type RoleDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RoleDetailRequest struct {
	ID string `path:"id"`
}

type RoleDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RolePermissionsUpdateRequest struct {
	ID          string   `path:"id"`
	Permissions []string `json:"permissions"`
}

type RolePermissionsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RoleUpdateRequest struct {
	ID          string   `path:"id"`
	Name        string   `json:"name,optional"`
	Description string   `json:"description,optional"`
	Permissions []string `json:"permissions,optional"`
}

type RoleUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RolesListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type RolesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RootRequest struct {
}

type RootResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaCreateRequest struct {
	Name   string      `json:"name"`
	Schema interface{} `json:"schema"`
}

type SchemaCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaDeleteRequest struct {
	ID string `path:"id"`
}

type SchemaDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaDetailRequest struct {
	ID string `path:"id"`
}

type SchemaDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaRawValidateRequest struct {
	Schema interface{} `json:"schema"`
	Data   interface{} `json:"data"`
}

type SchemaRawValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaUIConfigRequest struct {
	ID string `path:"id"`
}

type SchemaUIConfigResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaUIConfigUpdateRequest struct {
	ID     string      `path:"id"`
	Config interface{} `json:"config"`
}

type SchemaUIConfigUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaUpdateRequest struct {
	ID     string      `path:"id"`
	Schema interface{} `json:"schema"`
}

type SchemaUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaValidateRequest struct {
	ID   string      `path:"id"`
	Data interface{} `json:"data"`
}

type SchemaValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemasListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type SchemasListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SignedUrlRequest struct {
	Path   string `form:"path"`
	Expire int    `form:"expire,optional"`
}

type SignedUrlResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type StatusRequest struct {
}

type StatusResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type StreamJobRequest struct {
	JobID string `path:"jobId"`
}

type StreamJobResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type StreamMessagesRequest struct {
}

type StreamMessagesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportCommentCreateRequest struct {
	TicketID string `path:"ticketId"`
	Content  string `json:"content"`
}

type SupportCommentCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportCommentsListRequest struct {
	TicketID string `path:"ticketId"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
}

type SupportCommentsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFAQCreateRequest struct {
	Category string `json:"category"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type SupportFAQCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFAQDeleteRequest struct {
	ID string `path:"id"`
}

type SupportFAQDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFAQListRequest struct {
	Category string `form:"category,optional"`
}

type SupportFAQListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFAQUpdateRequest struct {
	ID       string `path:"id"`
	Category string `json:"category,optional"`
	Question string `json:"question,optional"`
	Answer   string `json:"answer,optional"`
}

type SupportFAQUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFeedbackCreateRequest struct {
	Type    string `json:"type"`
	Content string `json:"content"`
}

type SupportFeedbackCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFeedbackDeleteRequest struct {
	ID string `path:"id"`
}

type SupportFeedbackDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFeedbackListRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type SupportFeedbackListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportFeedbackUpdateRequest struct {
	ID      string `path:"id"`
	Status  string `json:"status,optional"`
	Comment string `json:"comment,optional"`
}

type SupportFeedbackUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportTicketCreateRequest struct {
	Subject string `json:"subject"`
	Content string `json:"content"`
}

type SupportTicketCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportTicketDeleteRequest struct {
	ID string `path:"id"`
}

type SupportTicketDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportTicketDetailRequest struct {
	ID string `path:"id"`
}

type SupportTicketDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportTicketTransitionRequest struct {
	ID     string `path:"id"`
	Status string `json:"status"`
}

type SupportTicketTransitionResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportTicketUpdateRequest struct {
	ID      string `path:"id"`
	Subject string `json:"subject,optional"`
	Content string `json:"content,optional"`
}

type SupportTicketUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SupportTicketsListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}

type SupportTicketsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UISchemaRequest struct {
	Type string `form:"type"`
}

type UISchemaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserCreateRequest struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Email    string   `json:"email,optional"`
	Roles    []string `json:"roles,optional"`
}

type UserCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserCurrentRequest struct {
}

type UserCurrentResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserDeleteRequest struct {
	ID string `path:"id"`
}

type UserDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserDetailRequest struct {
	ID string `path:"id"`
}

type UserDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserGameEnvsRequest struct {
	ID string `path:"id"`
}

type UserGameEnvsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserGameEnvsUpdateRequest struct {
	ID       string   `path:"id"`
	GameEnvs []string `json:"gameEnvs"`
}

type UserGameEnvsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserGamesRequest struct {
	ID string `path:"id"`
}

type UserGamesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserGamesUpdateRequest struct {
	ID    string   `path:"id"`
	Games []string `json:"games"`
}

type UserGamesUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserInfo struct {
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type UserPasswordResetRequest struct {
	ID string `path:"id"`
}

type UserPasswordResetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserProfileRequest struct {
	ID string `path:"id"`
}

type UserProfileResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UserUpdateRequest struct {
	ID       string   `path:"id"`
	Username string   `json:"username,optional"`
	Email    string   `json:"email,optional"`
	Roles    []string `json:"roles,optional"`
	Status   string   `json:"status,optional"`
}

type UserUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UsersListRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Search   string `form:"search,optional"`
	Role     string `form:"role,optional"`
}

type UsersListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type XRenderComponentsRequest struct {
}

type XRenderComponentsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type XRenderGenerateRequest struct {
	Schema interface{} `json:"schema"`
}

type XRenderGenerateSchemaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type XRenderPreviewRequest struct {
	Schema interface{} `json:"schema"`
}

type XRenderPreviewSchemaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type XRenderTemplatesRequest struct {
}

type XRenderTemplatesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
