// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import "time"

type Admin struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Nickname  string   `json:"nickname"`
	Email     string   `json:"email"`
	Phone     string   `json:"phone"`
	Roles     []string `json:"roles"`
	Status    int      `json:"status"` // 1:active 0:disabled
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type AdminCreateRequest struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Nickname string   `json:"nickname"`
	Email    string   `json:"email"`
	Phone    string   `json:"phone"`
	Roles    []string `json:"roles"`
}

type AdminCreateResponse struct {
	Admin
}

type AdminDeleteRequest struct {
	ID string `uri:"id"`
}

type AdminDeleteResponse struct {
	Message string `json:"message"`
}

type AdminDetailRequest struct {
	ID string `uri:"id"`
}

type AdminDetailResponse struct {
	Admin
}

type AdminGame struct {
	GameId   string   `json:"gameId"`
	GameName string   `json:"gameName"`
	Envs     []string `json:"envs"`
}

type AdminGamesRequest struct {
	ID string `uri:"id"`
}

type AdminGamesResponse struct {
	Games []AdminGame `json:"games"`
}

type AdminGamesUpdateRequest struct {
	ID    string      `uri:"id"`
	Games []AdminGame `json:"games"`
}

type AdminPasswordResetRequest struct {
	ID          string `uri:"id"`
	NewPassword string `json:"newPassword"`
}

type AdminPasswordResetResponse struct {
	Message string `json:"message"`
}

type AdminUpdateRequest struct {
	ID       string   `uri:"id"`
	Nickname string   `json:"nickname"`
	Email    string   `json:"email"`
	Phone    string   `json:"phone"`
	Roles    []string `json:"roles"`
	Status   int      `json:"status"`
}

type AdminUpdateResponse struct {
	Admin
}

type AdminsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Search   string `form:"search"`
	Role     string `form:"role"`
	Status   int    `form:"status"`
}

type AdminsListResponse struct {
	Items []Admin `json:"items"`
	Total int64   `json:"total"`
	Page  int     `json:"page"`
	Size  int     `json:"pageSize"`
}

type AgentAnalyticsFiltersResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AgentMetaReportRequest struct {
}

type AgentMetaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Alert struct {
	Id        string      `json:"id"`
	Type      string      `json:"type"`
	Level     string      `json:"level"`
	Message   string      `json:"message"`
	Source    string      `json:"source"`
	Status    string      `json:"status"`
	Details   interface{} `json:"details"`
	CreatedAt string      `json:"createdAt"`
}

type AlertSilenceRequest struct {
	ID       string `uri:"id"`
	Duration int    `json:"duration"` // 分钟
	Reason   string `json:"reason"`
}

type AlertsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Level    string `form:"level"`
	Status   string `form:"status"`
}

type AlertsListResponse struct {
	Items []Alert `json:"items"`
	Total int64   `json:"total"`
	Page  int     `json:"page"`
	Size  int     `json:"pageSize"`
}

type AnalyticsFilters struct {
	GameId  string      `json:"gameId"`
	Filters interface{} `json:"filters"`
}

type AnalyticsFiltersQuery struct {
}

type AnalyticsQuery struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type ApprovalApproveRequest struct {
	ID string `uri:"id"` // 审批ID
}

type ApprovalApproveResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalGetRequest struct {
	ID string `uri:"id"` // 审批ID
}

type ApprovalGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalRejectRequest struct {
	ID     string `uri:"id"`     // 审批ID
	Reason string `json:"reason"` // 拒绝原因
}

type ApprovalRejectResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ApprovalsListRequest struct {
	Page     int    `form:"page"`     // 页码
	PageSize int    `form:"pageSize"` // 每页数量
	Status   string `form:"status"`   // 状态过滤
}

type ApprovalsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AssignmentsHistoryRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	GameId   string `form:"game_id"`
	Env      string `form:"env"`
	Action   string `form:"action"`
}

type AssignmentsHistoryResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AssignmentsListRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	GameId   string `form:"game_id"`
	Env      string `form:"env"`
}

type AssignmentsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AssignmentsUpdateRequest struct {
	GameId    string   `json:"game_id"`
	Env       string   `json:"env"`
	Action    string   `json:"action"` // assign/clone/remove
	Functions []string `json:"functions"`
}

type AssignmentsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type AuditRequest struct {
	Page     int    `form:"page"`     // 页码
	PageSize int    `form:"pageSize"` // 每页数量
	Action   string `form:"action"`   // 操作类型过滤
	UserID   string `form:"userId"`   // 用户ID过滤
}

type AuditResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Backup struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Size      int64  `json:"size"`
	Type      string `json:"type"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type BackupCreateRequest struct {
	Name string `json:"name"`
	Type string `json:"type"` // full, incremental
}

type BackupDeleteRequest struct {
	ID string `uri:"id"`
}

type BackupDetailResponse struct {
	Backup
}

type BackupDownloadRequest struct {
	ID string `uri:"id"`
}

type BackupsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Type     string `form:"type"`
}

type BackupsListResponse struct {
	Items []Backup `json:"items"`
	Total int64    `json:"total"`
	Page  int      `json:"page"`
	Size  int      `json:"pageSize"`
}

type BatchCopyFunctionsRequest struct {
	FunctionIds []string `json:"function_ids"`
}

type BatchCopyFunctionsResponse struct {
	Updated int      `json:"updated"`
	Failed  []string `json:"failed"`
	Copied  []string `json:"copied"` // 新复制的函数ID列表
}

type BatchDeleteFunctionsRequest struct {
	FunctionIds []string `json:"function_ids"`
}

type BatchDeleteFunctionsResponse struct {
	Updated int      `json:"updated"`
	Failed  []string `json:"failed"`
}

type BatchDeleteObjectsData struct {
	Deleted []string `json:"deleted"`
	Failed  []string `json:"failed"`
}

type BatchDeleteObjectsRequest struct {
	Keys []string `json:"keys"`
}

type BatchDeleteObjectsResponse struct {
	Code    int                    `json:"code"`
	Message string                 `json:"message"`
	Data    BatchDeleteObjectsData `json:"data"`
}

type BatchUpdateFunctionsRequest struct {
	FunctionIds []string `json:"function_ids"`
	Enabled     bool     `json:"enabled"`
}

type BatchUpdateFunctionsResponse struct {
	Updated int      `json:"updated"`
	Failed  []string `json:"failed"`
}

type BehaviorAdoptionBreakdownRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	Feature   string `form:"feature"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type BehaviorAdoptionBreakdownResponse struct {
	BySegment interface{} `json:"bySegment"`
	ByTime    interface{} `json:"byTime"`
}

type BehaviorAdoptionRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	Feature   string `form:"feature"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type BehaviorAdoptionResponse struct {
	Features []FeatureAdoption `json:"features"`
}

type BehaviorEvent struct {
	EventType string      `json:"eventType"`
	UserId    string      `json:"userId"`
	Data      interface{} `json:"data"`
	Timestamp string      `json:"timestamp"`
}

type BehaviorEventsRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	EventType string `form:"eventType"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
	Limit     int    `form:"limit,optional,default=100"`
}

type BehaviorEventsResponse struct {
	Items []BehaviorEvent `json:"items"`
	Total int64           `json:"total"`
}

type BehaviorFunnelRequest struct {
	GameId    string   `form:"gameId"`
	Env       string   `form:"env"`
	Steps     []string `json:"steps"`
	StartDate string   `form:"startDate"`
	EndDate   string   `form:"endDate"`
}

type BehaviorFunnelResponse struct {
	Steps []FunnelStep `json:"steps"`
}

type BehaviorPathsRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
	Depth     int    `form:"depth,optional,default=5"`
}

type BehaviorPathsResponse struct {
	Paths interface{} `json:"paths"`
}

type BehaviorRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type BehaviorResponse struct {
	TopActions interface{} `json:"topActions"`
	UserFlows  interface{} `json:"userFlows"`
	HeatMap    interface{} `json:"heatMap"`
}

type CallPlatformRequest struct {
	Platform string `json:"platform"` // 平台名称，如 "quicksdk"
	Method   string `json:"method"`   // API 方法名
	Request  string `json:"request"`  // 请求参数（JSON 字符串格式）
}

type CallPlatformResponse struct {
	Code     int         `json:"code"`
	Message  string      `json:"message"`
	Response interface{} `json:"response,omitempty"` // 平台返回的响应
}

type CertificateAddRequest struct {
	Domain      string `json:"domain"`
	Certificate string `json:"certificate"`
	PrivateKey  string `json:"privateKey"`
}

type CertificateAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateAlertAddRequest struct {
	Domain    string `json:"domain"`
	Threshold int    `json:"threshold"`
}

type CertificateAlertAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateAlertsListRequest struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type CertificateAlertsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateCheckAllRequest struct {
}

type CertificateCheckAllResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateCheckRequest struct {
	ID string `uri:"id"`
}

type CertificateCheckResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateDeleteRequest struct {
	ID string `uri:"id"`
}

type CertificateDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateDetailRequest struct {
	ID string `uri:"id"`
}

type CertificateDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateDomainInfoRequest struct {
	Domain string `form:"domain"`
}

type CertificateDomainInfoResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateExpiringRequest struct {
	Days int `form:"days"`
}

type CertificateExpiringResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificateStatsRequest struct {
}

type CertificateStatsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CertificatesListRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	Status   string `form:"status"`
}

type CertificatesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Comment struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	Author    string `json:"author"`
	CreatedAt string `json:"createdAt"`
}

type ComponentActionRequest struct {
	ID string `uri:"id"`
}

type ComponentDetailRequest struct {
	ID string `uri:"id"`
}

type ComponentPatchRequest struct {
	ID    string      `uri:"id"`
	Patch interface{} `json:"patch"`
}

type ComponentsDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsDisableResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsEnableResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsInstallRequest struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

type ComponentsInstallResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsListRequest struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type ComponentsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ComponentsPatchResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfigUpsertRequest struct {
	Key   string `json:"key"`   // 配置键
	Value string `json:"value"` // 配置值
}

type ConfigUpsertResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfigVersionDetailRequest struct {
	Key     string `form:"key"`     // 配置键
	Version int    `form:"version"` // 版本号
}

type ConfigVersionDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfigVersionsRequest struct {
	Key string `form:"key"` // 配置键
}

type ConfigVersionsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CreateDirectoryRequest struct {
	Prefix string `json:"prefix"`
}

type CreateDirectoryResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DeleteObjectRequest struct {
	Key string `form:"key"`
}

type DeleteObjectResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Descriptor struct {
	Id          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Schema      interface{} `json:"schema"`
}

type DescriptorsRequest struct {
	Type   string `form:"type"`
	GameId string `form:"gameId"`
}

type DescriptorsResponse struct {
	Items []Descriptor `json:"items"`
}

type EntitiesListRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	Type     string `form:"type"`
}

type EntitiesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityCreateRequest struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}

type EntityCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityDeleteRequest struct {
	ID string `uri:"id"`
}

type EntityDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityDetailRequest struct {
	ID string `uri:"id"`
}

type EntityDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityFunction struct {
	Id        string `json:"id"`
	Operation string `json:"operation"` // create/read/update/delete/custom
	Name      string `json:"name"`
}

type EntityFunctionsRequest struct {
	ID string `uri:"id"`
}

type EntityFunctionsResponse struct {
	Items []EntityFunction `json:"items"`
}

type EntityPreviewRequest struct {
	ID string `uri:"id"`
}

type EntityPreviewResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityUpdateRequest struct {
	ID   string      `uri:"id"`
	Data interface{} `json:"data"`
}

type EntityUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EntityValidateRequest struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}

type EntityValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type EpisodeMetrics struct {
	EpisodeId      string  `json:"episodeId"`
	Players        int     `json:"players"`
	CompletionRate float64 `json:"completionRate"`
	AvgProgress    float64 `json:"avgProgress"`
}

type FAQ struct {
	Id        int64    `json:"id"`
	Question  string   `json:"question"`
	Answer    string   `json:"answer"`
	Category  string   `json:"category"`
	Tags      []string `json:"tags"`
	Visible   bool     `json:"visible"`
	Sort      int      `json:"sort"`
	Views     int      `json:"views"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type FAQCategoriesRequest struct {
}

type FAQCategoriesResponse struct {
	Items []FAQCategory `json:"items"`
}

type FAQCategory struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type FAQCreateRequest struct {
	Question string   `json:"question"`
	Answer   string   `json:"answer"`
	Category string   `json:"category"`
	Tags     []string `json:"tags"`
	Visible  bool     `json:"visible,optional,default=true"`
	Sort     int      `json:"sort,optional,default=0"`
}

type FAQDeleteRequest struct {
	ID string `uri:"id"`
}

type FAQDetailResponse struct {
	FAQ
}

type FAQListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Category string `form:"category"`
	Keyword  string `form:"keyword"`
	Visible  *bool  `form:"visible"`
}

type FAQListResponse struct {
	Items []FAQ `json:"items"`
	Total int64 `json:"total"`
	Page  int   `json:"page"`
	Size  int   `json:"pageSize"`
}

type FAQUpdateRequest struct {
	ID       string   `uri:"id"`
	Question string   `json:"question"`
	Answer   string   `json:"answer"`
	Category string   `json:"category"`
	Tags     []string `json:"tags"`
	Visible  *bool    `json:"visible"`
	Sort     *int     `json:"sort"`
}

type FeatureAdoption struct {
	Feature      string  `json:"feature"`
	Users        int     `json:"users"`
	AdoptionRate float64 `json:"adoptionRate"`
	Frequency    float64 `json:"frequency"`
}

type Feedback struct {
	Id        int64  `json:"id"`
	PlayerId  string `json:"playerId"`
	Contact   string `json:"contact"`
	Content   string `json:"content"`
	Category  string `json:"category"`
	Priority  string `json:"priority"`
	Status    string `json:"status"`
	Rating    int    `json:"rating"` // 1-5星
	Attach    string `json:"attach"` // 附件URL
	GameId    string `json:"gameId"`
	Env       string `json:"env"`
	Reply     string `json:"reply"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type FeedbackCreateRequest struct {
	PlayerId string `json:"playerId"`
	Contact  string `json:"contact"`
	Content  string `json:"content"`
	Category string `json:"category"`
	Rating   int    `json:"rating"`
	Attach   string `json:"attach"`
	GameId   string `json:"gameId"`
	Env      string `json:"env"`
}

type FeedbackDeleteRequest struct {
	ID string `uri:"id"`
}

type FeedbackDetailResponse struct {
	Feedback
}

type FeedbackListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Status   string `form:"status"`
	Category string `form:"category"`
	GameId   string `form:"gameId"`
}

type FeedbackListResponse struct {
	Items []Feedback `json:"items"`
	Total int64      `json:"total"`
	Page  int        `json:"page"`
	Size  int        `json:"pageSize"`
}

type FeedbackStats struct {
	Total        int            `json:"total"`
	ByCategory   map[string]int `json:"byCategory"`
	ByStatus     map[string]int `json:"byStatus"`
	AvgRating    float64        `json:"avgRating"`
	ResponseRate float64        `json:"responseRate"`
}

type FeedbackStatsRequest struct {
	GameId string `form:"gameId"`
	Days   int    `form:"days,optional,default=7"`
}

type FeedbackStatsResponse struct {
	FeedbackStats
}

type FeedbackUpdateRequest struct {
	ID       string `uri:"id"`
	Status   string `json:"status"`
	Priority string `json:"priority"`
	Reply    string `json:"reply"`
}

type FiltersGetRequest struct {
	GameId string `form:"gameId"`
}

type FiltersGetResponse struct {
	Items []AnalyticsFilters `json:"items"`
}

type FiltersUpdateRequest struct {
	GameId  string      `json:"gameId"`
	Filters interface{} `json:"filters"`
}

type Function struct {
	Id          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	GameId      string      `json:"gameId"`
	Status      int         `json:"status"`
	Version     string      `json:"version"`
	Instances   int         `json:"instances"`
	SpecFormat  string      `json:"specFormat"`
	OpenAPISpec interface{} `json:"openapiSpec"`
	CreatedAt   string      `json:"createdAt"`
	UpdatedAt   string      `json:"updatedAt"`
}

type FunctionActionRequest struct {
	ID string `uri:"id"`
}

type FunctionAnalyticsRequest struct {
	ID string `uri:"id"`
}

type FunctionAnalyticsResponse struct {
	TotalCalls     int64   `json:"totalCalls"`
	SuccessRate    float64 `json:"successRate"`
	AvgLatency     float64 `json:"avgLatency"`
	CallsToday     int64   `json:"callsToday"`
	CallsThisWeek  int64   `json:"callsThisWeek"`
	CallsThisMonth int64   `json:"callsThisMonth"`
}

type FunctionCopyRequest struct {
	ID string `uri:"id"`
}

type FunctionCopyResponse struct {
	FunctionId string `json:"function_id"`
	NewId      string `json:"new_id"`
}

type FunctionDescriptor struct {
	Input  interface{} `json:"input"`
	Output interface{} `json:"output"`
	Schema interface{} `json:"schema"`
}

type FunctionDetailRequest struct {
	ID string `uri:"id"`
}

type FunctionDetailResponse struct {
	Function
	Descriptor FunctionDescriptor `json:"descriptor"`
}

type FunctionHistoryItem struct {
	ID        string      `json:"id"`
	Action    string      `json:"action"`
	Operator  string      `json:"operator"`
	Timestamp string      `json:"timestamp"`
	Details   interface{} `json:"details"`
}

type FunctionHistoryRequest struct {
	ID string `uri:"id"`
}

type FunctionInstance struct {
	AgentId   string `json:"agentId"`
	AgentName string `json:"agentName"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updatedAt"`
}

type FunctionInstancesAllRequest struct {
}

type FunctionInstancesAllResponse struct {
	Instances []map[string]interface{} `json:"instances"`
}

type FunctionInstancesRequest struct {
	ID string `uri:"id"`
}

type FunctionInstancesResponse struct {
	Items []FunctionInstance `json:"items"`
}

type FunctionInvokeRequest struct {
	ID              string      `uri:"id"`
	Params          interface{} `json:"params"`
	Payload         interface{} `json:"payload"`
	GameID          string      `json:"gameId"`
	Env             string      `json:"env"`
	Mode            string      `json:"mode"`
	Route           string      `json:"route"`
	TargetServiceID string      `json:"target_service_id"`
	HashKey         string      `json:"hash_key"`
}

type FunctionInvokeResponse struct {
	JobId  string      `json:"jobId"`
	JobID  string      `json:"jobID,omitempty"`
	Result interface{} `json:"result,omitempty"`
}

type FunctionPermission struct {
	Resource string   `json:"resource"`
	Actions  []string `json:"actions"`
	Roles    []string `json:"roles"`
}

type FunctionPermissionsRequest struct {
	ID string `uri:"id"`
}

type FunctionPermissionsResponse struct {
	Items []FunctionPermission `json:"items"`
}

type FunctionPermissionsUpdateRequest struct {
	ID          string               `uri:"id"`
	Permissions []FunctionPermission `json:"permissions"`
}

type FunctionPublishRequest struct {
	ID string `uri:"id"`
}

type FunctionPublishResponse struct {
	ApprovalId string `json:"approvalId,omitempty"` // 如果需要审批
	Published  bool   `json:"published"`
}

type FunctionRouteConfig struct {
	Nodes  []string `json:"nodes"`
	Path   string   `json:"path"`
	Order  int      `json:"order"`
	Hidden bool     `json:"hidden"`
}

type FunctionRouteRequest struct {
	ID string `uri:"id"`
}

type FunctionRouteResponse struct {
	Menu   FunctionRouteConfig `json:"menu"`
	Source string              `json:"source"`
}

type FunctionRouteUpdateRequest struct {
	ID     string   `uri:"id"`
	Nodes  []string `json:"nodes"`
	Path   string   `json:"path"`
	Order  int      `json:"order"`
	Hidden bool     `json:"hidden"`
}

type FunctionUIHistoryItem struct {
	Version    int         `json:"version"`
	Schema     interface{} `json:"schema"`
	Layout     interface{} `json:"layout"`
	Components interface{} `json:"components"`
	Message    string      `json:"message"`
	CreatedBy  string      `json:"createdBy"`
	CreatedAt  string      `json:"createdAt"`
}

type FunctionUIHistoryRequest struct {
	ID string `uri:"id"`
}

type FunctionUIHistoryResponse struct {
	Items []FunctionUIHistoryItem `json:"items"`
}

type FunctionUIRequest struct {
	ID string `uri:"id"`
}

type FunctionUIResponse struct {
	Schema         interface{} `json:"schema"`
	Layout         interface{} `json:"layout"`
	Components     interface{} `json:"components"`
	Custom         bool        `json:"custom"`
	HasDefault     bool        `json:"hasDefault"`
	UISource       string      `json:"uiSource"`       // custom_metadata/config_file_override/openapi_x_ui/none
	UISourceDetail string      `json:"uiSourceDetail"` // human-readable source description
}

type FunctionUIRollbackRequest struct {
	ID      string `uri:"id"`
	Version int    `json:"version"`
}

type FunctionUIRollbackResponse struct {
	AppliedVersion int                 `json:"appliedVersion"`
	Current        *FunctionUIResponse `json:"current"`
}

type FunctionUIUpdateRequest struct {
	ID         string      `uri:"id"`
	Schema     interface{} `json:"schema"`
	Layout     interface{} `json:"layout"`
	Components interface{} `json:"components"`
}

type FunctionWarningItem struct {
	Key        string `json:"key"`
	AgentID    string `json:"agent_id"`
	FunctionID string `json:"function_id"`
	Version    string `json:"version"`
	Code       string `json:"code"`
	Message    string `json:"message"`
	Count      int    `json:"count"`
	FirstSeen  string `json:"first_seen"`
	LastSeen   string `json:"last_seen"`
}

type FunctionWarningsRequest struct {
	FunctionID string `form:"function_id"`
	AgentID    string `form:"agent_id"`
	Code       string `form:"code"`
	Limit      int    `form:"limit,optional,default=100"`
}

type FunctionWarningsResponse struct {
	Items []FunctionWarningItem `json:"items"`
}

type FunctionsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	GameId   string `form:"gameId"`
	Category string `form:"category"`
	Status   int    `form:"status"`
}

type FunctionsListResponse struct {
	Items []Function `json:"items"`
	Total int64      `json:"total"`
	Page  int        `json:"page"`
	Size  int        `json:"pageSize"`
}

type FunctionsPendingRequest struct {
}

type FunctionsPendingResponse struct {
	Items []PendingFunction `json:"items"`
}

type FunnelStep struct {
	Step           string  `json:"step"`
	Users          int     `json:"users"`
	ConversionRate float64 `json:"conversionRate"`
	DropOffRate    float64 `json:"dropOffRate"`
}

type GameCreateRequest struct {
	Name        string `json:"name"`
	AliasName   string `json:"aliasName"`
	Description string `json:"description"`
	Config      string `json:"config"`
}

type GameCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameDeleteRequest struct {
	ID string `uri:"id"`
}

type GameDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameDetailRequest struct {
	ID string `uri:"id"`
}

type GameDetailResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    GameInfo `json:"data,omitempty"`
}

type GameEnvAddRequest struct {
	ID   string `uri:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

type GameEnvAddResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameEnvDeleteRequest struct {
	ID    string `uri:"id"`
	EnvID string `uri:"envId"`
}

type GameEnvDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameEnvItem struct {
	Env         string `json:"env"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type GameEnvUpdateRequest struct {
	ID    string `uri:"id"`
	EnvID string `uri:"envId"`
	Name  string `json:"name"`
	Type  string `json:"type"`
}

type GameEnvUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GameEnvsData struct {
	Envs []GameEnvItem `json:"envs"`
}

type GameEnvsListRequest struct {
	ID string `uri:"id"`
}

type GameEnvsListResponse struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    GameEnvsData `json:"data,omitempty"`
}

type GameInfo struct {
	ID          uint          `json:"id"`
	Name        string        `json:"name"`
	Icon        string        `json:"icon"`
	Description string        `json:"description"`
	Enabled     bool          `json:"enabled"`
	AliasName   string        `json:"aliasName"`
	Homepage    string        `json:"homepage"`
	Status      string        `json:"status"`
	GameType    string        `json:"gameType"`
	GenreCode   string        `json:"genreCode"`
	Color       string        `json:"color"`
	Envs        []GameEnvItem `json:"envs"`
	CreatedAt   string        `json:"createdAt"`
	UpdatedAt   string        `json:"updatedAt"`
}

type GameUpdateRequest struct {
	ID          string `uri:"id"`
	Name        string `json:"name"`
	AliasName   string `json:"aliasName"`
	Description string `json:"description"`
	Config      string `json:"config"`
	Status      string `json:"status"`
}

type GameUpdateResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    GameInfo `json:"data,omitempty"`
}

type GamesData struct {
	Games []GameInfo `json:"games"`
	Total int        `json:"total"`
}

type GamesListRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	Status   string `form:"status"`
}

type GamesListResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    GamesData `json:"data,omitempty"`
}

type GetRoutesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    []RouteItem `json:"data"`
}

type HealthzRequest struct {
}

type HealthzResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type IngestRequest struct {
	GameId    string      `json:"gameId"`
	Env       string      `json:"env"`
	Events    interface{} `json:"events"`
	Timestamp string      `json:"timestamp"`
}

type IngestResponse struct {
	Accepted int    `json:"accepted"`
	Rejected int    `json:"rejected"`
	BatchId  string `json:"batchId"`
}

type JobCancelRequest struct {
	ID string `uri:"id"` // 任务ID
}

type JobCancelResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type JobItem struct {
	ID         string `json:"id"`
	FunctionID string `json:"function_id,omitempty"`
	Actor      string `json:"actor,omitempty"`
	State      string `json:"state,omitempty"`
	GameID     string `json:"game_id,omitempty"`
	Env        string `json:"env,omitempty"`
	RPCAddr    string `json:"rpc_addr,omitempty"`
	StartedAt  string `json:"started_at,omitempty"`
	EndedAt    string `json:"ended_at,omitempty"`
	DurationMs int64  `json:"duration_ms,omitempty"`
	Error      string `json:"error,omitempty"`
}

type JobListRequest struct {
	Status     string `form:"status"`
	FunctionID string `form:"function_id"`
	Actor      string `form:"actor"`
	GameID     string `form:"game_id"`
	Env        string `form:"env"`
	Page       int    `form:"page,optional,default=1"`
	Size       int    `form:"size,optional,default=20"`
}

type JobListResponse struct {
	Jobs  []JobItem `json:"jobs"`
	Total int       `json:"total"`
}

type JobResultRequest struct {
	ID string `uri:"id"` // 任务ID
}

type JobResultResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type JobStartRequest struct {
	FunctionID string      `json:"functionId"` // 函数ID
	Params     interface{} `json:"params"`
}

type JobStartResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type LevelMetrics struct {
	LevelId        string  `json:"levelId"`
	Attempts       int     `json:"attempts"`
	Completions    int     `json:"completions"`
	CompletionRate float64 `json:"completionRate"`
	AvgDuration    float64 `json:"avgDuration"`
	AvgRetries     float64 `json:"avgRetries"`
}

type LevelsEpisodesRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type LevelsEpisodesResponse struct {
	Episodes []EpisodeMetrics `json:"episodes"`
}

type LevelsMapsRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type LevelsMapsResponse struct {
	Maps []MapMetrics `json:"maps"`
}

type LevelsRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type LevelsResponse struct {
	Levels []LevelMetrics `json:"levels"`
}

type ListObjectsRequest struct {
	Prefix    string `form:"prefix"`
	Marker    string `form:"marker"`
	Limit     int    `form:"limit"`
	Delimiter string `form:"delimiter"`
}

type ListObjectsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    ObjectsData `json:"data"`
}

type ListPlatformMethodsResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Methods []string `json:"methods,omitempty"`
}

type ListPlatformsResponse struct {
	Code      int            `json:"code"`
	Message   string         `json:"message"`
	Platforms []PlatformInfo `json:"platforms,omitempty"`
}

type LoginRequest struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
}

type MapMetrics struct {
	MapId      string      `json:"mapId"`
	HeatMap    interface{} `json:"heatMap"`
	DeathSpots interface{} `json:"deathSpots"`
}

type MessageDetailRequest struct {
	ID string `uri:"id"`
}

type MessageDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessageReadRequest struct {
	ID string `uri:"id"`
}

type MessageReadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessageSendRequest struct {
	To      string      `json:"to"`
	Type    string      `json:"type"`
	Title   string      `json:"title"`
	Content string      `json:"content"`
	Data    interface{} `json:"data"`
}

type MessageSendResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessagesListRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	Type     string `form:"type"`
	Status   string `form:"status"`
}

type MessagesListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MessagesUnreadCountRequest struct {
}

type MessagesUnreadCountResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type MetricsRequest struct {
}

type MetricsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Node struct {
	Id        string      `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"` // server, agent
	Status    string      `json:"status"`
	IP        string      `json:"ip"`
	Port      int         `json:"port"`
	Resources interface{} `json:"resources"`
	UpdatedAt string      `json:"updatedAt"`
}

type NodeActionRequest struct {
	ID string `uri:"id"`
}

type NodeCommand struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NodeCommandsRequest struct {
}

type NodeCommandsResponse struct {
	Items []NodeCommand `json:"items"`
}

type NodeDrainRequest struct {
	ID      string `uri:"id"`
	Timeout int    `json:"timeout"` // 秒
}

type NodeMetaRequest struct {
	ID string `uri:"id"`
}

type NodeMetaResponse struct {
	Meta interface{} `json:"meta"`
}

type NodeMetaUpdateRequest struct {
	ID   string      `uri:"id"`
	Meta interface{} `json:"meta"`
}

type NodesListRequest struct {
	Type   string `form:"type"`
	Status string `form:"status"`
}

type NodesListResponse struct {
	Items []Node `json:"items"`
}

type ObjectInfo struct {
	Key          string `json:"key"`
	Size         int64  `json:"size"`
	LastModified string `json:"last_modified"`
	ETag         string `json:"etag"`
	StorageClass string `json:"storage_class"`
}

type ObjectsData struct {
	Objects     []ObjectInfo `json:"objects"`
	Prefixes    []string     `json:"prefixes"`
	IsTruncated bool         `json:"is_truncated"`
	NextMarker  string       `json:"next_marker"`
}

type OpenAPIDocumentRequest struct {
}

type OpenAPIDocumentResponse struct {
	Spec interface{} `json:"spec"` // OpenAPI 3.0.3 Document
}

type OpenAPIImportRequest struct {
	Spec interface{} `json:"spec"` // OpenAPI 3.0.3 Document
}

type OpenAPIImportResponse struct {
	Imported int      `json:"imported"`
	Failed   []string `json:"failed"`
}

type OpenAPISpecRequest struct {
	ID string `uri:"id"`
}

type OpenAPISpecResponse struct {
	Spec interface{} `json:"spec"` // OpenAPI 3.0.3 Operation Object
}

type OpsAgentInfo struct {
	AgentID   string            `json:"agentId"`
	GameID    string            `json:"gameId"`
	Env       string            `json:"env"`
	Version   string            `json:"version"`
	RPCAddr   string            `json:"rpcAddr"`
	Connected bool              `json:"connected"`
	LastSeen  string            `json:"lastSeen"`
	Functions []string          `json:"functions"`
	Processes []string          `json:"processes"`
	Labels    map[string]string `json:"labels"`
}

type OpsAgentMetaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsAgentMetaUpdateRequest struct {
	AgentID string      `json:"agentId"`
	Meta    interface{} `json:"meta"`
}

type OpsAgentMetricsRequest struct {
	AgentID string `form:"agentId"`
	Since   string `form:"since"`
	Limit   int    `form:"limit"`
}

type OpsAgentMetricsResponse struct {
	Code    int              `json:"code"`
	Message string           `json:"message"`
	Data    []OpsMetricsData `json:"data,omitempty"`
}

type OpsAgentProcessesRequest struct {
	AgentID string `uri:"agentId"`
}

type OpsAgentProcessesResponse struct {
	Code    int                 `json:"code"`
	Message string              `json:"message"`
	Data    []OpsManagedProcess `json:"data,omitempty"`
}

type OpsAgentSystemInfo struct {
	Hostname      string `json:"hostname"`
	OS            string `json:"os"`
	OSVersion     string `json:"osVersion"`
	KernelVersion string `json:"kernelVersion"`
	Arch          string `json:"arch"`
	CPUCores      int32  `json:"cpuCores"`
	TotalMemory   uint64 `json:"totalMemory"`
	BootTime      string `json:"bootTime"`
	AgentVersion  string `json:"agentVersion"`
}

type OpsAgentSystemInfoRequest struct {
	AgentID string `uri:"agentId"`
}

type OpsAgentSystemInfoResponse struct {
	Code    int                `json:"code"`
	Message string             `json:"message"`
	Data    OpsAgentSystemInfo `json:"data,omitempty"`
}

type OpsAgentsListRequest struct {
}

type OpsAgentsListResponse struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Data    []OpsAgentInfo `json:"data,omitempty"`
}

type OpsAlert struct {
	Severity    string                 `json:"severity,omitempty"`
	Service     string                 `json:"service,omitempty"`
	Instance    string                 `json:"instance,omitempty"`
	Summary     string                 `json:"summary,omitempty"`
	StartsAt    string                 `json:"starts_at,omitempty"`
	EndsAt      string                 `json:"ends_at,omitempty"`
	Duration    string                 `json:"duration,omitempty"`
	Silenced    bool                   `json:"silenced,omitempty"`
	Labels      map[string]interface{} `json:"labels,omitempty"`
	Annotations map[string]interface{} `json:"annotations,omitempty"`
}

type OpsAlertSilenceDeleteRequest struct {
	ID string `uri:"id"`
}

type OpsAlertSilenceRequest struct {
	AlertID  string `json:"alertId"`
	Duration int    `json:"duration"` // 静默时长（分钟）
}

type OpsAlertSilenceResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsAlertsRequest struct {
}

type OpsAlertsResponse struct {
	Alerts []OpsAlert `json:"alerts"`
}

type OpsBackupCreateRequest struct {
	Name string `json:"name"`
}

type OpsBackupCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupDeleteRequest struct {
	ID string `uri:"id"`
}

type OpsBackupDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupDownloadRequest struct {
	ID string `uri:"id"`
}

type OpsBackupDownloadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsBackupsListRequest struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type OpsBackupsListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsConfigRequest struct {
}

type OpsConfigResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsCpuMetrics struct {
	UsagePercent float64   `json:"usagePercent"`
	Cores        int32     `json:"cores"`
	PerCore      []float64 `json:"perCore,omitempty"`
	Load1M       float64   `json:"load1m"`
	Load5M       float64   `json:"load5m"`
	Load15M      float64   `json:"load15m"`
}

type OpsDiskMetrics struct {
	MountPoint     string  `json:"mountPoint"`
	Device         string  `json:"device"`
	FsType         string  `json:"fsType"`
	TotalBytes     uint64  `json:"totalBytes"`
	UsedBytes      uint64  `json:"usedBytes"`
	AvailableBytes uint64  `json:"availableBytes"`
	UsagePercent   float64 `json:"usagePercent"`
}

type OpsExecCommandRequest struct {
	AgentID string   `uri:"agentId"`
	Command string   `json:"command"`
	Args    []string `json:"args"`
	Timeout int32    `json:"timeout"`
}

type OpsExecCommandResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    OpsExecCommandResult `json:"data,omitempty"`
}

type OpsExecCommandResult struct {
	Success  bool   `json:"success"`
	ExitCode int32  `json:"exitCode"`
	Stdout   string `json:"stdout"`
	Stderr   string `json:"stderr"`
}

type OpsFunctionsRequest struct {
}

type OpsFunctionsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsHealthCheck struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Enabled     bool   `json:"enabled"`
	Type        string `json:"type"`
	Kind        string `json:"kind"`
	Target      string `json:"target"`
	Expect      string `json:"expect"`
	Region      string `json:"region"`
	Interval    int    `json:"interval"`
	IntervalSec int    `json:"intervalSec"`
	TimeoutMs   int    `json:"timeoutMs"`
}

type OpsHealthGetRequest struct {
}

type OpsHealthGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsHealthRunRequest struct {
	ID string `json:"id"`
}

type OpsHealthRunResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsHealthUpdateRequest struct {
	Enabled bool             `json:"enabled"`
	Checks  []OpsHealthCheck `json:"checks"`
}

type OpsHealthUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMQRequest struct {
}

type OpsMQResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMaintenanceGetRequest struct {
}

type OpsMaintenanceGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMaintenanceUpdateRequest struct {
	Enabled bool                   `json:"enabled"`
	Message string                 `json:"message"`
	Windows []OpsMaintenanceWindow `json:"windows"`
}

type OpsMaintenanceUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsMaintenanceWindow struct {
	ID          string `json:"id"`
	GameID      string `json:"gameId"`
	Env         string `json:"env"`
	Start       string `json:"start"`
	End         string `json:"end"`
	Message     string `json:"message"`
	BlockWrites bool   `json:"blockWrites"`
}

type OpsManagedProcess struct {
	Name         string `json:"name"`
	Command      string `json:"command"`
	WorkingDir   string `json:"workingDir"`
	State        string `json:"state"`
	Pid          int32  `json:"pid"`
	RestartCount int32  `json:"restartCount"`
	LastStart    string `json:"lastStart,omitempty"`
}

type OpsMemoryMetrics struct {
	TotalBytes     uint64  `json:"totalBytes"`
	UsedBytes      uint64  `json:"usedBytes"`
	AvailableBytes uint64  `json:"availableBytes"`
	UsagePercent   float64 `json:"usagePercent"`
	SwapTotal      uint64  `json:"swapTotal"`
	SwapUsed       uint64  `json:"swapUsed"`
}

type OpsMetricsData struct {
	AgentID   string              `json:"agentId"`
	Timestamp string              `json:"timestamp"`
	CPU       OpsCpuMetrics       `json:"cpu"`
	Memory    OpsMemoryMetrics    `json:"memory"`
	Disks     []OpsDiskMetrics    `json:"disks,omitempty"`
	Networks  []OpsNetworkMetrics `json:"networks,omitempty"`
}

type OpsMetricsQuery struct {
	Start string `form:"start"`
	End   string `form:"end"`
}

type OpsMetricsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNetworkMetrics struct {
	Interface   string `json:"interface"`
	BytesSent   uint64 `json:"bytesSent"`
	BytesRecv   uint64 `json:"bytesRecv"`
	PacketsSent uint64 `json:"packetsSent"`
	PacketsRecv uint64 `json:"packetsRecv"`
}

type OpsNodeActionRequest struct {
	NodeID string `uri:"nodeId"`
}

type OpsNodeCommandsQuery struct {
	NodeID string `form:"nodeId"`
}

type OpsNodeCommandsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeDrainResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeMetaRequest struct {
	NodeID string `uri:"nodeId"`
}

type OpsNodeMetaResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeRestartResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodeUndrainResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNodesRequest struct {
}

type OpsNodesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNotificationChannel struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	URL    string `json:"url"`
	Secret string `json:"secret"`
}

type OpsNotificationRule struct {
	Event         string   `json:"event"`
	Channels      []string `json:"channels"`
	ThresholdDays int      `json:"thresholdDays"`
}

type OpsNotificationsGetRequest struct {
}

type OpsNotificationsGetResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsNotificationsUpdateRequest struct {
	Enabled  bool                     `json:"enabled"`
	Channels []OpsNotificationChannel `json:"channels"`
	Rules    []OpsNotificationRule    `json:"rules"`
}

type OpsNotificationsUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsProcessActionRequest struct {
	AgentID string `uri:"agentId"`
	Name    string `uri:"name"`
	Force   bool   `json:"force"`
}

type OpsProcessActionResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    int32  `json:"pid,omitempty"`
}

type OpsProcessStartRequest struct {
	AgentID string `uri:"agentId"`
	Name    string `uri:"name"`
}

type OpsProcessStartResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    int32  `json:"pid,omitempty"`
}

type OpsServiceItem struct {
	ID             string              `json:"id"`
	Name           string              `json:"name"`
	Type           string              `json:"type"`
	Status         string              `json:"status"`
	Address        string              `json:"address"`
	GameID         string              `json:"gameId"`
	Env            string              `json:"env"`
	Version        string              `json:"version"`
	Region         string              `json:"region"`
	Zone           string              `json:"zone"`
	Labels         map[string]string   `json:"labels"`
	FunctionsCount int                 `json:"functionsCount"`
	LastSeen       string              `json:"lastSeen"`
	Metadata       *OpsServiceMetadata `json:"metadata"`
}

type OpsServiceMetadata struct {
	Processes      []OpsServiceProcess `json:"processes"`
	ProcessesCount int                 `json:"processesCount"`
}

type OpsServiceProcess struct {
	ServiceID    string   `json:"service_id"`
	Addr         string   `json:"addr"`
	Version      string   `json:"version"`
	LastSeenUnix int64    `json:"last_seen_unix"`
	FunctionIDs  []string `json:"function_ids"`
	Functions    int      `json:"functions"`
}

type OpsServicesRequest struct {
}

type OpsServicesResponse struct {
	Services []OpsServiceItem `json:"services"`
	Total    int              `json:"total"`
}

type OpsSilenceDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OpsSilencesRequest struct {
}

type OpsSilencesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OverviewMetrics struct {
	DAU        int     `json:"dau"`
	MAU        int     `json:"mau"`
	NewUsers   int     `json:"newUsers"`
	Revenue    float64 `json:"revenue"`
	ARPU       float64 `json:"arpu"`
	ARPPU      float64 `json:"arppu"`
	PayingRate float64 `json:"payingRate"`
}

type OverviewRequest struct {
	AnalyticsQuery
}

type OverviewResponse struct {
	Metrics OverviewMetrics `json:"metrics"`
	Trends  interface{}     `json:"trends"`
}

type PacksExportRequest struct {
	ID string `form:"id"`
}

type PacksExportResponse struct {
	Filename    string `json:"filename,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	Content     []byte `json:"content,omitempty"`
}

type PacksImportRequest struct {
	Archive string `json:"archive"`
}

type PacksImportResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type PacksListRequest struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type PacksListResponse struct {
	Manifest           interface{} `json:"manifest,omitempty"`
	Packs              interface{} `json:"packs,omitempty"`
	Counts             interface{} `json:"counts,omitempty"`
	ETag               string      `json:"etag,omitempty"`
	ExportAuthRequired bool        `json:"exportAuthRequired,omitempty"`
}

type PacksPluginRequest struct {
	Pack string `form:"pack"`
	Path string `form:"path"`
}

type PacksPluginResponse struct {
	Content string `json:"content,omitempty"`
}

type PacksReloadRequest struct {
}

type PacksReloadResponse struct {
	OK        bool   `json:"ok"`
	UpdatedAt string `json:"updatedAt"`
}

type PaymentTransaction struct {
	Id            string  `json:"id"`
	UserId        string  `json:"userId"`
	ProductId     string  `json:"productId"`
	Amount        float64 `json:"amount"`
	Currency      string  `json:"currency"`
	Status        string  `json:"status"`
	PaymentMethod string  `json:"paymentMethod"`
	CreatedAt     string  `json:"createdAt"`
}

type PaymentsIngestRequest struct {
	GameId       string      `json:"gameId"`
	Env          string      `json:"env"`
	Transactions interface{} `json:"transactions"`
	Timestamp    string      `json:"timestamp"`
}

type PaymentsIngestResponse struct {
	Accepted int    `json:"accepted"`
	Rejected int    `json:"rejected"`
	BatchId  string `json:"batchId"`
}

type PaymentsMetrics struct {
	Revenue        float64 `json:"revenue"`
	Transactions   int     `json:"transactions"`
	PayingUsers    int     `json:"payingUsers"`
	ARPU           float64 `json:"arpu"`
	ARPPU          float64 `json:"arppu"`
	ConversionRate float64 `json:"conversionRate"`
}

type PaymentsProductTrendRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
	Limit     int    `form:"limit,optional,default=10"`
}

type PaymentsProductTrendResponse struct {
	Items []ProductTrend `json:"items"`
}

type PaymentsRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type PaymentsResponse struct {
	Metrics PaymentsMetrics `json:"metrics"`
	Trends  interface{}     `json:"trends"`
}

type PaymentsSummary struct {
	Date         string  `json:"date"`
	Revenue      float64 `json:"revenue"`
	Transactions int     `json:"transactions"`
	Users        int     `json:"users"`
}

type PaymentsSummaryRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
	GroupBy   string `form:"groupBy,optional,default=day"` // day, week, month
}

type PaymentsSummaryResponse struct {
	Items []PaymentsSummary `json:"items"`
}

type PaymentsTransactionsRequest struct {
	Page      int    `form:"page,optional,default=1"`
	PageSize  int    `form:"pageSize,optional,default=20"`
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	Status    string `form:"status"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type PaymentsTransactionsResponse struct {
	Items []PaymentTransaction `json:"items"`
	Total int64                `json:"total"`
	Page  int                  `json:"page"`
	Size  int                  `json:"pageSize"`
}

type PendingFunction struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	Requester string `json:"requester"`
	CreatedAt string `json:"createdAt"`
}

type Permission struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Category    string `json:"category"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type PermissionDetailRequest struct {
	ID string `uri:"id"`
}

type PermissionDetailResponse struct {
	Permission
}

type PermissionsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Category string `form:"category"`
	Resource string `form:"resource"`
}

type PermissionsListResponse struct {
	Items []Permission `json:"items"`
	Total int64        `json:"total"`
	Page  int          `json:"page"`
	Size  int          `json:"pageSize"`
}

type PlatformInfo struct {
	Name    string   `json:"name"`    // 平台名称
	Enabled bool     `json:"enabled"` // 是否启用
	Methods []string `json:"methods"` // 支持的方法列表
}

type Player struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	GameId    string `json:"gameId"`
	Status    int    `json:"status"`  // 1:active 0:banned 2:suspended
	Balance   int64  `json:"balance"` // 游戏货币
	Level     int    `json:"level"`
	Vip       int    `json:"vip"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type PlayerBalanceRequest struct {
	ID     string `uri:"id"`
	Amount int64  `json:"amount"`
	Reason string `json:"reason"`
}

type PlayerBalanceResponse struct {
	Player
}

type PlayerCreateRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	GameId   string `json:"gameId"`
}

type PlayerCreateResponse struct {
	Player
}

type PlayerDeleteRequest struct {
	ID string `uri:"id"`
}

type PlayerDetailRequest struct {
	ID string `uri:"id"`
}

type PlayerDetailResponse struct {
	Player
}

type PlayerUpdateRequest struct {
	ID       string `uri:"id"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Status   int    `json:"status"`
	Level    int    `json:"level"`
	Vip      int    `json:"vip"`
}

type PlayerUpdateResponse struct {
	Player
}

type PlayersListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	GameId   string `form:"gameId"`
	Search   string `form:"search"`
	Status   int    `form:"status"`
	Level    int    `form:"level"`
	Vip      int    `form:"vip"`
}

type PlayersListResponse struct {
	Items []Player `json:"items"`
	Total int64    `json:"total"`
	Page  int      `json:"page"`
	Size  int      `json:"pageSize"`
}

type ProductTrend struct {
	ProductId   string  `json:"productId"`
	ProductName string  `json:"productName"`
	Revenue     float64 `json:"revenue"`
	Sales       int     `json:"sales"`
	Growth      float64 `json:"growth"`
}

type ProfileGame struct {
	GameId      string      `json:"gameId"`
	GameName    string      `json:"gameName"`
	Color       string      `json:"color"`
	Envs        []string    `json:"envs"`
	EnvMeta     interface{} `json:"envMeta"`
	Permissions []string    `json:"permissions"`
}

type ProfileGamesRequest struct {
}

type ProfileGamesResponse struct {
	Games []ProfileGame `json:"games"`
}

type ProfileGetRequest struct {
}

type ProfileGetResponse struct {
	ProfileInfo
}

type ProfileInfo struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Nickname  string   `json:"nickname"`
	Email     string   `json:"email"`
	Phone     string   `json:"phone"`
	Roles     []string `json:"roles"`
	Avatar    string   `json:"avatar"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type ProfilePasswordRequest struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ProfilePermission struct {
	Resource string   `json:"resource"`
	Actions  []string `json:"actions"`
	GameId   string   `json:"gameId,omitempty"`
	Env      string   `json:"env,omitempty"`
}

type ProfilePermissionsRequest struct {
	GameId string `form:"gameId"`
	Env    string `form:"env"`
}

type ProfilePermissionsResponse struct {
	Permissions   []ProfilePermission `json:"permissions"`
	Admin         bool                `json:"admin"`
	Roles         []string            `json:"roles"`
	PermissionIDs []string            `json:"permissionIDs,omitempty"`
}

type ProfileUpdateRequest struct {
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
}

type ProviderActionRequest struct {
	ID string `uri:"id"`
}

type ProviderDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProviderDetailRequest struct {
	ID string `uri:"id"`
}

type ProviderDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProviderReloadResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersCapabilitiesRequest struct {
}

type ProvidersCapabilitiesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersDescriptorsRequest struct {
}

type ProvidersDescriptorsResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersEntitiesRequest struct {
	ID string `uri:"id"`
}

type ProvidersEntitiesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ProvidersListRequest struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type ProvidersListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RateLimit struct {
	Id        string      `json:"id"`
	Name      string      `json:"name"`
	Resource  string      `json:"resource"` // function, api, user
	Limit     int         `json:"limit"`    // 每秒请求数
	Window    int         `json:"window"`   // 时间窗口（秒）
	Action    string      `json:"action"`   // reject, throttle
	Rules     interface{} `json:"rules"`
	Status    int         `json:"status"`
	UpdatedAt string      `json:"updatedAt"`
}

type RateLimitDeleteRequest struct {
	ID string `uri:"id"`
}

type RateLimitGetRequest struct {
	ID string `uri:"id"`
}

type RateLimitPreviewRequest struct {
	Rules interface{} `json:"rules"`
}

type RateLimitPreviewResponse struct {
	Matches interface{} `json:"matches"`
	Impact  interface{} `json:"impact"`
}

type RateLimitResponse struct {
	RateLimit
}

type RateLimitUpsertRequest struct {
	Name     string      `json:"name"`
	Resource string      `json:"resource"`
	Limit    int         `json:"limit"`
	Window   int         `json:"window"`
	Action   string      `json:"action"`
	Rules    interface{} `json:"rules"`
}

type RateLimitsListRequest struct {
	Resource string `form:"resource"`
}

type RateLimitsListResponse struct {
	Items []RateLimit `json:"items"`
}

type RealtimeMetrics struct {
	OnlineUsers    int         `json:"onlineUsers"`
	ActiveSessions int         `json:"activeSessions"`
	QPS            float64     `json:"qps"`
	AvgLatency     float64     `json:"avgLatency"`
	ErrorRate      float64     `json:"errorRate"`
	TopEvents      interface{} `json:"topEvents"`
}

type RealtimeRequest struct {
	GameId string `form:"gameId"`
	Env    string `form:"env"`
}

type RealtimeResponse struct {
	RealtimeMetrics
	Timestamp string `json:"timestamp"`
}

type RealtimeSeriesRequest struct {
	GameId   string `form:"gameId"`
	Env      string `form:"env"`
	Interval string `form:"interval,optional,default=1m"` // 1m, 5m, 15m
	Duration int    `form:"duration,optional,default=60"` // 分钟
}

type RealtimeSeriesResponse struct {
	Series interface{} `json:"series"`
}

type RegistryAgent struct {
	AgentID      string `json:"AgentID"`
	GameID       string `json:"GameID,omitempty"`
	Env          string `json:"Env,omitempty"`
	RpcAddr      string `json:"RpcAddr,omitempty"`
	Functions    int    `json:"Functions"`
	Healthy      bool   `json:"Healthy"`
	ExpiresInSec int    `json:"ExpiresInSec"`
}

type RegistryCoverage struct {
	GameEnv   string                          `json:"game_env"`
	Functions map[string]RegistryCoverageStat `json:"functions"`
	Uncovered []string                        `json:"uncovered"`
}

type RegistryCoverageStat struct {
	Healthy int `json:"healthy"`
	Total   int `json:"total"`
}

type RegistryFunction struct {
	GameID string   `json:"GameID,omitempty"`
	ID     string   `json:"ID"`
	Agents []string `json:"Agents,omitempty"`
}

type RegistryRequest struct {
}

type RegistryResponse struct {
	Agents      []RegistryAgent     `json:"agents"`
	Functions   []RegistryFunction  `json:"functions"`
	Assignments map[string][]string `json:"assignments"`
	Coverage    []RegistryCoverage  `json:"coverage"`
}

type ReloadPlatformConfigResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Success bool   `json:"success,omitempty"`
}

type RenameDirectoryRequest struct {
	OldPrefix string `json:"old_prefix"`
	NewPrefix string `json:"new_prefix"`
}

type RenameDirectoryResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type RetentionCohort struct {
	Cohort    string    `json:"cohort"`
	Users     int       `json:"users"`
	Retention []float64 `json:"retention"` // Day 1, 3, 7, 14, 30
}

type RetentionRequest struct {
	GameId    string `form:"gameId"`
	Env       string `form:"env"`
	Cohort    string `form:"cohort"` // daily, weekly, monthly
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type RetentionResponse struct {
	Cohorts []RetentionCohort `json:"cohorts"`
}

type Role struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Permissions []string `json:"permissions"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

type RoleCreateRequest struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Permissions []string `json:"permissions"`
}

type RoleCreateResponse struct {
	Role
}

type RoleDeleteRequest struct {
	ID string `uri:"id"`
}

type RoleDetailRequest struct {
	ID string `uri:"id"`
}

type RoleDetailResponse struct {
	Role
}

type RoleUpdateRequest struct {
	ID          string   `uri:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Permissions []string `json:"permissions"`
}

type RoleUpdateResponse struct {
	Role
}

type RolesListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Category string `form:"category"`
	Search   string `form:"search"`
}

type RolesListResponse struct {
	Items []Role `json:"items"`
	Total int64  `json:"total"`
	Page  int    `json:"page"`
	Size  int    `json:"pageSize"`
}

type RootRequest struct {
}

type RootResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type RouteItem struct {
	Path       string                 `json:"path"`
	Name       string                 `json:"name"`
	Icon       string                 `json:"icon"`
	Component  string                 `json:"component"`
	Meta       map[string]interface{} `json:"meta"`
	Routes     []RouteItem            `json:"routes"`
	HideInMenu bool                   `json:"hideInMenu"`
}

type SchemaCreateRequest struct {
	Name   string      `json:"name"`
	Schema interface{} `json:"schema"`
}

type SchemaCreateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaDeleteRequest struct {
	ID string `uri:"id"`
}

type SchemaDeleteResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaDetailRequest struct {
	ID string `uri:"id"`
}

type SchemaDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaRawValidateRequest struct {
	Schema interface{} `json:"schema"`
	Data   interface{} `json:"data"`
}

type SchemaRawValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaUIConfigRequest struct {
	ID string `uri:"id"`
}

type SchemaUIConfigResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaUIConfigUpdateRequest struct {
	ID     string      `uri:"id"`
	Config interface{} `json:"config"`
}

type SchemaUIConfigUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaUpdateRequest struct {
	ID     string      `uri:"id"`
	Schema interface{} `json:"schema"`
}

type SchemaUpdateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemaValidateRequest struct {
	ID   string      `uri:"id"`
	Data interface{} `json:"data"`
}

type SchemaValidateResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SchemasListRequest struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type SchemasListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SignedUrlRequest struct {
	Path   string `form:"path"`
	Expire int    `form:"expire"`
}

type SignedUrlResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Silence struct {
	Id        string      `json:"id"`
	AlertType string      `json:"alertType"`
	Matchers  interface{} `json:"matchers"`
	StartAt   string      `json:"startAt"`
	EndAt     string      `json:"endAt"`
	CreatedBy string      `json:"createdBy"`
}

type SilenceDeleteRequest struct {
	ID string `uri:"id"`
}

type SilencesListRequest struct {
}

type SilencesListResponse struct {
	Items []Silence `json:"items"`
}

type StatusRequest struct {
}

type StatusResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type StreamJobRequest struct {
	JobID string `uri:"jobId"`
}

type StreamJobResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type StreamMessagesRequest struct {
}

type StreamMessagesResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type TermDeleteRequest struct {
	Domain string `json:"domain"` // entity | operation
	Alias  string `json:"alias"`  // 要删除的别名
}

type TermDeleteResponse struct {
	Ok bool `json:"ok"`
}

type TermItem struct {
	Id        int64  `json:"id"`
	Domain    string `json:"domain"`              // entity | operation
	TermKey   string `json:"term_key"`            // 原始术语键
	Alias     string `json:"alias"`               // 别名
	DisplayZh string `json:"display_zh"` // 中文显示
	DisplayEn string `json:"display_en"` // 英文显示
	Order     int64  `json:"order"`      // 排序
}

type TermUpsertRequest struct {
	Domain    string `json:"domain"`              // entity | operation
	TermKey   string `json:"term_key"`            // 原始术语键
	Alias     string `json:"alias"`               // 别名
	DisplayZh string `json:"display_zh"` // 中文显示
	DisplayEn string `json:"display_en"` // 英文显示
	Order     int64  `json:"order"`      // 排序
}

type TermUpsertResponse struct {
	Ok bool `json:"ok"`
}

type TermsListRequest struct {
	Domain string `json:"domain"` // entity | operation
}

type TermsListResponse struct {
	Items []TermItem `json:"items"`
}

type Ticket struct {
	Id        int64    `json:"id"`
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	Category  string   `json:"category"`
	Priority  string   `json:"priority"`
	Status    string   `json:"status"`
	Assignee  string   `json:"assignee"`
	Tags      []string `json:"tags"`
	PlayerId  string   `json:"playerId"`
	Contact   string   `json:"contact"`
	GameId    string   `json:"gameId"`
	Env       string   `json:"env"`
	Source    string   `json:"source"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type TicketCommentCreateRequest struct {
	TicketID string `uri:"ticketId"`
	Content  string `json:"content"`
}

type TicketCommentsRequest struct {
	TicketID string `uri:"ticketId"`
}

type TicketCommentsResponse struct {
	Items []Comment `json:"items"`
}

type TicketCreateRequest struct {
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category string   `json:"category"`
	Priority string   `json:"priority,optional,default=medium"`
	Tags     []string `json:"tags"`
	PlayerId string   `json:"playerId"`
	Contact  string   `json:"contact"`
	GameId   string   `json:"gameId"`
	Env      string   `json:"env"`
}

type TicketDeleteRequest struct {
	ID string `uri:"id"`
}

type TicketDetailRequest struct {
	ID string `uri:"id"`
}

type TicketDetailResponse struct {
	Ticket
	Comments []Comment `json:"comments,omitempty"`
}

type TicketTransitionRequest struct {
	ID     string `uri:"id"`
	Status string `json:"status"` // open, in_progress, resolved, closed
	Note   string `json:"note"`
}

type TicketUpdateRequest struct {
	ID       string   `uri:"id"`
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category string   `json:"category"`
	Priority string   `json:"priority"`
	Assignee string   `json:"assignee"`
	Tags     []string `json:"tags"`
}

type TicketsListRequest struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=20"`
	Status   string `form:"status"`
	Category string `form:"category"`
	Priority string `form:"priority"`
	Assignee string `form:"assignee"`
}

type TicketsListResponse struct {
	Items []Ticket `json:"items"`
	Total int64    `json:"total"`
	Page  int      `json:"page"`
	Size  int      `json:"pageSize"`
}

type UploadObjectData struct {
	Key string `json:"key"`
	URL string `json:"url"`
}

type UploadObjectRequest struct {
}

type UploadObjectResponse struct {
	Code    int              `json:"code"`
	Message string           `json:"message"`
	Data    UploadObjectData `json:"data"`
}

type UserInfo struct {
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
	Nickname string   `json:"nickname,omitempty"`
	Email    string   `json:"email,omitempty"`
	Phone    string   `json:"phone,omitempty"`
}

type WorkspaceConfig struct {
	ObjectKey   string              `json:"objectKey"`
	Title       string              `json:"title,omitempty"`
	Description string              `json:"description,omitempty"`
	Layout      interface{}         `json:"layout,omitempty"`
	Published   bool                `json:"published"`
	Status      string              `json:"status,omitempty"`
	PublishedAt string              `json:"publishedAt,omitempty"`
	PublishedBy string              `json:"publishedBy,omitempty"`
	MenuOrder   int                 `json:"menuOrder"`
	Version     int                 `json:"version,omitempty"`
	Meta        WorkspaceConfigMeta `json:"meta,omitempty"`
}

type WorkspaceConfigDeleteRequest struct {
	ObjectKey string `uri:"objectKey"`
}

type WorkspaceConfigDeleteResponse struct {
	Message string `json:"message"`
}

type WorkspaceConfigGetRequest struct {
	ObjectKey string `uri:"objectKey"`
}

type WorkspaceConfigGetResponse struct {
	WorkspaceConfig
}

type WorkspaceConfigMeta struct {
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

type WorkspaceConfigSaveRequest struct {
	ObjectKey   string      `uri:"objectKey"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Layout      interface{} `json:"layout,omitempty"`
	Status      string      `json:"status"`
	MenuOrder   int         `json:"menuOrder"`
}

type WorkspaceConfigSaveResponse struct {
	WorkspaceConfig
}

type WorkspaceConfigsListRequest struct {
}

type WorkspaceConfigsListResponse struct {
	Items []WorkspaceConfig `json:"items"`
}

type WorkspacePublishRequest struct {
	ObjectKey   string `uri:"objectKey"`
	PublishedBy string `json:"publishedBy"`
}

type WorkspacePublishResponse struct {
	Published bool   `json:"published"`
	ObjectKey string `json:"objectKey"`
}

type WorkspacePublishedListRequest struct {
}

type WorkspacePublishedListResponse struct {
	Items []WorkspaceConfig `json:"items"`
}

type WorkspaceRollbackRequest struct {
	ObjectKey string `uri:"objectKey"`
	VersionId string `json:"versionId"`
}

type WorkspaceRollbackResponse struct {
	ObjectKey string `json:"objectKey"`
	Version   int    `json:"version"`
}

type WorkspaceUnpublishRequest struct {
	ObjectKey string `uri:"objectKey"`
}

type WorkspaceUnpublishResponse struct {
	Published bool   `json:"published"`
	ObjectKey string `json:"objectKey"`
}

type WorkspaceVersionDetailRequest struct {
	ObjectKey string `uri:"objectKey"`
	VersionId string `uri:"versionId"`
}

type WorkspaceVersionDetailResponse struct {
	WorkspaceVersionRecord
}

type WorkspaceVersionRecord struct {
	Id                 string      `json:"id"`
	ObjectKey          string      `json:"objectKey"`
	Version            int         `json:"version"`
	Config             interface{} `json:"config"`
	IsCurrentDraft     bool        `json:"isCurrentDraft"`
	IsCurrentPublished bool        `json:"isCurrentPublished"`
	CreatedAt          string      `json:"createdAt,omitempty"`
	CreatedBy          string      `json:"createdBy,omitempty"`
	Comment            string      `json:"comment,omitempty"`
}

type WorkspaceVersionsRequest struct {
	ObjectKey string `uri:"objectKey"`
	From      string `form:"from"`
	To        string `form:"to"`
}

type WorkspaceVersionsResponse struct {
	Items                   []WorkspaceVersionRecord `json:"items"`
	CurrentDraftVersion     int                      `json:"currentDraftVersion"`
	CurrentPublishedVersion int                      `json:"currentPublishedVersion"`
}

// MigrationResult represents the result of a data migration operation.
type MigrationResult struct {
	Name      string    `json:"name"`
	Success   bool      `json:"success"`
	Error     string    `json:"error,omitempty"`
	Duration  string    `json:"duration,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
}
